### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#10]
Since we are hosting this publicly, it should have a license. I personally like MIT or BSD3.

**Comment by jlibovicky** [comment]
We have depedencies having: Python Software Foundation Licence, Apace 2.0 Licence, MIT Licence which are OK for more or less everything.

Unfornutely: python-Levenshtein and ansi2html are under GPL. We need to replace them if we want to have a less restrictive licence.

**Comment by jlibovicky** [comment]
ansi2html is used in the logbook which serves the experiments log in a web app. We can replace it with this http://www.pixelbeat.org/scripts/ansi2html.sh which is under LGPL.

**Comment by tomasmcz** [comment]
OK, lets make a checklist:

- [ ] banish Levenshtein
- [ ] replace ansi2html
- [ ] select a reasonable license

**Comment by tomasmcz** [comment]
How are the data for the ACL MMMT licensed? Can I put a subset of them on my web at ufal and have Travis download them and run tests on them?

**Comment by jlibovicky** [comment]
The data is licensed under Creative Commons: Attribution-NonCommercial-ShareAlike 4.0 International. (http://www.statmt.org/wmt16/multimodal-task.html) I think you can.

**Comment by jlibovicky** [comment]
OK, python-Levenshtein is now replaced by `difflib`, ansi2html changed to `ansiconv`. I would prefer BSD licence because it is more restrictive in acknowledging the authors, but does not restrict the use at all. Do you agree, @tomasmcz and @jindrahelcl?

**Comment by jindrahelcl** [comment]
I couldn't care less.
