### ISSUE TITLE
Soft alignment visualisation

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#108]
The goal is to be able to get images of alignment, which are seen everywhere in the NMT papers.

**Comment by jindrahelcl** [comment]
It should be possible (and quite cool) to add these alignments to tensorboard via tf.image_summary...

**Comment by cifkao** [comment]
@jindrahelcl I tried doing that [here](https://github.com/ufal/neuralmonkey/compare/master...cifkao:attention). But I don't know what `attentions_in_time` are and why there are (in the case of `tests/small.ini`) 11 of them.

Also, am I correct in assuming that the image always corresponds to the last sentence in the batch? I'm not sure how to get more than one image per batch or how to prevent it from being overwritten by the next batch…

**Comment by jindrahelcl** [comment]
Hi, as for now, (almost) all of the sequences are represented as a Python list of length ``max_output_len`` (``max_input_len`` for encoders). This dimension is in the code often called **time**. The contents of these lists are Tensorflow tensors, whose first dimension is the batch size. Note that this will change with  #116. Then, all of the sequences will be represented as single Tensors of shape ``[batch_size, time, (whatever_shape_of_the_tensor_of_one_token)]``

It is not clear what images are you talking about. It should always be as many images as there are sentences in the batch, though.

As for the images that should be generated from the alignment, I would do it the same way sample sentences are outputted during the validation, i.e. for starters, first 15 sentences from validation. Then we can add an option to log the validation output on a random or some selected subset of the data.

And the final answer:
``attentions_in_time`` is an array of the attention weights. These are the vectors that we want to visualize (I think). The array is **in time** which means it has length of whatever the maximum length of the __decoder__ is. Note that this can be longer than the output sequence and something must be done about that.
The Tensors in ``attentions_in_time`` have shape ``[batch_size, max_input_length]`` and should contain numbers from zero to one and should sum to one over the last dimension.
For example, the value on the index [24,6] in the 3rd tensor in this array is a probability with which the third word on the output is aligned to the seventh word on the input during decoding the 25th sentence in the batch

**Comment by cifkao** [comment]
@jindrahelcl @obo 
I think I managed to visualize the alignments for the first batch of validation data every `validation_period`; see #121. It's probably not the neatest possible solution, though, and I cannot guarantee I didn't break something.

I'm not sure what to do about the fact that the matrices are of fixed dimensions, as @jindrahelcl wrote.

I tried testing it only on `tests/small.ini` and the output didn't make a lot of sense (but neither did the translations).

**Comment by cifkao** [comment]
I can see that in `master`, the corresponding image summary is still in the graph, but it is no longer fetched during validation. Can you think of a clean way to do that in the new code?

**Comment by jlibovicky** [comment]
Sure, it's simple, I just forgot about it. You just add the fetches in the `next_to_execute` method and then you assign the results to the `image_summaries` field of the `ExecutionResults`. If you want to get familiar with the new runners, try it yourself, otherwise I can do it.

**Comment by cifkao** [comment]
Thank you, I will try to do it.
