### ISSUE TITLE
--dry-run for GPU memory check

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#111]
Add command-line option which would:
1. load the config (optionally check existence of source files but not load them)
2. build the TF model
3. run one batch and one validation with totally fake words

and either crash on out-of-memory error
or return success

**Comment by obo** [comment]
A tip from Milan Straka for more detailed memory footprint. So report this, if successful.

Ohledně paměti -- můžete se zkusit podívat, co kolik zabírá. Když tu síť
načtete na GPU/CPU a uložíte runtime_metadata jednoho vyhodnocení do
SummaryWriteru, ukáže vám to u všeho, kolik to zabírá paměti (takže
budete vědět, co je největší žrout a jestli by dynamické verze rnn
pomohly).

**Comment by jindrahelcl** [comment]
Instead of --dry-run CLI option, I would make a new executable neuralmonkey-check, which will do this (and can do various other checking things, too).

**Comment by jindrahelcl** [comment]
De-duping with #267
