### ISSUE TITLE
use dynamic RNNs in encoder and decoder for lower memory demands

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#114]
Follow tips from Milan Straka:

neznám NM tolik, ale nepoužívá stále ještě "rozbalený" enkodér (rnn)
a dekodér z seq2seq modulu? Tyhle rozbalené verze rekurentních sítí mají
tu nevýhodu, že zabírají hodně GPU RAM -- proto už v tf mají
i dynamic_rnn, který tím (tolik) netrpí. Takže enkodér můžete zkusit nahradit
v podstatě hned.

Co se týče těch dekodérů, tak "dynamické" verze právě pushují do tf
(tady je pull request na verzi bez attention https://github.com/tensorflow/tensorflow/pull/4686),
případně, pokud si v NM děláte dekódování ručně, je možné použít
rnn.raw_rnn (hodně obecná verze rnn, která stačí i na dynamické
dékodování).

**Comment by jindrahelcl** [comment]
#116 does introduces the dynamic RNN to encoders. The manual decoding could be refactored to dynamic RNNs as well.
