### ISSUE TITLE
derive all objects from a new class 'modelbit'; support common features through this

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#117]
All model objects are now derived from the very basic python class 'object'.
I suggest to change this to a new class 'modelbit'. ModelBit would then support common configuration options such as:

save_graph_before_this=output_filename
save_graph_after_this=output_filename2
tf_device="/gpu:1"

Ideally (but I'm not sure Python OOP supports this), ModelBit constructor would take care of all the options and also somehow make sure the e.g. save_graph_after_this is run after the child constructor.

save_graph_before_this should be easy to handle and here is the code for it (yes, instantiating a new SummaryWriter for this):

```
log("Saving graph before XXX.")
ts=datetime.datetime.now().strftime("%Y-%m-%d_%H%M%S")
graph_writer = tf.train.SummaryWriter("graph-before-XXX."+ts,
  graph=tf.get_default_graph())
log("Graph saved, maybe not flushed yet.")
```

tf_device needs to wrap the child's constructor in "with tf.device(THE_DEVICE):"

**Comment by jindrahelcl** [comment]
ty nám ten krásnej kód chceš zprasit, viď? :-D

**Comment by obo** [comment]
Ne, ja chci prece zprasenej kod zkraslit. :-)

Ale predevsim chci:
- dovolit tech vic gpu
- zpristupnit graf i postupne, aby byl mensi a prehlednejsi
- vyhledove nejak podstatne zkraslit namespacy, aby graf svymi shluky odrazel strukturu site spis nez strukturu konfiguraku a postupneho volani funkci, ktere ten graf postavily

----- Original Message -----
> From: "Jindra Helcl" <notifications@github.com>
> To: "ufal/neuralmonkey" <neuralmonkey@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Wednesday, 26 October, 2016 14:48:36
> Subject: Re: [ufal/neuralmonkey] derive all objects from a new class 'modelbit'; support common features through this
> (#117)

> ty nám ten krásnej kód chceš zprasit, viď? :-D
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ufal/neuralmonkey/issues/117#issuecomment-256336790

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by jindrahelcl** [comment]
hotovo v #241. Akorát se to nejmenuje ModelBit ale ModelPart. Ani jedno se mi nelíbí.
