### ISSUE TITLE
Do not catch general exceptions in config_loader

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#12]
When you catch general exceptions there, every exception (eg. import error) from the module that you want something from gets caught and the the error message about non-existence of something that is clearly there is quite confusing. Btw. you should never just catch general exceptions. Fix this after I finish #4.

**Comment by jlibovicky** [comment]
Except line 70 where it can catch anything and print out misleading error message, it is perfectly fine elsewhere. It catches all exceptions, prints where this originates in the configuration file (so you can track it in the configuration) and print the complete original stack trace as if it crashed at the place the exception originated.

**Comment by jlibovicky** [comment]
I am making myself a checklist:

- [ ] treat differently various excpetion on line 70 and 72 (throw most of them further)
- [ ] when the general exception is cought, always print the line number that has caused that

**Comment by jlibovicky** [comment]
Since this file will have many changes during the transfer to python 3, I would postpone it after it is done.

**Comment by tomasmcz** [comment]
Btw. one of the consequences of this is that when you try to run the current version with Python 2.7, it runs out of stack while catching and re-raising an exception in config_loader. That should never happen.

**Comment by jlibovicky** [comment]
Tohle můžem zavřít, ne? Když se v konfiguraci chytá obecná exception, je to jenom, aby se zabalila do jiné excpetion (která ví, kde to bylo v tom konfiguráku) a pošle se dál. Žádnou excpetion to nikdy nesežere.

**Comment by jindrahelcl** [comment]
jo
