### ISSUE TITLE
Bias should not be subject for L2 regularization

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#122]
Řikal Milan na přednášce

**Comment by jindrahelcl** [comment]
When #127 is solved, there is a ``regularizer`` parameter for the ``get_variable`` function, that can be used for this.

**Comment by jlibovicky** [comment]
Is this really done?

**Comment by jindrahelcl** [comment]
By the regex in the generic trainer.

Dne 27. 7. 2017 7:30 odp. napsal uživatel "Jindřich Libovický" <
notifications@github.com>:
