### ISSUE TITLE
Saving of the whole graph, not just variable values.

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#130]
According to @obo, @foxik knows how.

**Comment by jlibovicky** [comment]
Why? Do you think it will make loading the run and server script faster?

**Comment by jindrahelcl** [comment]
I don't know exactly. @obo wants it, I don't really care.

**Comment by obo** [comment]
My understanding is that the whole graph is much more portable. A model saved with the graph should be easier to deploy. The code to run such a model needs to know only the inputs and outputs.

In the current form, a different server code would be needed for every model variation.

3. listopadu 2016 16:51:29 SEČ, Jindra Helcl <notifications@github.com> napsal:
>I don't know exactly. @obo wants it, I don't really care.


-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by foxik** [comment]
I also think it is a good idea, for the reasons @obo listed -- the `run` and `server` (and even scripts for further training, if you have some) can be model-architecture-agnostic, as long as the input and output nodes (and their format) are fixed.

**Comment by jlibovicky** [comment]
The `run` and `server` scripts are already model agnostic - they re-build whatever model is specified in the configuration, load the saved variables and wait for the data.

**Comment by foxik** [comment]
Currently you have to keep around the code which is able to rebuild all possible configurations. That makes managing the network construction code harder -- you have to be sure the names stay the same (you might want to add namescopes/rename variables for nice graphs) and that some higher-level TensorFlow ops stay the same(if tf.nn.rnn changes the names of the variables inside in new TensorFlow version, or if it is even removed, you would have to either reimplement the old one or do not use newest TensorFlow).

From one point of view, storing the whole MetaGraph is an ultimate configuration of the network itself :-)

But I agree that your configuration framework can handle the situation well, if you keep from changing the existing code and there are no backward-incompatible changes in TensorFlow.
