### ISSUE TITLE
Modes of computing the initial state of a decoder

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#131]
Nematus seems to use the average of all encoder states, Bahdanau uses projection of final backward state, and many more.

Do something to be able to configure this.

**Comment by jlibovicky** [comment]
We already have the encoder projection, don't we<

**Comment by jindrahelcl** [comment]
Yes

Dne 21. 9. 2017 1:35 odp. napsal uživatel "Jindřich Libovický" <
notifications@github.com>:
