### ISSUE TITLE
Developers' guidelines

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#132]
Put these things to the docs for developers:

- [x] How to install pylint and mypy, how to run tests.
- [ ] Reference to the style guidelines, number of columns, no backslashes, etc..

(...)

**Comment by jindrahelcl** [comment]
addressed in #255

**Comment by jlibovicky** [comment]
In fact, it's hidden here. http://neural-monkey.readthedocs.io/en/latest/github_dev.html
