### ISSUE TITLE
Problem in Post Editing Experiment

### ISSUE THREAD

**Issue by kadir-gunel** [ufal/neuralmonkey#133]
Hello, 
By following the tutorial, I am trying to make basic experiments with NMT tool but even though I copied and pasted directly from the tutorial page, I couldn't run the described post editing experiment. 
I am receiving parse value exception ("_Failed to load INI File: Error on line 21:  Cannot parse value: "Vocabulary.from_dataset_"). The line 21 describes the class=Vocabulary.from_dataset variable in configuration file.

Could you help?

ps : I am using the gpu version of tensorflow. And it seems like both TF and NeuralMonkey are installed correctly; I can import TensorFlow and NeuralMonkey from REPL.

**Comment by jindrahelcl** [comment]
Hi,

vocabulary should be with small v.

Cheers,
Jindra

Dne pátek 4. listopadu 2016 kadir-gunel <notifications@github.com>
napsal(a):
