### ISSUE TITLE
Make dropout configuration great again

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#135]
Dropout keep prob should be configurable to have different values at different places (embeddings vs state to output, ...)

The best way to do it is probably to change the constructors of encoders and decoders. Any suggestions?

**Comment by jlibovicky** [comment]
... and also the `feed_dict` methods. Go ahead ;-)

**Comment by jlibovicky** [comment]
AFAIK, this is done. Feel free to re-open, if think it is not.
