### ISSUE TITLE
make sure beam search works well

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#139]
We should be using beam search for participants' models. Make sure it works well.

**Comment by jindrahelcl** [comment]
That's not exactly an issue.. :-) More like a check list item. Maybe it would be better to start a WMT17 tuning task wiki page and put these things there.

**Comment by jindrahelcl** [comment]
And by wiki page, I mean something like this: [https://github.com/ufal/neuralmonkey/wiki/WMT-17-Neural-Tuning-Task-Preparation]

**Comment by jindrahelcl** [comment]
De-duplicating with #144
