### ISSUE TITLE
Ensembles

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#14]
Write support for ensemble models.

The idea is, in the end, to give the running script multiple *.ini files (or one with links to another experiments).

**Comment by jindrahelcl** [comment]
@jlibovicky nemáš nápady jak to udělat nějak pěkně? Muj nápad je přidat novej ensemble runner a ten to pustí. Tim se ale musí hrozně refactorovat všechno, co používá session a mohlo by používat graph. Aby bylo možný pak tomu ensemble runneru dát grafy s nainicializovanejma proměnnejma, který on už si pospouští na svejch datech.

Jo taky, ensemble u těchhle věcí znamená, že ti každej model vyhodí větu a její pravděpodobnost a ty pak vemeš tu nejlepší? Nebo se to i nějak mixuje po cestě (i když nevim jak by se to dělalo)?

**Comment by jlibovicky** [comment]
I would ensemble the decoders such that in every step all of the decoders will output a probability distribution over the dictionary and the output symbol selected from a combination of these distributions. The selected symbol will be then fed as an input all the other decoders.

A reasonable way to go is probably creating a EnsembleDecoder class which will handle the decoders in this way. I can imagine creating configuration for the ensemble automatically from provided _run.ini_ files.  The technically trickiest part will be how to load all the variables without running into conflicts in the variable scopes.

You may try to ask @tuetschek, he implemented something like this in his NLG project.

**Comment by tuetschek** [comment]
I have actually done exactly what @jlibovicky suggested – a new class that handles its sub-decoders. Each of the sub-decoders has a random suffix appended to its variable scope when training so that there are no clashes when running the decoding on a single machine. Also, I implemented [my own saving & loading](https://github.com/UFAL-DSG/tgen/blob/d2254e3812cfd5d3bf0597a92cfb8bf7b69c4172/tgen/tf_ml.py#L38-L66) with lower-level functions so that I can squeeze all the sub-decoders into one file.

A side note: it probably pays off to code it all to work inside of tensorflow, [my implementation](https://github.com/UFAL-DSG/tgen/blob/master/tgen/seq2seq_ensemble.py#L87-L106) is slow as hell.

**Comment by jlibovicky** [comment]
Udělal bych to takhle: když se pustí trénování, uděláš celý se to dá variable scopu, kterej bude mít jméno s náhodným suffixem a to jméno se uloží do souboru do adresáře ke všem těm logům a diffům. 

Pak si uděláš tool, kterej vezme jejich konfigurace (zkontroluje, jestl je to stejná verze gitu, jestli mají stejnou vocabulary a tak) a udělá to jeden konfigurák, kde to vyskládá všechny ty enkodéry a dekodéry a vytvoří jeden ensemblovací dekodér, kterej to bude správně mergovat ty distribuce a s tím konfugrám pak už půjde pustit model.

**Comment by tuetschek** [comment]
Jako že budeš mít jeden konfigurák, ale každej sub-model bude ve zvláštním souboru? To asi jde, možná to je jednodušší na provedení než to moje – asi by se měly dát použít `Saver` a `Loader`.

**Comment by jindrahelcl** [comment]
taky by asi šlo ještě dál abstrahovat ten main v tom konfiguráku, aby i ten byl objektem, dědil od něčeho jako `experiment` a pak už bys mohl dělat spoustu divů docela zadarmo s tim, co máme. Taky bude potom jednodušší ten spustitelnej soubor.

**Comment by tomasmcz** [comment]
@jlibovicky: It's great that you keep adding these complex new features to the pre-MTM milestone, while you say you have exactly one day to implement them. Today will be a heck of a programming spree for you, won't it?

**Comment by jindrahelcl** [comment]
Tuhle issue jsem otevřel já a ptal jsem se Jindry, jaký má nápady. Když už chceš mudrovat, přečti si o čem to je.

**Comment by tomasmcz** [comment]
Ale @jlibovicky to přidal pod pre-MTM milestone. Proti samotné diskusi nic nemám, naopak. Když už chceš mudrovat, přečti si o čem to je.

**Comment by jindrahelcl** [comment]
@jlibovicky To by znamenalo, že by se ty modely v ensemblu musely trénovat každej zvlášť, ne? V Edinburku to letos dělali tak, že vzali 5 posledních uloženejch modelů z jednoho běhu trénování. Spíš bychom potřebovali mít víc oddělenejch grafů, a každej z nich pouštět úplně zvlášť. Což zas je blbý protože se to nevejde do paměti.

Nebo mít jeden graf a v jednu chvíli jen jedny proměnný a pořád volat Saver.restore()

**Comment by jindrahelcl** [comment]
Jestli teda ensembly fungujou tak, že každej model vyplivne větu a její pravděpodobnost a do výsledku se vezme ta nejpravděpodobnější, tak se taky dá prostě pustit to samý pětkrát s různejma variables a nechat si plivat pravděpodobnosti (což asi máme zadarmo, ne?).

**Comment by jlibovicky** [comment]
ad předchozí: Jo, to by se muselo pustit tolikrát, kolik modelů chceme ensemblovat.

ad poslední: To je ale slabší model, než to o čem jsem mluvil. Zadarmo by to bylo v Theanu, kde ten graf je stateless, taky jsou ty variables přímo součástí toho grafu, tak to chce zjistit, jak dlouho trvá vyměnit ty proměnné. Problém bych viděl taky v tom, že věty, co vydají jednotlivé dekodéry, můžou mít různou délku. Delší věty žijou v mnohem větším pravděpodobnostním prostoru, takže jednotlivci tam mají výrazně menší pravděpodobnost. Takže by bylo potřeba to normalizovat (a asi to bude fungovat)

Kdybysme to ensemblovali na úrovni těch jednotlivých výstupů, tak například můžeme spravit,  že jeden dekodér se zblázní a obrovskou pravděpodobností vydá jedno slovo špatně, ostatní ho přehlasujou a on už jede v pohodě. Nevím ale, jak to tohle udělat s tím n-bestem.

Možná bych to zkusil nějak ohackovat. Ten *.meta soubor vypadá, že by to mohl být protobuffer a jsou tam napsaný jména těch proměnných. Ten by se dal naparsovat a přidat těm proměnným nějaké prefixy a pak při stavění grafu tak pojmenovat variable scopy, kde bude žít ten model. Ale je to je to samozřejmě hrozmě moc práce.

**Comment by tuetschek** [comment]
@jindrahelcl : to mi zní nějak moc jednoduše :-). to jde? resp. jsou ty pravděpodobnosti pak porovnatelné? moje ensembly aspoň fungujou tak, že se dohadujou na každým dalším slově...

**Comment by jindrahelcl** [comment]
@tuetschek Asi to neni moc chytrý, jak píše Jindra, čim delší věta, tim nižší ta pravděpodobnost bude. Pro stejně dlouhý věty si myslím, že by ty pravděpodobnosti porovnatelný být měly (pakliže jedeme nad stejnym slovníkem), ale zas tak moc si za tim nestojim..

Snažil jsem se vymyslet řešení, který by se vešlo do paměti na GPU, ale taky mi teď došlo, že ensembly se používaj až při překládání, a to asi klidně může běhat na CPU, a tam se to do paměti snad vejde (pokud budeme mít 5 modelů, každej se vešel do nějaký naší GPU, čili <= 6 GB, a taky pokud to na GPU i CPU zabírá stejně, tak stačí 32GB RAM)

@jlibovicky Pokud by se každej model zavřel do svýho grafu, tak se ty scopy můžou jmenovat stejně a můžem mít víc sessionů a celý by to mělo běhat, ne?

**Comment by jindrahelcl** [comment]
Done in #110
