### ISSUE TITLE
better TF namespaces, so that graph makes sense

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#140]
improve TF namespaces, e.g.:

- the two versions of the decoder in the graph should clearly indicate their use in the namespace name: decoder_for_training, and decoder_for_running
- dropouts should be grouped
- overall, the graph (before Adam) should be easy to explore by gradual expansion of a reasonable number of components

**Comment by jindrahelcl** [comment]
The parts of the graph **must not** be in different namespaces because the variables are shared. I was stuck by this fact almost a month..

**Comment by jindrahelcl** [comment]
How do you propose to "group" dropouts?

**Comment by obo** [comment]
use tf11+ name_scope instead of the variable scopes

**Comment by jlibovicky** [comment]
Solved with PR #217.
