### ISSUE TITLE
Include attention images in tutorial

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#141]
Ondra Cifka (@cifkao) has added drawing of attention images of the validation set to the branch bahdanau.

Make sure there is a tutorial that makes use of this.

**Comment by cifkao** [comment]
How do we add images?

**Comment by cifkao** [comment]
See http://neural-monkey.readthedocs.io/en/latest/visualization.html#attention-visualization

**Comment by cifkao** [comment]
We might have better images later.

**Comment by obo** [comment]
Thanks! I'm still reopening, please add a command usage for your script `tf_save_images.py` so that people know how to extract the sequence. Adding a `convert` call to make it then an animated GIF or something like that would be a bonus. :-)

**Comment by cifkao** [comment]
> Here, the source sentence is on the vertical axis and the target sentence on the horizontal axis, hence the 12th and following rows are totally blank (decoding is hard stopped after emitting end-of-sentence mark) while the trailing columns occasionally get some minor attention (the decoder is free to look beyond the last input word).

If this (what you added) was true, then the *target* sentence would be on the vertical axis. I think it's the other way around: The length of the *source* sentence is given – that accounts for the blank rows (see [this line](https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/decoding_function.py#L89) where the attention weights are masked using `input_weights`). But the length of the *target* sentence does not affect the number of RNN states (= the number of attention vectors), hence the noise at the end. In fact, I think the length of the output is not even inferred in the decoder, so it's not so easy to crop the image appropriately.

**Comment by obo** [comment]
Quite possibly!
I added the details to be sure we avoid confusion, I was asking for this type of correction. :-)
Please go ahead and fix my description. And possibly crop the image at least in one dimension, if the number is available.
Thanks, O.

----- Original Message -----
> From: "Ondřej Cífka" <notifications@github.com>
> To: "ufal/neuralmonkey" <neuralmonkey@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "State change" <state_change@noreply.github.com>
> Sent: Monday, 9 January, 2017 23:24:54
> Subject: Re: [ufal/neuralmonkey] Include attention images in tutorial (#141)

>> Here, the source sentence is on the vertical axis and the target sentence on the
>> horizontal axis, hence the 12th and following rows are totally blank (decoding
>> is hard stopped after emitting end-of-sentence mark) while the trailing columns
>> occasionally get some minor attention (the decoder is free to look beyond the
>> last input word).
> 
> If this (what you added) was true, then the *target* sentence would be on the
> vertical axis. I think it's the other way around: The length of the *source*
> sentence is given – that accounts for the blank rows (see [this
> line](https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/decoding_function.py#L89)
> where the attention weights are masked using `input_weights`). But the length
> of the *target* sentence does not affect the number of RNN states (= the number
> of attention vectors), hence the noise at the end. In fact, I think the length
> of the output is not even inferred in the decoder, so it's not so easy to crop
> the image appropriately.
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/ufal/neuralmonkey/issues/141#issuecomment-271427257

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo
