### ISSUE TITLE
Add factored translation and multitask learning and sequence labeling into test cases

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#145]

**Comment by jindrahelcl** [comment]
Už tam chybí jen multiobjective, a ten teď zadarmo nemáme. Ale @tomkocmi už to nějak řešil?

**Comment by tomkocmi** [comment]
Nevim jestli to co delam je uplne presne to, co v tomto issue chcete, ale ano pracuju na multiobjective s mnoha datasety. Zkousim to udelat tak, jak nakonec psal Jindrich v poslednim emailu "Re: Problem s tf.cond"

**Comment by jindrahelcl** [comment]
V tom případě bych tohle zavřel a až budeme mít nějaký funkční multiobjective trénování, tak se udělá test..
