### ISSUE TITLE
Evaluation functions

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#15]
Evaluation functions should be refactored in callable and comparable objects to simplify the training loop function. They can also define their own name so the output in the log need not to be the name of the function.

**Comment by tomasmcz** [comment]
Why should an evaluation **function** be an object and not just a function? What do you mean by “comparable objects”?

**Comment by jindrahelcl** [comment]
I wrote function because that's what it's called now. Stop trolling

I was not precise with the "comparable". What I mean is, that every evaluation function has to have defined another one which compares its scores. If you have score of 35 and score of 40, you don't know which one is better unless you know what the evaluation function was. So instead of function `bleu_4` or `bleu_1`, there will be a class BLEU, with:

- constructor that takes a length of the n-grams for compution of BLEU
- method `__call__(out, ref)` which  will run the evaluation on the corpora
- method `compare(score1, score2)` which compares two scores (in case of BLEU it just calls `cmp` on those scores
- method `get_name()` which returns nicely-formatted string, such as "BLEU 4"

**Comment by tomasmcz** [comment]
I'm not trolling, I genuinely wanted to know why would conceptualize that as an object. After you explained the issue with comparing, I would say that for most evaluation functions this would be a static class (btw. a concept that is absolutely useless and meaningless in Python). And even bleu should conceptually not be an object – it has no state, unless you want to parametrize it on n-gram size; and then it still has no state, as n-gram size does not change after initialization. Therefore it should be a function that returns a function. Although I admit that higher order functions are somewhat cumbersome in Python, I do not think that we should just replace them all with classes that are not classes and objects with no state in a java-like ObjectEvaluationFunctionBleuFactory style.c

**Comment by tomasmcz** [comment]
Python is a horrible language as is, and it really doesn't get any better by writing Java in it.

**Comment by jlibovicky** [comment]
I would like to avoid having functions returning functions being called from the configuration file. Unfortunately, the reflection tools in Python are too weak to later find out what function and with which parameters has been called that a function was created and it would be hardly possible to generate the run.ini file. In case of classes, the reflection tools are much better. Personally, I do not see having callable objects to be such a design disaster, given we write in Python. Btw. is there such a thing as static class in Python?

**Comment by tomasmcz** [comment]
I'm not saying that we should definitely stick to higher order functions in this particular case; just that we should think about semantics of the code.

Python has static variables and methods, so you can create something like a static class, but it does not make much sense in Python.

**Comment by tomasmcz** [comment]
@jlibovicky: This might also mean that we should rethink our approach to configuration, instead of creating more senseless, bogus pseudo-objects.

Just in case it wasn't clear: I'm using 'senseless' and similar words in their technical, semantical sense, I don't mean to sound judgemental.

**Comment by jindrahelcl** [comment]
> Python is a horrible language as is,

**Comment by jindrahelcl** [comment]
Ok, now I'm trolling.. Static classes are imo far better solution that a function that returns another function - at minimum it's better to read and it is easier to create unified API for all of these evaluators.
