### ISSUE TITLE
restucturedtext-lint won't work with sphinx extensions

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#168]
In th #164 we talked about using [restucturedtext-lint](https://github.com/twolfson/restructuredtext-lint) for automatic testing of quality of the `rst` files and docstrings. The linter is unfortunately unable to work work with Sphinx extensions we are using.

I can see several ways out of it:
* do not lint the `rst` files,
* do it it with a custom Python script and filter out complaints regarding the Sphinx extensions,
* convert all documentation to Markdown.

What do you think?

**Comment by jindrahelcl** [comment]
Which Sphinx extensions?

**Comment by jlibovicky** [comment]
At least `todo`. Some Sphinx directives can be registered to the linter and some of them not. It complains also about `automodule`and `toctree`, but I didn't find the directives in the sphinx package, so I can't tell whether they can work or not.

**Comment by jindrahelcl** [comment]
I see. Well, the question is, whether doing something about that is worth it or not. Personally, I would scrap the whole idea.. What are exactly the benefits of having rst checker (or checked documentation)? 
I mean - if I write or update a piece of documentation and commit it, I *always* go to the new docs page and check whether it's ok or not. 
As for docstrings, the worst are captured by pylint, and we could do something about the others (e.g. force the developers to document all function params, check whether they are complete, check whether there are not any nonexisting parameters documented, and so on)
As for documentation, I would not force any particular format and I would not go lint with it.

**Comment by jlibovicky** [comment]
OK, let's keep it like this for now. When I am in linting mood again, I can come with PEP257 or something like this.
