### ISSUE TITLE
training is not working since #152

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#171]
the model runs, but learns nothing

**Comment by jlibovicky** [comment]
Are you sure it was because of #152? My #151 refactor brought so many bugs, I would suspect it may have happened there as well.

**Comment by jindrahelcl** [comment]
It stopped working before the merge of your refactor. I have mentioned it somewhere.

**Comment by tomkocmi** [comment]
My training of a model today also didn't learned anything.
