### ISSUE TITLE
RNN Runner computes `train_logprobs` when there is no target data series

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#177]
Shouldn't it use runtime logprobs?

**Comment by jlibovicky** [comment]
To je protože tam celou dobu feeduju do těch train vstupů (aby se to netlouklo s greedy runem, když se to pustí najednou, ale nejspíš by to nevadilo), takže tam taky vylézají ty train_logprobs. Přišlo mi, že to nevadí, protože RNN runner se stejně nikdy nepustí zároveň s trainerem.

**Comment by jindrahelcl** [comment]
Já teď dělám refaktor dekodéru, kde train_inputs byl seznam tenzorů a stačilo nafeedovat první položku v tom seznamu  a už to fungovalo. Train_inputs jsem předělal na jeden tensor time x batch, a pokud neexistuje target series, tak by ho nikdo neměl ani feedovat a ani by se nemělo fetchovat train_cokoliv.

**Comment by jlibovicky** [comment]
Tak to zkus v tom run runneru přepsat všechno "train_" na "runtime_", myslím, že by to mohlo fungovat samo od sebe.

**Comment by jindrahelcl** [comment]
ok, vyzkoušim

**Comment by jindrahelcl** [comment]
omg fecthes místo fetches.. :-) tak jak jsi to napsal to asi nepujde, protoze on ten rnn runner pro ten beam search feeduje ty train inputs (řádka 250). Misto toho by mel asi feedovat nejaky runtime inputs, ale ty to nema, protoze si je to supluje tou loop function..

**Comment by jindrahelcl** [comment]
Co mi přijde nejčistší varianta je dát dekodéru ještě nějakej placeholder na slovo a předchozí stav a pomocí toho vyprodukovat další slovo (nebo logprobs) a používat to pro beam search

**Comment by jlibovicky** [comment]
To by šlo, ale musel by se teda úplně změnit TF Manager, aby bylo možný feedovat do každý TF session něco úplně jinýho (protože v každý session je ten předchozí stav jinej).

**Comment by jlibovicky** [comment]
Ale v tý loopfunction zase muse musí vznikat ty tenzory, co by se daly feedovat. Jestli se nepletu, tak tu loop function si stejně pouštíme sami decoding function, taby bysme je tam prostě mohli posbírat.

**Comment by jindrahelcl** [comment]
Loop function bys na tohle právě nepoužil, loop function je od toho, aby ti dala current input, ale ty ten budeš feedovat - takže jako kdybys měl gold data a cpal to tam v train módu, ale budeš je tam cpát jedno po druhým a ten loop function bude dělat ten pythoní kód okolo.

**Comment by martinpopel** [comment]
Znáte [dynamic_rnn_decoder](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/ops/seq2seq.py)? Možná to vůbec nesouvisí s tím co tu řešíte - pak se omlouvám.

**Comment by jindrahelcl** [comment]
Neznám, vypadá to použitelně, dík za tip.. :) Nicméně to, co tady řešíme, bude potřeba beztak vyřešit..

**Comment by jindrahelcl** [comment]
Změnil jsem rnn runner, aby používal runtime logprobs a testy prochází. Takže tohle zavírám a můžeš se na to kouknout v rámci review. Commit: 823c635a09661f79608d51c6d30d6132e98527d9
