### ISSUE TITLE
Create and maintain specification for the configuration

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#18]

**Comment by tomasmcz** [comment]
Also, put everything in one place. Eg. the parts of `dataset.py` that deal with `^s_` patterns for series should in my opinion be somewhere in the configuration module.

**Comment by jlibovicky** [comment]
First of all, we should separate loading and generating configuration. Loading is very straightforward and fine with higher order functions etc. It just takes python functions and __init__ methods and feed whatever is specified in the file as arguments. It is kind Python for poors. It would only mess things up if you add there a condition: and if the type whose __init__ method you are calling is Dataset, do something entirely different than with all the other functions/classes.

**Comment by tomasmcz** [comment]
For me, that would be yet another reason to rethink the whole thing. Specification (and preferably also implementation) of the ini format should be in one place.

**Comment by jindrahelcl** [comment]
Let's move this here: https://docs.google.com/document/d/1UHCWf3WYaMdprAfTeRG2EhOlFyLRkjy6LnqhCONL19A/edit?usp=sharing

I have sent you an edit invite, feel free to write something.

**Comment by jlibovicky** [comment]
Done in #236.
