### ISSUE TITLE
Create comparison model with Nematus

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#185]
The most frequent question on IWSLT for the Neural Moneky was if we have some numbers of how big model can we fit into the GPU with comparison to Nematus.

**Comment by jindrahelcl** [comment]
I'm working on it as a part of my stay in Edinburgh.

**Comment by jindrahelcl** [comment]
As for the numbers, I think we can fit the Nematus model on the 12 GB GPU we have back in Prague. I doubt it can fit on a smaller GPU. But there has been an observation that lowering the RNN size radically (e.g. from 1000 to 500 or 300) only leads to BLEU loss of about 1-2 points.

**Comment by tomkocmi** [comment]
And how much memory does the Nematus need for its model?

**Comment by jindrahelcl** [comment]
Definitely less. But I'm afraid there's not much we can do about it.
