### ISSUE TITLE
Combine runner and training decoder together

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#188]
Current approach takes too much memory as it have to create two same graphs.

**Comment by jindrahelcl** [comment]
Dovolim si tuhle issue vést v češtině:
1. Tou pamětí si nejsem jistej, protože ty grafy sdílej proměnný, který tam jsou uložený jen jednou, a pokaždý, když se pustí session.run, tak se spustí právě jeden graf, takže tam by paměťový nároky navíc vznikat neměly (protože ten runtime graf se nepoužije). Graf jako takovej bez proměnných a bez naplněných placeholderů by téměř žádný místo zabírat neměl, protože je symbolickej.
Například tenhle kód rozhodně nezabere (10^38 x 64) + (12 x 32) bitů, ale jen 12 x 32 bitů, protože `big_matrix` se nepoužívá.
```
big_matrix = tf.placeholder(tf.int64, [100000000000, 100000000000])
small_matrix = tf.ones([3,4], tf.int32)
s = tf.Session()
s.run(small_matrix)
```

2. Train a runtime grafy **nejsou** stejný (aspoň tak, jak to funguje teď). Podobný, to jo. Aby se tohohle docílilo, musel by se použít jen runtime graf a trainer by mu musel pod rukama měnit jeho výsledky - to by ale znamenalo, že session.run nestačí volat jednou, ale `max_output_len`krát, což by možná celkově to trénování naopak zpomalilo

Závěr je takovej, že si myslim, že to paměť neušetří, ale asi stojí za to to vyzkoušet a změřit to (paměť i čas).

**Comment by tomkocmi** [comment]
Ja presne nevim, kde je problem. Kazdopadne kdyz mam model kterej s runner_batch zabira 6GB na grafice a kdyz dam runner_batch 20 tak se nevejde do 8GB, tak si myslim ze je neco spatne, zvlast kdyz runner k trenovani neni potreba (dobre je potreba k validaci, jestli to chapu, ale ta se dela jen jednou za cas). Nemusi se tedy nijak spojovat, jen by se melo vyresit to, ze veci nepotrebne k trenovani zabiraj zbytecne pamet (a to docela dost). Cely tenhle issue je pouze o tomhle problemu, ktery osobne nevim kde presne vznika.

**Comment by jlibovicky** [comment]
Mít pro train a runtime jenom jeden graf je frajeřinka a asi netřeba tvdrit, že je to potřeba do WMT17 Training Tasku mít hotové. Když bychom volali `session.run` `max_output_len` krát, tak bysme si jenom ublížili (stačí se podívat, jak pomalý je teď RNN Runner). Řešení by podlě mě bylo posbírat ty tenzory, co vznikají v `loop_function` a feedovat do nich rovnou ty trénovací indexy. Myslím, že by se tím něco málo paměti ušetřit mohlo, ale moc to nebude.

**Comment by jindrahelcl** [comment]
Runner je taky potřeba k logování (každých 20 batchí, vyplivne to jednu řádku s kecama). 
Nicméně, ve chvíli, kdy se používá runner, tak trénování vůbec neni načtený do paměti - jedno načtení do paměti GPU, výpočet a následný odpovídající uvolnění paměti by mělo odpovídat jednomu volání `session.run`.

**Comment by tomkocmi** [comment]
dneska jsme vyresili problem s padajicima modelama, ktery jsem myslel, ze za nej muzou oddelene grafy, vyresil commitem 82b8085bf5ea75e968ae65e1c8f73a1cb968209d ... kazdopadne pokud by spojeni grafu trochu snizilo narocnost na pamet, tak by to bylo fajn nad tim zauvazovat

**Comment by jindrahelcl** [comment]
Leželo mi to v hlavě a fakt si myslim, že se tim lautr nic neušetří. Kód grafu jako takovej má na zabranou paměť minimální vliv (nenese v sobě žádný data); paměť se spotřebovává voláním session.run, která ale obsazuje jen tu část grafu, kterou potřebuje k výpočtu.

Je to analogický k tomu, kdybys měl desetitisíciřádkovej kód, jehož `main()` by volalo funkci na řádcích 250-275, která už žádný jiný funkce nevolá a chtěl bys v tom kódu nechat jen ten relevantní kus.
Sice by neměl deset tisíc řádek ale jen 30, ale paměti to bude žrát furt stejně.

**Comment by jindrahelcl** [comment]
Btw., @tomkocmi, neprošly ti testy. :-P

**Comment by jindrahelcl** [comment]
ups, close byl překlik

**Comment by tomkocmi** [comment]
Ty testy neprochazej uz delsi dobu a fakt nevim cim to je (snazil jsem se to vykoumat na tom vystupu ale tam to odkazuje na kusy kodu co jsem neupravoval). Tak to neresim :D

**Comment by jlibovicky** [comment]
Nedělal bych to, protože jinak nebude možné implementovat Self-Critical training (#215).
