### ISSUE TITLE
Automatically check PEP8 and PEP257

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#190]
Are we ready to automatically check following PEP8 guidelines using [pycodestyle](https://pypi.python.org/pypi/pycodestyle) on top of pylint. I tried to run it today and most of the errors are in number of black lines. This can be easily fixed and added into our tests suite.

And what about using [pycodestyle](https://pypi.python.org/pypi/pycodestyle) to check compliance with PEP257? Wouldn't it be to restrictive?

And what about becoming the ultimate code checking nazis using [xenon](https://pypi.python.org/pypi/xenon/) to check code complexity? Would we ever be able to submit a line of code? Would we achieve a coding nirvana and eternal programming peace?

**Comment by jindrahelcl** [comment]
pycodestyle already among tests, we can enable code complexity testing later
