### ISSUE TITLE
GPU profiling

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#199]
This could be really interesting to put into NeMo https://github.com/tensorflow/tensorflow/issues/1824

**Comment by obo** [comment]
One of the interesting comments in the thread there suggest to browse the collected stats in chrome:

https://github.com/tensorflow/tensorflow/issues/1824#issuecomment-225754659

**Comment by obo** [comment]
And another relevant link is for using nvidia's visual profiler for programs calling CUDA from python:

http://austindw.com/blog/programming/profiling-cuda-through-python-with-nvvp

**Comment by obo** [comment]
A remark that a bad protobuf version can make the profiling too expensive:

https://github.com/tensorflow/tensorflow/issues/5981

**Comment by jindrahelcl** [comment]
I don't think this is a task for anyone to "start" with..

**Comment by obo** [comment]
If he or she has done profiling of TF but is new to NM, it is actually a good task to start with. But I agree there are probably very few people like that.

----- Original Message -----
> From: "Jindra Helcl" <notifications@github.com>
> To: "ufal/neuralmonkey" <neuralmonkey@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Comment" <comment@noreply.github.com>
> Sent: Friday, 23 December, 2016 12:42:55
> Subject: Re: [ufal/neuralmonkey] GPU profiling (#199)

> I don't think this is a task for anyone to "start" with..
> 
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ufal/neuralmonkey/issues/199#issuecomment-268978381

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo
