### ISSUE TITLE
Separate configuration reading from execution

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#206]
and check #123

**Comment by tomasmcz** [comment]
@jlibovicky Rozumím tomu správně, že když přidám nový kus konfigurace, který chci používat jenom při trénování, tak musím v `run.py` ručně nastavit, aby se při běhu nebuildoval?

**Comment by jlibovicky** [comment]
Je to tak, ale moc se mi to nelíbí. Tak to můžeš zkusit vymyslet lépe.

**Comment by tomasmcz** [comment]
TODO: doplnit uvozovky do dokumentace
