### ISSUE TITLE
NM branding on readthedocs

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#209]
Could we somehow add the ape picture to readthedocs?
And could we make the name Neural Monkey more visible than it is now in the blue home region?

Reason: the chapter on tutorial will change to "Post-Editing Tutorial" once @tomkocmi adds "Translation Tutorial". And the name Neural Monkey then vanishes from the menu (except the blue title box):
http://neural-monkey.readthedocs.io/en/latest/tutorial.html

Or should we change Intro to "Introduction to Neural Monkey"?

**Comment by jindrahelcl** [comment]
podle mě translation tutorial je zbytečnej, protože nepřinese nic novýho. Radši bych dělal popisy různých featur, který se do translation daj přidat.. INI soubor pro translation je v examples a je okomentovanej a člověk, kterej četl ten hlavní tutoriál, tak nemá problém to pochopit.

**Comment by obo** [comment]
Translation tutorial vubec neni zbytecnej, i kdyby jen rekl: prectete si PE tutorial a podivejte se na tohle ukazkove ini.

Jednou je to translation task, takze je potreba na to mit strucny uvod bez klicek.

Samozrejme souhlasim, ze tutorial/ten google doc by pak mel uvest, co a jak pridat.

O.

----- Original Message -----
> From: "Jindra Helcl" <notifications@github.com>
> To: "ufal/neuralmonkey" <neuralmonkey@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Tuesday, 20 December, 2016 14:18:45
> Subject: Re: [ufal/neuralmonkey] NM branding on readthedocs (#209)

> podle mě translation tutorial je zbytečnej, protože nepřinese nic novýho. Radši
> bych dělal popisy různých featur, který se do translation daj přidat.. INI
> soubor pro translation je v examples a je okomentovanej a člověk, kterej četl
> ten hlavní tutoriál, tak nemá problém to pochopit.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ufal/neuralmonkey/issues/209#issuecomment-268240829

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by jindrahelcl** [comment]
Tak to bych napsal rovnou do getting started - tady máte tutoriál jak to používat a  v `examples/translation.ini` je ukázkovej konfigurák pro překlad.

Odděloval bych task a dokumentaci toho package. Pro ten package neni novej tutoriál potřeba, pro task třeba jo, ale dal bych to jinam, tak jak jsme dohodli včera ráno.

Přestylovávat readthedocs (nápis vpravo nahoře) nebudem, všichni to používaj takhle, viz:
https://blocks.readthedocs.io/en/latest/ nebo
http://docs.readthedocs.io/en/latest/index.html

Opici tam přidat můžem.

**Comment by tomkocmi** [comment]
Trochu se tu rozvinulo nekolik tema :D takze po bodech:
1) ohledne te dokumentace, tak ty readthedocs jsou opravdu priserne na zorientovani, ale to je jedno. A to ze to vsichni tak pouzivaj neznamena, ze je to dobre.
2) Tvrdit, ze "kdo si precte tutorial chape vsechny scripty" je pritazene za vlasy, radeji bych delal vse detaile nez predpokladat ze kazdy je genius a vse okamzite pochopi na prvni precteni. Protoze opice nema state-of-the-art vysledky, tak ji musime udelat poradne zdokumentovanou a nejaky prochazeni examplu nekde v testech si nemyslim, ze je funkcni zdokumentovani.
3) Ten MT tutorial zacnu delat za 20 minut a budu ho delat do dokumentace, jak jsme se vcera domluvili. Chci tam na nem ukazat i jine veci nez ktere jsou v posteditingu jako nacitani z gzipu nebo BPE.

**Comment by obo** [comment]
Jen hlasim, ze souhlasim s Tomem.

A prosim bych obrazek opice. :-)

(Readthedocs ma mozna jednu vyhodu a to je ten slavnej responsive layout. Ted jsem to videl v uzkem okne a menu vlevo tam nebylo vubec. Osobne to nesnasim, protoze to pak neumim najit, ale chapu, ze vetsina lidi to naopak vyhledava. :-)

----- Original Message -----
> From: "tomkocmi" <notifications@github.com>
> To: "ufal/neuralmonkey" <neuralmonkey@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Tuesday, 20 December, 2016 15:00:29
> Subject: Re: [ufal/neuralmonkey] NM branding on readthedocs (#209)

> Trochu se tu rozvinulo nekolik tema :D takze po bodech:
> 1) ohledne te dokumentace, tak ty readthedocs jsou opravdu priserne na
> zorientovani, ale to je jedno. A to ze to vsichni tak pouzivaj neznamena, ze je
> to dobre.
> 2) Tvrdit, ze "kdo si precte tutorial chape vsechny scripty" je pritazene za
> vlasy, radeji bych delal vse detaile nez predpokladat ze kazdy je genius a vse
> okamzite pochopi na prvni precteni. Protoze opice nema state-of-the-art
> vysledky, tak ji musime udelat poradne zdokumentovanou a nejaky prochazeni
> examplu nekde v testech si nemyslim, ze je funkcni zdokumentovani.
> 3) Ten MT tutorial zacnu delat za 20 minut a budu ho delat do dokumentace, jak
> jsme se vcera domluvili. Chci tam na nem ukazat i jine veci nez ktere jsou v
> posteditingu jako nacitani z gzipu nebo BPE.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ufal/neuralmonkey/issues/209#issuecomment-268249821

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by jindrahelcl** [comment]
1. komentoval jsem stylování toho nápisu, ne readthedocs jako celek
2 a 3. dokumentace ano, řikat jednu věc na několika místech stejně ne. Minimálně proto, že je to situace, ze který to zaručeně dojde do chvíle, kdy někdo něco změní a změní dokumentaci jen na jednom místě a pak z toho bude dokumentace, která si protiřečí. Čili popsat věci, ve kterých se to liší od post-editing tutoriálu, ne to psát celý odznova. Btw. tvrdit "kdo si precte tutorial chape vsechny scripty" přitažený za vlasy skutečně je, a proto to jsem to nikde netvrdil.

**Comment by tomkocmi** [comment]
Super, takhle souhlasim. Jinak ten tutorial neplanuju delat tak detailne, to souhlasim ze je zbytecne. Chci to delat jako nadstavbu na postediting a rozsirit tam veci, ktere postediting nepouziva jako gzip, BPE atp ::)

**Comment by obo** [comment]
Opice je pridana do index.html.
Overil jsem, ze lokalne zkompilovana dokumentace ma skutecne nad menu vlevo take opici, cili ze se logo neukazuje na readthedocs, je vlastne jen cizi bug.
Cili zaviram.
