### ISSUE TITLE
Wrong symlink in best variables

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#21]
Commit add9bdc99ab6acbf0ebece9c5c792c3fb3f495f4 (fix saving variables) introduced a bug. It creates a symlink with wrong relative address. For example, when I set my output to directory `test-out`, it creates a link to `test-out/data.whatever` in that folder. So the script is looking for `test-out/test-out/data.whatever` instead of `test-out/data.whatever`.

My preferred solution would be to put the commit into a separate branch (rewinding current master by one commit) and merge #13. That will enable running `tests/small.ini` on Travis. The new branch can be merged when the bug is fixed. What do you think, @jindrahelcl?

**Comment by jindrahelcl** [comment]
I have run it on this commit and the link is fine. Can you paste the ini file?

**Comment by tomasmcz** [comment]
It' the ini file in #13. You can replicate this by rebasing #13 (or the `package_hierarchy` branch from this repo) on add9bdc and running `tests_run.sh`.

**Comment by jindrahelcl** [comment]
fixed
