### ISSUE TITLE
Image processing into requirements?

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#214]
Neural Monkey should be able to work also with multimodal data. However, loading and basic processing of images requires additional dependencies. It can be done either with [scipy](https://www.scipy.org) - which is a rather big dependency, or [pillow](https://python-pillow.org/), which is a relatively small package.

My questions is:
* Do we plan to use scipy for anything else except basic image processing?
* If not, is it OK, to add pillow in the requirement and process images with it?
* If not, what is the proper way to separate the image processing code from the rest of the code?

**Comment by jindrahelcl** [comment]
Is there a reason we do not use Tensorflow's features for this?

https://www.tensorflow.org/api_docs/python/image/

**Comment by jlibovicky** [comment]
Cool, I didn't know it's there. I'll rewrite the image processors PR using this.
