### ISSUE TITLE
Self-critical Sequence Training

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#215]
Self-critical Sequence Training is a simple method of using REINFORCE algorithm for sequence-to-sequence learning. Unlike [Minimum Risk Training](https://arxiv.org/abs/1512.02433) it does not require sampling of beam of hypotheses for the expected reward estimation, and unlike the [MIXER algorithm](http://arxiv.org/abs/1511.06732). it does use additional network for baseline estimation.

Paper on arXiv: https://arxiv.org/pdf/1612.00563v1.pdf

**Comment by loveJasmine** [comment]
keep me posted

**Comment by jlibovicky** [comment]
Done in #435.

**Comment by loveJasmine** [comment]
@jlibovicky 
Vocabulary file does not exist: tests/outputs/vocab/encoder_vocab.pkl
while  I am running:
bin/neuralmonkey-train tests/self-critical.ini

**Comment by jlibovicky** [comment]
The tests depend on each other. The vocabulary is created by running `bin/neuralmonkey-train tests/vocab.ini`.

The test case just tests whether it is possible to build the computational graph, not the learning capabilities of the model, its output don't have any revelance.

**Comment by loveJasmine** [comment]
@jlibovicky 

do you plan have MIXER model implemented on this project?

**Comment by jlibovicky** [comment]
Not anytime soon. Feel free to contribute :-)

**Comment by loveJasmine** [comment]
how to enable/disable this feature in the ini config file?

**Comment by jlibovicky** [comment]
You can follow the minimum example in [self-critical.ini](https://github.com/ufal/neuralmonkey/blob/master/tests/self-critical.ini).

**Comment by jindrahelcl** [comment]
(lines 71-75 and 84)
