### ISSUE TITLE
Run all tests even if one fails

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#218]
Now, unit and regression tests (the ones that include the training of "tests/small.ini") do not run all tests if one of them fails. That is due to the `set -e` in the scripts.

This is particularly bad in unit tests, which are not dependent on each other.

I propose to use `pytest`, which is compatible with `unittest` and provides a better interface for running tests (it scans the whole package for test functions and run them, it supports test fixtures (which would be nice to have for testing complicated tensorflow objects)).

I tried to run `pytest`, bud it is not straightforward with our tests, since one of them is somehow incompatible with pytest behavior.

As for the regression tests, I'd invest some time to create a hierarchical structure of running the scenarios one by one so each test that can be run (given the result from its prerequisites) is run.

**Comment by jlibovicky** [comment]
Go ahead, do it!

**Comment by jlibovicky** [comment]
What about this? Is this done?

**Comment by jindrahelcl** [comment]
No, but I wouldn't bother with this. If a test fails on an error that would cause all the tests to fail, it would consume too much time on travis.

**Comment by jlibovicky** [comment]
I thought this was about unit tests, not integration tests.

**Comment by jindrahelcl** [comment]
It was about both - perhaps we should do this just for the unit tests?

2017-09-21 16:11 GMT+02:00 Jindřich Libovický <notifications@github.com>:

**Comment by jlibovicky** [comment]
I thought it is already done for unit tests.

**Comment by jindrahelcl** [comment]
I don't think so. Look at the unit-tests_run.sh file

2017-09-22 10:35 GMT+02:00 Jindřich Libovický <notifications@github.com>:
