### ISSUE TITLE
Diff and commit messages fail to write out

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#221]
If the experiment output directory does not exist, NM creates it, but only after trying to store git info there:

...
sh: 1: cannot create experiments/mmmt-delta/git_commit: Directory nonexistent
sh: 1: cannot create experiments/mmmt-delta/git_diff: Directory nonexistent
2016-12-29 23:22:57: Initializing TensorBoard summary writer.

**Comment by jindrahelcl** [comment]
tohle už je někde fixlý..

**Comment by jindrahelcl** [comment]
V df0db10611f0c1c9f4d80480f38fb4ebf46792f7 je to opravený - jakou máš verzi? Tohle je už dávno v masteru

**Comment by jindrahelcl** [comment]
Btw. adresář se vždycky dělá dřív

**Comment by obo** [comment]
Master mi to porad dela. Jeste dnes, commit bec408a546accf2bf705cc6dcccc1334cee915c3.

sh: 1: cannot create output/git_commit: Directory nonexistent
sh: 1: cannot create output/git_diff: Directory nonexistent
2017-01-19 12:33:47: Initializing TensorBoard summary writer.

**Comment by jindrahelcl** [comment]
odkud to pouštíš relativně k root directory toho package?

**Comment by jindrahelcl** [comment]
a jak máš nastavenou main.output konfiguraci?

**Comment by obo** [comment]
Nespoustim to z toho package. To nemuzeme predpokladat.
Cili to bude duvod.
Spoustim to prikazem ./muj-odkaz/neuralmonkey/bin/neuralmonkey-train, kde muj-odkaz je symlink na ten repozitar.

NM by si tedy mela napred udelat nejaky readlink -f na cestu k sobe a tam udelat v subshellu cd a teprve pak volat git.

**Comment by jindrahelcl** [comment]
Podívej se do kódu, přesně to se tam děje.

**Comment by jindrahelcl** [comment]
Nepředpokládáme místo, odkud se to volá.

**Comment by jindrahelcl** [comment]
Napiš ještě,  co máš v konfigu v ``output`` v  ``[main]``, prosim
