### ISSUE TITLE
remove examples, add tutorial configs to tests

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#223]
example configs are not tested and do not work; remove them from master altogether

on the other hand, tutorial configs need to be tested, please add a minimized version of each of them to tests

**Comment by jindrahelcl** [comment]
I disagree. Examples are not tests and are there for the user to see how the things can be done. 

Examples should be working configurations that learn a somewhat good model, test configurations should be minimal and fast, and should cover everything. Examples are part of the documentation, whereas tests are designed for testing..
