### ISSUE TITLE
Make tests for example configurations

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#224]
issue #223 will remove the directory examples from master altogether

get the examples (e.g. as of 6635290) back to master but **as tests**, so that we are sure they are valid

**Comment by jindrahelcl** [comment]
As I said in #223, examples are not tests and should be separated.

**Comment by obo** [comment]
All examples need to be regularly tested or removed. Bad example is worse than no example.

If they are tested, they can surely live in the examples directory. I understand the distinction you want to make.


3. ledna 2017 18:49:20 SEČ, Jindra Helcl <notifications@github.com> napsal:
>As I said in #223, examples are not tests and should be separated.  


-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by jindrahelcl** [comment]
Jak tak tady teď sedim a přemejšlim, tak mi vlastně přijde, že bad example rozhodně neni worse než no example, protože to aspoň ty lidi donutí chvíli přemejšlet, proč to nefunguje.

Nicméně - až se mergne #357, bylo by hezký, kdyby ty examply testoval ten démon - @jlibovicky ?

Nejhezčí by bylo, kdyby to celý jelo automaticky - git clone neuralmonkey, instalace requirements, kouknout se do examples, pro každej `něco.ini` vlýzt do složky `data/něco`, postahovat data, pustit to něco a výsledek zapsat někam do tabulky.

**Comment by jlibovicky** [comment]
Možná bych na to udělal druhýho démona. Aby zůstal ten první, co to zvládá otestovat jednou za dva dny, protože ten, co pojede všechny examply, tak bude trvat určitě dýl než dva dny.

**Comment by jindrahelcl** [comment]
Klidně, čim víc démonů, tim pekelnějc otestovaný to bude

**Comment by jindrahelcl** [comment]
Replaced by #678
