### ISSUE TITLE
Make tests/small.ini the current best known config for training

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#226]
I'd like tests/small.ini to represent the best known config for training in all aspects:

- the score it reaches when run sufficiently long on a good dataset
- speed of training
- memory consumption

Current tests/small.ini is:

- [ ] terribly slow (c63a702 was 4x faster than 524be81; I have no idea if the fix introduced in 524be81 indeed does require the increased costs)
- [ ] has runner_1 (runners.rnn_runner.RuntimeRnnRunner) which @jlibovicky said could be removed, but it lead to an error when I tried it
- [ ] val_data_no_target is also probably not needed for baseline training

If you like, you may rename it to soa-baseline-train.ini or something like that.

All the remaining aspects should be still tested, but in separate tests, e.g. dynamic-rnn.ini

Related to #225

**Comment by tomkocmi** [comment]
As I have helped you this mornig. The first problem is connected with the use of beam search during the logging. Therefore the model is slow only due to the slow implementation of beam search.
