### ISSUE TITLE
Check the configuration described in PE and MT tutorials

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#231]
Once decoder_refactor is merged into master, we need to check if the configuration described in tutorials (both PE and MT) works as expected.

Consider automatically extracting documentation from the tutorial, so that tutorials can be included in automatic tests.

**Comment by jindrahelcl** [comment]
Aha tak to je naše (@jindrahelcl a @jlibovicky) chyba, že jsme si specifikace k řešení téhle issue nevšimli.. Jak už jsem psal v tom pull requestu, mnohem praktičtější bude, když se to udělá naopak - tutoriály budou includovat snippety z examplů (např. pomocí direktivy `literalinclude` ze Sphinx, dokumentaci lze najít zde: http://www.sphinx-doc.org/en/1.5.1/markup/code.html)

Jak nám poradil @hajicj, examples by měly být vždycky vázány na jednu konkrétní verzi (release), takže ani nevznikne problém s tím, že by se měnila čísla odkazovaných řádek.

**Comment by obo** [comment]
No, jsem celkem dost proti, aby kdokoli musel psát kamkoli čísla řádek. I pro jednu jedinou verzi.

Nerozumím tomu, jak se můžou čísla řádek neměnit, když někde nahoře v konfiguraci se něco prodlouží.

16. ledna 2017 20:30:43 SEČ, Jindra Helcl <notifications@github.com> napsal:
>Aha tak to je naše (@jindrahelcl a @jlibovicky) chyba, že jsme si
>specifikace k řešení téhle issue nevšimli.. Jak už jsem psal v tom pull
>requestu, mnohem praktičtější bude, když se to udělá naopak - tutoriály
>budou includovat snippety z examplů (např. pomocí direktivy
>`literalinclude` ze Sphinx, dokumentaci lze najít zde:
>http://www.sphinx-doc.org/en/1.5.1/markup/code.html)
>
>Jak nám poradil @hajicj, examples by měly být vždycky vázány na jednu
>konkrétní verzi (release), takže ani nevznikne problém s tím, že by se
>měnila čísla odkazovaných řádek.  


-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by jindrahelcl** [comment]
Vtip je v tom, že v konfiguraci se nic neprodlouží, protože examples by měly být zamrzlý vždy ke konkrétnímu releasu. K těm tak často nedochází, takže si můžem dovolit ty tutoriály zkontrolovat.

Samozřejmě se to dá udělat fikanějš a vyzobnout to do tutoriálu třeba sedem, ale kontrolovat se to stejně bude muset.

Největší důraz je třeba klást na to, že examply jsou luxus, kterej nejde udržovat průběžně, aniž by se z toho lidi zbláznili.

**Comment by jindrahelcl** [comment]
Asi jsem nepochopil tvojí poznámku.

Čísla řádek, která budou ve zdrojáku dokumentace používaný jako odkaz, kterej se vyrendruje např:
```
.. literalinclude:: example.ini
   :lines: 10-15
```
udělá, že tam bude vidět třeba
```
[main]
train_dataset=<něco>
val_dataset=<něco_jinýho>
ještě_něco=ahoj
řádek_15=nazdar
```

Dokumentace se měnit může. Pokud example zůstane stejnej (a to zůstane), tak s tim problém žádnej neni.

Samozřejmě, že si každej ten example může měnit, ale neovlivní tim, jak se renderuje dokumentace

**Comment by jindrahelcl** [comment]
Čísla řádek jsou v tomhle případě mnohem lepší alternativa, než mít dvě kopie jednoho examplu, z toho jednu zašifrovanou do dokumentace a druhou nezávisle někde jinde.

**Comment by obo** [comment]
Aha, tak to jen hlasim, ze sis nevsiml, ze tento cely ukol je uz ve vetvi tutcheck vyresen. :-) Tam uz je prave to vyzobavani hotove a konfigurak PE uz je takto automaticky syntakticky zkontrolovan. Tom dneska delal na tom, aby test dale pokracoval a nezdechl na nedostupna data.

**Comment by jindrahelcl** [comment]
Všimnul, a to, jak je to špatně, mě dovedlo sem k té issue. Taky to píšu hned v úvodu.

**Comment by obo** [comment]
Jako že sedem by to šlo, ale perl je špatně. :-) V tom případě jsem ochoten přepsat ten extraktor do Pythonu.

Ne, vážně. Vůbec nechápu, co je na větvi tutcheck špatně. Shodujeme se, že žádný kus konfigurace nemá být dvakrát na různých místech. Tutoriál je velmi užitečný a netestované příklady jsou chyba. Pak jde jedině o to, jestli budou příklady v textu tutoriálu a z něj se pro test vykousnou, nebo jestli budou ležet mimo a nějak se do něj zabudují. Možnost a) je hotova a nenutí počítat řádky. Ano, závisí na ad hoc skriptu. Možnost b) hotova není a vidím jedinou odlišnost, a sice, že použije existující konstrukt ze sphinxu, za cenu podstatně pitomější údržby. (Jakákoli změna příkladu nutí přečíslovávat, ne že ne.)

Asi to probereme zítra, ale budu tam jen do 11.50.


16. ledna 2017 21:51:46 SEČ, Jindra Helcl <notifications@github.com> napsal:
>Všimnul, a to, jak je to špatně, mě dovedlo sem k té issue. Taky to
>píšu hned v úvodu.


-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by jindrahelcl** [comment]
Pro mě je možnost b jediná přijatelná alternativa. Z následujících důvodů (seřazených podle pádnosti):

1. Example, který se při testování automaticky konstruuje z dokumentace se nedá rovnou spustit, aniž bys musel copy-pastovat a při tom nadělal spoustu chyb (např. když něco přehlédneš nezkopíruješ všechno), nebo aniž bys musel napřed pouštěl perl skript, kterej to z dokumentace vytáhne.
(1a. A budou copy-pastovat, protože Perl není mezi požadovanýma závislostma, takže nemůžeme jen tak napsat do dokumentace, ať si to Perlem vygenerujou.)
2. Nelze napsat takto testovaný dokument, který nepopisuje celý konfigurák explicitně.
3. To, že není hotová, jednak není pravda (ta direktiva v tom Sphinxu už je), a jednak i kdyby hotová nebyla, tak to neznamená, že se nedá udělat (kór když udělat komplikovanější řešení trvalo jen den).
4. Jako pitomější údržba to možná připadá tobě, ale já radši po editaci examplu zkontroluju, jestli jsem nešoupal z řádkama (a klidně v tom examplu může být disclaimer, který ti to poradí), než abych udržoval dvě identické verze jednoho examplu jen kvůli tomu, abych mohl ten example pouštět
5. Jak už jsem zmínil v (1a), dohodli jsme se, že se vyvarujeme používání Perlu, který není a nebude mezi závislostma. Takže takhle napsaná feature sice může existovat a můžeme jí interně používat, ale mimo repozitář.

**Comment by obo** [comment]
1: To ale platí i pro stávající tutoriály, že je musíš poskládat. Čili tady jsou a) i b) ekvivalentní.
1a: Není problém při automatickém testu konfigurace také na známé místo vložit kopii (začínající hláškou "automatically generated from tutorial, do not edit", takže v tutoriálu můžeme napsat, že full config is assembled there and there.
2: není problém, extrakční skript je plně v naší režii, může si brát komponenty, odkud chce, klidně něco navíc z "neviditelné části tutoriálu". Ale spíš si myslím, že dobrý tutoriál opravdu zmíní vše.
3: jako že nikdo ty čísla řádek nedohledával, nezkusil udělat řešení b
4: pořád si nějak nerozumíme, já jsem taky zásadně proti dvěma kopiím examplu. Řešení b) je riskantnější, protože když v tom opisování čísel řádků uděláš chybu, tak už to uvidí jedině okem čtenář tutoriálu. Chyba v řešení a) vede k nespustitelnému příkladu, což se odhalí samo.
5: OK, to je politika, klidně. (mimochodem, sphinx taky není v requirements.txt, ale myslím, že vývojové nástroje tam nepatří)

**Comment by tomasmcz** [comment]
Ještě bych dodal, že řešení *b* je lepší v tom, že ten tutoriálový example by byl přímo v repozitáři, takže by bylo možné si ho třeba z Githubu otevřít ve vedlejším okně a pohodlně se koukat, jak jednotlivé snippety z tutoriálu zapadají do celku. Nebo ho rovnou vzít a začít s ním experimentovat, aniž bych musel někde zjišťovat jak ho mám vygenerovat.

**Comment by obo** [comment]
Ano, to je pěkná vlastnost a ve variantě a) ji o poznámku výše (1a) navrhuju udělat tak, že ten autotest ten extrahovaný konfig dá na dohodnuté místo (a případně hned zavolá git commit). Takže o jeden commit později nebo spíš ještě při commitu úpravy tutoriálu už to zas bude obojí konzistentní a správně.

Ale klidně si přečíslovávejte řádky, když se to i @tuetschek -ovi zdá lepší nápad...

**Comment by tuetschek** [comment]
Já bych rozhodně neměl být někdo, kdo o tom rozhoduje :-D. A Jindra mi přímou indexaci řádkama zamlčel, takže teď se mi nelíbí ani jedno řešení :-D.

**Comment by jindrahelcl** [comment]
1. Neporovnával jsem možnost (a) a stávající tutoriály, ale možnost (a) a (b) v jejich odpovídajících finálních podobách.
1a. tomu moc nerozumim, ale moje 1a nebyl zas tak důležitej důvod
2. Tak to by byl ještě větší prasečák než kdyby to mohlo brát jen z textu tutoriálu :-) Schválně jsem nepsal "tutoriál", ale obecněji "testovaný dokument". Když máš dokumentaci jedné featury a máš u toho snippet s kódem, který se bere z nějakého examplu, budeš moci testovat i tenhle example.  
4. Ne nutně. A při frekvenci updatu examplů jednou za pár měsíců neni zas tak drahá operace se po změně podívat do tutoriálů, jestli to lícuje
5. requirements.txt jsou požadovaný pythoní balíčky, ne závislosti.

Nejčistší řešení by bylo dodělat si Sphinx direktivu includeini a tý dát jako argumenty soubor a název sekce. Zkusim se podívat, jak komplikovaný by to bylo, ale myslim si, že ne moc.

**Comment by jindrahelcl** [comment]
Teď jsem si všimnul, že ``literalinclude`` direktiva má parametry ``start_after``  a ``end_before``, takže stačí napsat něco jako:

```
.. literalinclude:: ../../examples/translation.ini
    :start-after: [train_data]
    :end-before: [název_následující_sekce]
```

A jediný, co si hlídat, aby se nový sekce buď přidávaly na začátek examplu, nebo aby se to prostě vždy kontrolovalo.

**Comment by obo** [comment]
Tom dotlačil pull-request #250 do stavu, kdy to projde všemi testy a dělá, co má.
Chtěl bych tedy poprosit, abyste to teď třeba se skřípáním zubů odklepli a mergli. Tutoriály potřebujeme kvůli Training Tasku testované a tohle je hotové.

Je v tom taky kus našeho času a neradi bychom, aby se zahodil, než bude náhrada. Nechat to viset nemergnuté se skoro rovná zahození, protože každé rebasování je zbytečná práce navíc.

Výhledově se mi nejvíc líbí ta varianta s vylepšením Sphinxu, aby se dalo říct, kterou sekci .ini má ukázat. Až se Jindrovi podaří dotlačit do veřejně dostupného Sphinxu tohle rozšíření, můžeme na ten čistší způsob přejít. Do té doby ale tutcheck ohlídá např. změnu názvu tf_managera a další chystané novinky.

**Comment by jindrahelcl** [comment]
Píšeš to všechno hrozně manipulativně - do veřejného sphinxu neni třeba tlačit nic, rozšíření je jeden soubor a může si ho každej napsat sám. 

Navíc, ``start-at``  a ``end-before`` na to, co potřebujeme, stačí.

Kvůli training tasku neni potřeba žádná automatizace, ale bohatě stačí, když se ty konfiguráky vygenerujou jednou, ve chvíli, kdy jsou tutoriály hotový, a pak otestujou někde vedle.  Na training task bude danej jeden konkrétní komit, tak nechápu, proč se teď musí řešit continuous integration, když to neni potřeba.

**Comment by tomasmcz** [comment]
Mimochodem, to co je v tom PR taky není spolehlivé: když zapomenu před nový blok s konfigurací napsat `.. codeblock: ini`, tak budou testy dál procházet, ale nebudou testovat to, co se v tutoriálu zobrazuje.

**Comment by tomkocmi** [comment]
Mala vsuvka k zamysleni: Prijde nekdo novy, naprogramuje nejakou vec, ktera splnuje vsechny nalezitosti, nic neposkozuje a funguje. Udela pull request. Vy mu ho zavrhnete, protoze byste teoreticky dokazali naprogramovat "lepsi" variantu.

Jak se asi bude po tom vsem citit?
Bude mit dotycny dobry pocit z odvedene prace?
Bude chtit jeste nekdy prispivat do NM?
Zlepsi se tim povest NM a prilaka to nove lidi?

**Comment by martinpopel** [comment]
V některých projektech není doporučeno začít pracovat na PR, dokud nejsem u příslušné issue uveden jako jako Assignee.
Správci projektu si pak při přidělování člověka k issue ověří, že v hrubých obrysech souhlasí s tím, jak se to má řešit.
V některých projektech mohou mít issues třeba tag "help-wanted".
Někde je zase zvykem zakládat PR ještě, než se začne cokoli programovat a řeší se ty věci v tom PR místo v issue a pak se nějak označí (přiřazením recenzenta), že je to připraveno k recenzi a mergování.

Tím nechci říct, že zde někdo udělal něco špatně. Prostě NM žádnou takovouto politiku zatím nemá. Jen dávám inspiraci do budoucna.

**Comment by jindrahelcl** [comment]
@tomkocmi neber si to osobně, já taky udělal spoustu práce, která neni nikde mergnutá. Pokud se řeší takovýhle issues, měla by tomu předcházet nějaká diskuse, nebo aspoň, aby ten, co to dělá napsal, jak to udělá. Jak jsem psal na začátku tohohle shitstormu, můžem za to my, že jsme si nevšimli toho, jak je to řešení načrtnutý v zadání, a nezpochybnili jsme to předem. 

Co se týče přímo tvojí vsuvky k zamyšlení, už to tu je někde napsané - od nových lidí se nebude předpokládat, že budou dělat takovéhle věci. Těžko si představim, že přijde někdo, kdo překopá dokumentaci nebo změní nějaký globální koncept. Pokud to někdo udělá, aniž by se o tom před tím s náma poradil, tak to nejspíš dopadne tak, že odpověď na všechny čtyři otázky bude ne. A bude to správně.

**Comment by jindrahelcl** [comment]
Ale jak teď znova čtu to zadání týhle issue, tak se ani nedivim, že jsme si toho nevšimli, když je tam kulišácky "documentation" místo "configuration"...

**Comment by obo** [comment]
Closed by the merge.
