### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#237]
Commented diagram of data and model workflow.

**Comment by obo** [comment]
Overview je sice zmergovano do mastra, ale chybi v menu vlevo. Prosim doplnit odkaz a pak tohle zavrit.

**Comment by jindrahelcl** [comment]
už jsem to udělal, moje chyba.. :-)

2017-01-19 16:59 GMT+00:00 Ondrej Bojar <notifications@github.com>:
