### ISSUE TITLE
Output config missing in machine translation Example

### ISSUE THREAD

**Issue by JackTemaki** [ufal/neuralmonkey#238]
I just tried to use the framework as stated in the documentary,
and run into following error when translating the trained model:

`2017-01-09 14:44:12: There is no output file for dataset: dataset-neuralmonkey-test/data/test/batch3a_en.txt`

I solved it by adding:
`s_series_named_greedy_out=neuralmonkey-test/data/test/translate.out`
to the test_datasets.ini to get output out of the translation, but this might not be the correct way 
to do it.

**Comment by jindrahelcl** [comment]
Hi, the message you are getting is only a warning -- if you don't need to save the translated output for htis dataset, you can ignore it.
Otherwise, your solution is OK and should work.

Please note that we've just updated the configuration so all strings have to be enclosed in double quotes.
