### ISSUE TITLE
Better TF manager name

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#247]
I think that `TensorFlow manager` is a confusing name, for a new user it might look as part of TF, not NM. Should we change it to something neutral, like `session manager`?

**Comment by tomkocmi** [comment]
I don't think it is confusing at all. And if it is only a little bit and that is not a reason to change the name (the less changes to config the better). But if we want to change any naming in the config we should change it before launch WTM17, later I would suggest never rename anything in the config.

**Comment by jindrahelcl** [comment]
Jestli vám vadí tf_manager, klidně bych to přejmenoval na session_manager, ale je to delší a nepřijde mi, že by to přinášelo nějaký snadnější pochopení toho, co se v něm děje. Novej user kterej si přečte dokumentaci, tak bude vědět, že to neni součást tensorflow.

Pokud to chcete udělat, tak ale hned, ať po releasu pro tuning task nemusíme delší čas dělat nekompatibilní změny v konfiguraci.

**Comment by jlibovicky** [comment]
I don't think that `TensorFlowManaget` makes an impression of being part of TF, because if it was, it wouldn't contain TF in its name. `SessionManager` isn't a bad name either. I am fine with both names.

**Comment by tomkocmi** [comment]
Jestli se rozhodneme tohle zmenit (osobne bych spis nemenil), tak to pak udelam vsechno naraz v jednom pull requestu spolecne s #228 a dalsima, jestli jeste nejake zmeny budou ... at se to nemeni neustale po kazde jedne zmene jmena

**Comment by jindrahelcl** [comment]
Já bych se na tohle vykašlal, akorát to teď přidělává práci..

**Comment by tomasmcz** [comment]
Mně ani tak nevadí `neuralmonkey.tf_manager.TensorFlowManager`, tam je zjevné, že je to část NM. Ale například v #245 se píše prostě *TensorFlow manager* a tam bych si právě nebyl jistý, že nový uživatel pozná, že to má hledat v dokumentaci NM.

A když už jsme u toho, příklady konfigurace tf_manageru v dokumentaci trochu působí dojmem, že `[tf_manager]` je nějaká magická sekce, která sama bez classu a odkazu z `[main]` něco nakonfiguruje.

**Comment by jindrahelcl** [comment]
Ok, tak název necháme s tim, že se vysvětlí ta dvě místa. Jedno dávám jako comment do #245, na druhý vytvářim novou issue
