### ISSUE TITLE
Prevent colissions of encoders/decoders variables

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#25]
I you attempt to create more encoders and do not provide its name, it will crash later on collision of the variable scopes. I would suggest a mechanism (probably in utils.py) that would be always asked to get a name and append a number if there would be a collision.

**Comment by jindrahelcl** [comment]
Isn't it better to just require the name of the encoders if there are more of them?

**Comment by jlibovicky** [comment]
Probably yes.

**Comment by jindrahelcl** [comment]
Couldn't we name all objects from the names of the config sections?

**Comment by jlibovicky** [comment]
Do you mean something like: have a look if there is a "name" argument in the sections's callable and if yes, assign the name? I guess, we ccan do it. (There must be always a way to override the name by something else.)

**Comment by jindrahelcl** [comment]
I don't know, maybe it's not so good solution after all.. Perhaps just the section heading it as a default name if no name is provided directly. But that won't solve this issue.

The good thing about taking names _only_ from the configuration section heading is that we are already sure that the names would not collide.

Another idea: If we restrict the configuration so that only some constructors or functions can be called from config builder, we could also enforce all of them to have a 'name' property. (And, at the same time, declare their config parameters explicitly)

**Comment by jlibovicky** [comment]
I would keep the configuration as open as possible to be able to run basically code from it. We should restrict it only in cases when it is absolutely necessary.

It sounds fair to me to say: if you do nothing, the configuration will provide default names and ensure the variable scopes do not collide, if you intervene manually, you can mess it up.

**Comment by jindrahelcl** [comment]
Ok. So, the question is, how to do this.

I am thinking:
- if the name is not specified in the corresponding config section, use the name of the section
- if the name is specified and not collide with anything, use this name
- keep track of assigned names and crash when there is attempt to assign a namet that has been already used.

**Comment by jindrahelcl** [comment]
But, then you will have to have a special mechanism handling the names and the string `name` would become something as an keyword, which I would consider rather unpleasant.

**Comment by jindrahelcl** [comment]
I still don't see a reason why not to use only the names of the sections. I assume that every section corresponds to a single object and multiple instances of one section are not allowed.

**Comment by jlibovicky** [comment]
The name collisions are a problem only if it is also a name of a TF variable scope. I still view the configuration as kind of simplified general scripting language, so it should be possilbe to call anything - even some third parties code from that. If it happens to have a `name' argument, the user should be able to provide whatever the function wants and could be a name which may not even be a string.

**Comment by jindrahelcl** [comment]
And isn't it ok if TF crashes on name duplicity if the duplicity is caused by bad configuration?

**Comment by jlibovicky** [comment]
Well, if you write the same name twice, it is certainly OK. If you use a default name and then you get a cryptic message about forgotten reuse flag somewhere deep inside a constructor, it will be confusing for a user. This is why I wanted to have a mechanism that would by default ensure the variable scopes will not collide.

**Comment by jindrahelcl** [comment]
Ok. Maybe it should be a part of the checking module then? When the config is parsed, we know the names and then we can do something about it..

**Comment by jlibovicky** [comment]
It's probably too early to it in this stage. What if you need (for some reason) to have the same names. So... I would rollback to your first suggestion: just explicitly require a name for classes which create a TF variable scope and that would be it. We should also make a remark in the configuration specification.
