### ISSUE TITLE
TER is not Edit distance

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#252]
The post-editing tutorial uses Edit distance as a synonym for TER. It is not the same because standard edit distances uses only substitutions, additions and deletions, whereas TER allows swapping words.
Moreover, edit distance is as we have it implemented right now works on character level, whereas TER works on word level.

There is a Python implementation of TER with a suitable license called [pyter](https://pypi.python.org/pypi/pyter). Would you mind using it?

**Comment by jindrahelcl** [comment]
Sure not, it seems simple enough.. Let's go for it.

**Comment by jindrahelcl** [comment]
Teď už stačí změnit ten tutoriál?

**Comment by jlibovicky** [comment]
Myslím, že jo.

**Comment by jindrahelcl** [comment]
V MT tutoriálu to neni  -> neni to ani důležitý pro neural training task

**Comment by jindrahelcl** [comment]
He a mimochodem už je to hotový.. :-)

**Comment by obo** [comment]
Ja ale nijak zvlast nekontroloval text tutorialu, mozna jsem to opravil, ale v tom commitu mi slo jen o spustitelnost, kde se volal TER nejak postaru.

**Comment by jindrahelcl** [comment]
Jo já už si vzpomínám.. Já to totiž opravil a zapomněl jsem tadyto zavřít. Nebylo to postaru, jen to bylo víc explicitně. Předtim se dělal objekt uvnitř konfigurace pomocí konstruktoru:

```
[ter]
class=evaluators.ter.TEREvaluator
name="TER"
```

A odkazovalo se na něj pomocí ``<ter>``, a tys to jen změnil na kompaktnější ``evaluators.ter.TER``, což je staticky vyrobená instance třídy ``TEREvaluator`` s defaultníma parametrama, aby se to dalo psát rovnou. Stačí se podívat do kódu, neni to nijak začarovaný! https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/evaluators/ter.py
