### ISSUE TITLE
Image Captioning

### ISSUE THREAD

**Issue by f00barin** [ufal/neuralmonkey#256]
Hi, I was wondering if there is an easy way of doing image captioning using neuralmonkey. Is there an config file that I could take a look at? Thanks

**Comment by jlibovicky** [comment]
Hi, after the PR #254 introducing pre-trained ImageNet networks will get reviewed and merged, it will be relatively easy.

If you don't want to wait until it's in the master branch, you ca checkout the `imagenet` branch. There is a test configuration in `tests/captioning.ini` which shows how the ImageNet encoder is used. Note that to make the captioning work, you will need make the decoder states reasonably big and load checkpoint for the ImageNet network you want to use from the [slim project](https://github.com/tensorflow/models/tree/master/slim) readme.

**Comment by f00barin** [comment]
Ah! great, thanks. I will check it out!
