### ISSUE TITLE
Try typeguard

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#270]
Check constructor's arguments at runtime.

**Comment by jindrahelcl** [comment]
Interesting.. How do you want to do this - typeguard the config building with the `with TypeChecker('package')` style?

**Comment by tomasmcz** [comment]
I thougt I'd just place `assert  check_argument_types()` at important places. Almost everything is checked statically with mypy, except for constructors that take values directly from configuration. I'm going to try a few experiments with the typeguard package, see how the errors behave in different settings and then create a PR with the best solution I find.

**Comment by tomasmcz** [comment]
Solved in #276 .
