### ISSUE TITLE
Initialize (or bias?) final output layer based on unigram token probabilities

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#274]
As an option, decoder.state_to_word_W should be initialized by (neg log of) target word unigram probabilities. Or perhaps the bias should be set so. This should save a few iterations at the beginning.

**Comment by jindrahelcl** [comment]
de-duping with #275

**Comment by jlibovicky** [comment]
If it really helps, I would do it before #275 which requires much bigger effort. Unless you're willing to do #275 any time soon.

**Comment by jindrahelcl** [comment]
I see #275 as a next thing to do when I'm bored. As I've been sick and stayed at home today and probably will stay home tomorrow as well, I might do it quite soon. If you just want to try the different initialization, why not to just create a branch, do the edits there (read: hard-code the change in the initialization method) and try it. It should be quite easy, @obo could use it as an excercise to get to know the codebase. ;-)
