### ISSUE TITLE
Configurable initialization of variables

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#275]
`ModelPart` objects should be refactored to have a method (or a function supplied as a parameter to the constructor), that returns a dictionary of variable names and their respective initial values (given something like a dictionary of variable names and their shapes)

**Comment by obo** [comment]
I would stick to the simpler #274, which would be just an enhancement without refactoring. Let's leave the choice up to the kind volunteer who picks this up. :-)

**Comment by jindrahelcl** [comment]
Solved by #623
