### ISSUE TITLE
make documentation use python 3.5 and correct TF version

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#277]
Why does `requirements.txt` for docs state different version of TF than the package itself? Even different Python version? I don't want to switch to a new environment just to build documentation.

**Comment by jindrahelcl** [comment]
Já myslim, že `docs/requirements.txt` se může smazat. Je tam Python 3.4, protože readthedocs nepodporujou Python 3.5.. Tohle jsem vyřešil, a používají se teď místo toho .readthedocs*yml soubory, který jsou up-to-date.

**Comment by jindrahelcl** [comment]
smazal jsem to a funguje to.

**Comment by tomasmcz** [comment]
A jak si mám lokálně buildovat dokumentaci?

**Comment by tomasmcz** [comment]
Nicméně udržovat dva seznamy je asi hloupost, naistaluju si to ručně podle to YML.

**Comment by jindrahelcl** [comment]
YML plus to, co readthedocs maj v defaultu

**Comment by jindrahelcl** [comment]
a pak jen `make html`
