### ISSUE TITLE
Multiple decoders

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#28]
We should be able to create models that have more decoders at the same time. E.g. that would classify a sentence and output a sequence at the same time.

**Comment by jindrahelcl** [comment]
Definitely.. More, the decoders should be able to somehow look what they have generated so far (and the order or priority should be also somehow configurable)

These are some (very wild) use-cases that come to my mind (not revisited so maybe nonsense):

- combination of classifier and sequence decoder, for example first, classify whether the sentence is positive/negative or negated or something like this and then, using this knowledge, translate it.
- translation to multiple languages at once (A->B and A->C) using also a translation model between B and C (for example, translation from English to Czech and Slovak)
- combination of tagger and translation (or parser) - decoder for translation could be able to look at the results of the tagger (or the other way around, for fun).

**Comment by jlibovicky** [comment]
Solved in #151.
