### ISSUE TITLE
update configuration files and tutorials

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#284]
Update all example and test configration files as well as tutorials:

- [x] don't use `config.utils`; use e.g. `dataset.load_from_files` instead of `config.utils.dataset_from_files`
- [x] don't use `vocabulary.initialize_vocabulary`, use `vocabulary.from_dataset` or `vocabulary.from_file`

**Comment by jindrahelcl** [comment]
`vocabulary.initialize_vocabulary` does one of two things: either `vocabulary.from_dataset` or `vocaulary.from_file`, depending on existence of a file whose name is inferred from the `directory` and `name` arguments... So you have to think a little before doing the change.
