### ISSUE TITLE
Support config changes on command line

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#285]
neuralmonkey programs should support command-line parameters to modify the config, e.g.:

neuralmonkey-train config.ini -s main.batch_size=60 -s main.output='"new-output-dir"'

(The need for having apostrophes around quotes is a little annoying but that's life.)

Ondra Cifka also suggested to support 'modifying configs', e.g.:

cat > modconfig.ini << END
[main]
batch_size=60
output="new-output-dir"
END

neuralmonkey-train config.ini -c modconfig.ini

**Comment by jindrahelcl** [comment]
Myslim si, že jsme se o tomhle už bavili v září a že sis udělal tool na editaci konfigurace - proč nepoužiješ ten? Tenhle návrh se mi moc nelíbí, ale možná na to mají @jlibovicky nebo @tomasmcz jinej názor..

**Comment by jlibovicky** [comment]
I like this idea. It would be handy especially for submitting more jobs on cluster. Since the configuration parsing and execution does not interleave anywhere, I believe it can be implemented relatively easily. What is important though, is that the `experiment.ini` file in the experiment directory would need to reflect these changes, so the experiment directory contains everything that is need to replicated the experiment. Personally, I like more the version by @obo.

**Comment by jindrahelcl** [comment]
For preserving reproducibility, the only thing you'd need to do is to log the command that was run to a file placed in the experiment dir, similarly to `git_commit` or `git_diff`...

**Comment by obo** [comment]
Protoze Ondra Cifka sam od sebe rekl, ze na jeho soucasne pokusy je eman overkill, ale menit parametry by se mu hodilo. Puvodne jsem chtel Ondru poprosit, at to issue vyrobi on, ale pak jsem to udelal sam.

----- Original Message -----
> From: "Jindra Helcl" <notifications@github.com>
> To: "ufal/neuralmonkey" <neuralmonkey@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Wednesday, 25 January, 2017 18:33:34
> Subject: Re: [ufal/neuralmonkey] Support config changes on command line (#285)

> Myslim si, že jsme se o tomhle už bavili v září a že sis udělal tool na editaci
> konfigurace - proč nepoužiješ ten? Tenhle návrh se mi moc nelíbí, ale možná na
> to mají @jlibovicky nebo @tomasmcz jinej názor..
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ufal/neuralmonkey/issues/285#issuecomment-275175790

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by cifkao** [comment]
My idea was to write the modified configuration to `experiment.ini` as @jlibovicky wrote. Then you could clone experiments like
```bash
neuralmonkey-train a/experiment.ini -v 'main.output="b"'
neuralmonkey-train b/experiment.ini -v 'main.output="c"'
```

I can think of two ways to do this:

1. Do the same as `modify_monkconfig.pl`, i.e. load the ini file as text and edit it line by line before parsing it with `ConfigParser`.
2. Parse the file first, then use `config.set(section, option, value)` and `config.write('experiment.ini', space_around_delimiters=False)`. This is much easier, but the formatting could still change a bit, and we would lose comments. But the original config can still be kept in a separate file, along with the command line options.

**Comment by jindrahelcl** [comment]
There were some problems with the configuration generation in the past and I am not sure whether those problems would still emerge. @jlibovicky and @tomasmcz know more.. 

That said, I'd rather have the second option for the setting of the variables, but preserve the original `experiment.ini` and the changes to it separately, so you can keep track of what was the "parent" config and what were the changes.

To easily replicate experiments, however, it would be handy to also have a valid ini file with the used configuration (after changes)..
