### ISSUE TITLE
Post-release development

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#290]
After the first release (or maybe actually a little before that) of this software is published, we should move to a more structured workflow scheme. After I googled for best practices in this, I propose to have this model:

* The `master` branch with the stable version
  * `hotfix-*`branches branched from `master` and merged to both `master` and `dev`.
* A `dev` branch, which would contain the new features and changes
  * Feature branches branched from this branch, rebased on this branch before merge
* `release-*` branches created from the `dev` branch with desired changes for a new release. 
  * Only bug fixes should be committed to these branches. (And when they are, they should be merged back to `dev` as well.)
  * These branches, when tested, are merged to `master`

Here (http://nvie.com/posts/a-successful-git-branching-model/) is a nice example with a picture.

In the article, there is also a suggestion to use merge everywhere (no mention of rebase), and to use merge with the `--no-ff` option, which creates a merge commit even if it's not necessary. I'd like to put this to discussion. (I am in favor of the rebase+merge workflow as we are used to now.. In case of the feature branches only, of course.)

As soon as this is discussed, I'd switch to the selected scheme so we could prepare the first release for the WMT 17 Neural Training Task

**Comment by martinpopel** [comment]
So you are suggesting to move from the current [GitHub flow](https://guides.github.com/introduction/flow/) to the old [Git flow](http://nvie.com/posts/a-successful-git-branching-model/)?
There are [many][1] [reports][2] comparing those two flows. Have you read those?

Personally, I would say Git flow has too much overhead (esp. for such young&small project as NM) and it may discourage some people from contributing (today there many more programmers familiar with GitHub flow than Git flow).
Of course, this is subjective, my vote has zero weight (based on number of commits) and you - NM developers, should know what is the best for NM.

[1]: http://scottchacon.com/2011/08/31/github-flow.html
[2]: https://lucamezzalira.com/2014/03/10/git-flow-vs-github-flow/

**Comment by jindrahelcl** [comment]
No, I have not read them, but I will.. :-) Thanks. I didn't even know these things have those names.

**Comment by jindrahelcl** [comment]
@martinpopel Don't be so hard on yourself, based on number of commits, your vote would have weight 1.. :-)

I've read the first article (about Github flow by a guy from Github), and I see his point. I'll have to think about that and maybe re-think my suggestion.. On the "git flow", I like the fact that you keep a few releases and you don't need to e.g. update your examples for every feature in the development branch.

On the other hand, I think it is partially in conflict with the idea of neural monkey - to be a system for easy and fast prototyping of new seq2seq models. The git flow looks quite rigid for this kind of use.

How would you do releases (i.e. marking some "important" or "tested" versions) - by using tags?

**Comment by martinpopel** [comment]
> How would you do releases (i.e. marking some "important" or "tested" versions) - by using tags?

Yes, as usual. Git tag and (at least for major releases) also downloadable archive at https://github.com/ufal/neuralmonkey/releases.
For marking beta versions, minor bugfixes etc. you can use e.g. [semantic versioning](http://semver.org/).
BTW: Has NM adopted some versioning system?

**Comment by jindrahelcl** [comment]
Ok, I see. Is there a standard way of making these releases? Or do you think it would be better to put the monkey to PyPI? (With TF in PyPI, there is no real obstacle to do that.) Or better to do both?

As for the versioning system, not yet..

**Comment by martinpopel** [comment]
> Is there a standard way of making these releases?

[Yes](https://github.com/ufal/neuralmonkey/releases/new). GitHub releases can contain also compiled binaries, documentation and unversioned example data, but this is probably not needed in NM (well, docs as pdf+html may be handy).
I guess you know how to do (annotated) [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging), they show up automatically in [GitHub tags](https://github.com/ufal/neuralmonkey/tags).

Releasing NM to PyPI, in addition to GitHub is a good idea. It may attract users (who think that all serious Python projects are on PyPI) and it will be easier for other projects to depend the stable version of NM.

**Comment by jlibovicky** [comment]
The _Git workflow_ seems to be too complicated to me. I either stick with the current _Github workflow_, i.e., continuously merge all new features into master and from time to time make a release, at lest until we have something that we would call version 1.0.0. (after all it's a research software). 

On the other hand if you really wish to have a separate devel branch with new features and master only with bug fixes from the latest release, I am to against it.

Ad versioning: semantic versioning is fine :-)

**Comment by jindrahelcl** [comment]
To sum this up:

- use semantic versioning (already adopted in the first release)
- keep using Github workflow
- create release for PyPI (for 0.1.1)

If you all agree, we can close this issue.

**Comment by tomkocmi** [comment]
I do not have any opinion on this topic (except that I also want the github workflow, but as I see it is proposed). Therefore as for me, you can close it

I would like to have development as simple as possible :)
