### ISSUE TITLE
Docs on updating

### ISSUE THREAD

**Issue by martinpopel** [ufal/neuralmonkey#294]
I guess, there should be a notice that after each `git pull` it is recommended (if any problems appear) to run
```
pip3 install --upgrade --user -r --requirements.txt
```

Also, https://github.com/ufal/neuralmonkey/blob/master/README.md says `pip install -r requirements.txt`
but http://neural-monkey.readthedocs.io/en/latest/install.html says `pip3 install --upgrade -r --requirements.txt`
Shouldn't the former be updated?

I am no Python expert, but I guess that you either need `virtualenv`/ `python3 -m venv`
or `pip3 install --user` or `sudo pip3 install`.

**Comment by jindrahelcl** [comment]
I would change the installation instructions to use `virtualenv` and then update the README according to the installation instructions.
We can then expand the installation docs for users using Conda, `sudo`, `--user` or anything else, but I don't see that as a high-priority issue.

**Comment by jindrahelcl** [comment]
I edited teh README file and created a pull request here: #295
