### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#299]
I noticed that the current `tests\bpe.ini` issues a warning (“Warning: The rnn_size argument is ignored...”). I think that the test configurations should also serve as examples and therefore shouldn't contain things that lead to warnings.

To avoid this in the future, I propose the following:

- create a `logging.warning(...)` function and use it instead of `logging.log("Warning: ...")`
- create a `--strict` switch for executables that raises an exception instead of a warning and enable it in tests

What do you think?

**Comment by jindrahelcl** [comment]
Měl jsem pocit, jsem cca před dvěma měsíci otvíral issue Make logging the way it should be done, ale teď jí nemůžu najít ani mezi zavřenýma issues, tak jsem si jí asi vysnil..

* Jsem všema deseti pro udělání funkce
* Simulování scénářů s warningama mi v době, kdy jsem to tak udělal, přišlo cenný, protože to zvyšuje coverage. 
* `--strict` bych neudělal switch, ale environment variable `NEURALMONKEY_STRICT` nebo něco takovýho. Už se podle environment variables řídí, co se loguje. V zájmu zachování čistýho commandu na spouštění - tyhle věci imho často lidi dělaj defaultně, a tak si ty proměnný můžou nastavit někde v `.bashrc` nebo tak.
