### ISSUE TITLE
Move to Python 3.5

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#3]

**Comment by tomasmcz** [comment]
Python 3.5 has some advantages over 2.7. The one I find most important is far better support for type annotations. If we decide to move to Python 3.5, we should do it now, while we are refactoring things and working on code quality. What do you think, @jindrahelcl, @jlibovicky?

**Comment by jlibovicky** [comment]
I would definitely go for Python 3.5 as soon as we can. Using this the 2to3 tool {https://docs.python.org/3/library/2to3.html) it should be painless.

**Comment by jindrahelcl** [comment]
Again - as long as it's working, please yourself.

**Comment by jindrahelcl** [comment]
But it would be nice of you when you do some changes to tell us (for example if you change the way the thing is run).

**Comment by tomasmcz** [comment]
I created a branch called `py35` that runs Travis with Python 3.5. I think we can merge it when all tests are passing.

**Comment by tomasmcz** [comment]
Co na nich má být změněné?

**Comment by jindrahelcl** [comment]
Mělo by to bejt `#!/usr/bin/env python3`, aby se zvolil python 3 když máš oba a aby to rovnou spadlo, když máš jen python 2. Nevim, jestli má python 3 taky `python` ale z netu jsem pochopil, že ne.

**Comment by jindrahelcl** [comment]
Jaká je politika teďko se zpětně nekompatibilníma věcma (konkrétně dělení integerů) - mam se na to vykašlat, nebo mam dávat from __future__ import division nebo to mam explicitně přetypovávat?

**Comment by jlibovicky** [comment]
Vůbec nevím na co se ptáš :-)

**Comment by jindrahelcl** [comment]
No ve starym pythonu když napíšeš 1/2 tak ti to dá 0, kdežto v novym ti to dá 0.5.. Leda bys ve starym dal ten import z budoucnosti anebo kdybys napsal float(1)/2 nebo ňák tak.

**Comment by tomasmcz** [comment]
Just use `/` for float division and `//` for integer division (standard Python 3 usage).

Again, this is one the issues that someone might want to read in the future, so we should write in English, unless of course you're willing to go through every Czech conversation once a week or so and sum the results up somewhere (preferably in currently non-existent documentation).
