### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#316]
The examples are not working even when the release is out. Why do we have them? Can we put a note into the readme for people not to use them? Or into the tutorial?

**Comment by tomkocmi** [comment]
Specially the translation do not work because it does not have bpe correctly activated (we have found out because of Matiss who could not get it work). I didn't check it by myslef

**Comment by tomkocmi** [comment]
Sorry for the false alarm :), there was problem somewhere else. But if you are reading this did someone actually check the examples?

**Comment by jlibovicky** [comment]
No one did and after quick reading through them i can see:

1. the string are not in quotes in the ini files
2. multiobjective trainining using `MultiDecoder` is deprecated
3. `FactoredEncoder` used in `factored.ini` is broken (I've seen a fix in the Heidelberg fork)

It will be a lot of work to debug everything, but we can at least warn in the examples README that the examples are outdated.

**Comment by jindrahelcl** [comment]
Maybe we could first fix only the translation ini and mark all the others as deprecated or outdated. The translation example is the only one that could do any real harm in the following days.

**Comment by tomkocmi** [comment]
I would just deleted them all and rather have nice tutorial where we already have two examples and can redirect into tests. I think that the "examples" folder is redundant and because it do not work, Matiss spent a lot of time on it trying to get it work in last few weeks.

**Comment by jindrahelcl** [comment]
i am wokring on functional examples in a new branch.

**Comment by StoyanVenDimitrov** [comment]
Hello,

I'm follwing the sters of the tutorial for machine translation on http://neural-monkey.readthedocs.io/en/latest/machine_translation.html 
After executing $ bin/neuralmonkey-run exp-nm-mt/translation.ini exp-nm-mt/translation_run.ini
I receive:
There is no output file for dataset: dataset-exp-nm-mt/data/test/Batch3a_en.txt.gz 

Where this 'dataset-exp-nm-mt/...' comes from? I guess it should be 'exp-nm-mt/...'.

Best:
Stoyan

**Comment by jindrahelcl** [comment]
Hi,

the "dataset-" is a prefix that forms the name for the dataset (concatenated with paths of the input series). It's a little unfortunate here because the warning message is a bit confusing..

Anyway, if you don't care about the actual outputs for this dataset, you may ignore this warning. Otherwise, you may want to specify the output series path for the dataset by adding something ``s_target_out=path/to/file.out`` to the dataset configuration (where `target` is the ID of the series generated by the decoder).

**Comment by StoyanVenDimitrov** [comment]
Hi,
but actually the model is not even really being evaluated after running $ bin/neuralmonkey-run exp-nm-mt/translation.ini exp-nm-mt/translation_run.ini. I get: 
2017-03-....: Evaluating model on "dataset-exp-nm-mt/data/test/Batch3a_en.txt"
2017-03-....: ... series_named_greedy/runtime_xent: 0
2017-03-....: ... series_named_greedy/train_xent: 0     and that is. 

Does anybody else made this experience? It's probably something on my setup during training.

**Comment by jlibovicky** [comment]
Hi, it seems you forgot to specify the target series, so there is nothing you can evaluate the model against.

**Comment by jindrahelcl** [comment]
There is no reference (Czech) series for batch3a, so it cannot be evaluated on that.

The losses (and anything else for that matter) in this case simlpy can't be computed. Try adding the validation dataset to the run script as well, including the target series (batch2a_cs)... It should report BLEU and cross entropy on the dev set.

**Comment by StoyanVenDimitrov** [comment]
I didn't notice... :D. Thank you, guys! Now it works.

**Comment by jindrahelcl** [comment]
(closing the examples issue (#357 was merged))
