### ISSUE TITLE
The lib directory

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#32]
Should `subword_nmt` be a submodule? Are we doing the imports right?

**Comment by jindrahelcl** [comment]
It cannot be a submodule because we have changes in it and when it is a submodule, you cannot push your changes in this repository.

**Comment by jindrahelcl** [comment]
Requirements (in order of priority):

1. Be able to do changes in the 3rd party software and push them here
2. Be able to pull changes from the foreign repository
3. Anything else

**Comment by tomasmcz** [comment]
What changes do we have? Would the original repo benefit from them?

I think that we should fork the 3rd party repository and include the fork as a submodule. That way you can do whatever changes you need (and offer them to the authors of the repo, if they are useful to them) and you can easily pull and merge their changes.

**Comment by jindrahelcl** [comment]
No, it's just some hacks nobody would benefit from. Plus, there is the `__init__.py` file that was not in the original repo. Do as you think as long as it's working, i'm no git guru.

**Comment by jindrahelcl** [comment]
until we'll have our own implementation, I'd leave this as it is. feel free to re-open
