### ISSUE TITLE
Modification of travis

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#326]
Can someone please modify travis to stop outputing lines with (locally-disabled). It takes ages to find what does travis want. (Not mentioning that the code is really ugly because of all the pylint exceptions)

************* Module neuralmonkey.encoders.imagenet_encoder
I:  8, 0: Locally disabling unused-import (W0611) (locally-disabled)
I: 12, 0: Locally enabling unused-import (W0611) (locally-enabled)
I: 49, 0: Locally disabling too-many-arguments (R0913) (locally-disabled)

**Comment by martinpopel** [comment]
Try adding (well, mixing into what is there) this to https://github.com/ufal/neuralmonkey/blob/master/.pylintrc
```
[MESSAGES CONTROL]

# The purpose of locally disabling a warning is to disable it:-).
# If needed we can detect those places with `ack 'pylint: disable'`.
disable=locally-disabled,locally-enabled
```
