### ISSUE TITLE
Unify type hints

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#329]
Currently we are using both PEP 484 type hints and typing in comments (e.g. in BLEU evaluator).

Unify to use PEP 484 type hints everywhere.

**Comment by tomasmcz** [comment]
@jlibovicky claims this is done.

**Comment by jindrahelcl** [comment]
`find -name \*.py | xargs grep -B1 '# type'` claims it isn't

**Comment by tomasmcz** [comment]
- `grep -n1 '# type' -r neuralmonkey` je mnohem hezčí
- typehints u instancí se píšou komentářema

**Comment by jindrahelcl** [comment]
Jo, dobrý, grepoval jsem ve starý verzi.
(Mimochodem, tvuj příkaz pro mě hezčí neni, protože grepuje i věci, co nejsou python zdrojáky a taky neukazuje předchozí řádku, podle který jsem zjistil, že to nejsou typehints u instancí ale u definicí funkce.)

**Comment by tomasmcz** [comment]
V tý složce nic jiného než pythoní zdrojáky být nemá a `-n 3` ukazuje okolní řádky. Je to jednodušší a má to hezčí výstup.

**Comment by martinpopel** [comment]
Už dlouho jsem se nezúčastnil žádného flame, takže zde je má troška do mlejna:
`ack --python -B1 '# type' neuralmonkey`
Je to mnohem [rychlejší a lepší než grep](https://beyondgrep.com/) a kdo to nepoužívá je vopice:-).

**Comment by jindrahelcl** [comment]
Jsou tam ještě ty prekompiláty, ne?
