### ISSUE TITLE
update documentation and helper scripts to TF 0.9

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#34]
This should have been done in the `tf9` branch before the merge.

**Comment by jindrahelcl** [comment]
Which scripts? What documentation?

**Comment by tomasmcz** [comment]
- [ ] `prepare_env.sh`
- [ ] `README.md`
- [ ] anything else, @jlibovicky?

**Comment by tomasmcz** [comment]
Should we also add TF to `requirements.txt`?

**Comment by jindrahelcl** [comment]
i think requirements file is passed to pip, so no..

**Comment by tomasmcz** [comment]
The problem with TF would be that we don't know whether the user wants the CPU or GPU version.

**Comment by jindrahelcl** [comment]
The code works in both versions and we should keep it that way.

**Comment by jlibovicky** [comment]
+1 for keeping TF out

**Comment by jlibovicky** [comment]
`prepare_env.sh` updated in the py35 branch.

**Comment by tomasmcz** [comment]
It should have been updated in master and py35 should have been rebased (which will need to happen anyway). If we now decide to abandon the py35 branch, this issue would be closed and the change would be lost.
