### ISSUE TITLE
What happens when training is run with multiple sessions and multiple initial variables?

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#351]
I get that for running, this allows for ensembles. But training? I don't really know what this might be good for. Shouldn't we restrict using multiple sessions during training to 1?

**Comment by jlibovicky** [comment]
It should train multiple models with different initialization at the same time. The results you will see in the logs should be results of ensembling of these models. However, ensembles do not work with greedy runner.

I doubt it is a useful feature, but if the ensembles work, it's basically for free with the class design we have.
