### ISSUE TITLE
Split the regression test case on Travis to separate test cases

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#356]
Why do we do all the regression tests in one script when we can run them in parallel?

If we separate them, not only it may reduce the overall test execution time, but it will also fix the fact that now, when one test fails, all the subsequent tests are not run.

**Comment by tomasmcz** [comment]
Because

1. you made tests depend on each other (on `vocab.ini`, to be precise)
2. we don't want to have to install the environment for each test separately on Travis
3. if one test fails, we don't want to run more tests on Travis

**Comment by jindrahelcl** [comment]
1. O tomhle vím. Ale je velmi jednoduchý to na `vocab.ini` udělat nezávislý a přesto ekvivalentní (mít vocabulary někde uložený a po skončení `vocab.ini` kontrolovat, jestli je vytvořený a uložený slovník stejný.
2. Chápu, že by se tam dělala stejná práce několikrát, ale čemu by to vadilo? 
3. To neni pravda. Například když jsem dělal přestup na TF 1.0, tak spadl každý test na něčem jiným. Kdyby to jelo paralelně, budu na jeden run testování vědět víc informací. Jasně, často nastane i situace, kdy všechny  testy spadnou na stejný chybě, ale zase - čemu to vadí? Testy běží paralelně, tj. čas, který potrvá zjistit, že to všechno spadlo na tom stejným bude zhruba stejnej, jako čas zjistit, že padá to první.

**Comment by jlibovicky** [comment]
Myslím, že Tomášův argument pro bod 3. je, že jakmile to spadne na Travisu, tak si to stejně pustíš lokálně a zjišťuješ, co si rozbil lokálně a nepushuješ to pořád dokola, aby to zjistil Travis, kterýho je jenom jedna instance na organizaci.

**Comment by jindrahelcl** [comment]
To neni argument ani na jednu ani na druhou stranu - když to děláš tak, že vidíš, jak to spadlo, opraviš chybu a pushneš, tak se travisem plýtvá podobně stejně v sériovým i paralelním typu testování.
Nadto, pokud to někdo takhle dělá (já občas třeba před pushem otestuju lokálně jen ten test, kterej spadnul), tak když bude mít logy ze všech testů, tak to v tom paralelním testování dělat nebude, protože rovnou uvidí, že za rohem to padá na něčem jiným.

A neumožňuje náhodou travis něco jako běh několika testů ve sdíleným environmentu?

**Comment by jlibovicky** [comment]
Mně ta takhle dělit přijde proti duchu tomu, jak se ten Travis tváři, že se má používat - že se tváří, že by všechny testy téhož druhu měly být v jedné test suite nebo jak tomu říká. 

Ale spíš bych udělat pořádně ten náš skript - jako když pustíš pylint nebo unit testy: provést všechny testy a nakonec do přehledné tabulky, co prošlo a co spadlo. To mi přijde, že řeší tvoje trápení úplně stejně a je to v duchu Travisu a toho, jak vypadají ty ostatní testy.

**Comment by jindrahelcl** [comment]
To smysl dává, no.. I tak bych ale zkusil testovat všechno, tj. bez `set -ex` na začátku skriptu. Nevýhoda tady bude v tom, že se v tom logu půjde těžko vyznat a i když něco padne na něčem jiným, snadno chybu přehlídneš.

**Comment by tomasmcz** [comment]
Travis není debugger, měl by jenom co nejrychleji (tj. s co nejméně zdroji, takže tak jak je to teď) nezávisle zkontrolovat, že je kód v pořádku. Pokud zrovna neopravuješ nějakou chybu v nastavení Travisu, což by se nemělo dít moc často, tak nemá být pohodlný. Do těch logů na Travisu bys neměl potřebovat vůbec koukat, protože si máš pustit testy lokálně. `set -ex` je mimo jiné dobré k tomu, že to spadne co nejdřív, takže se dřív dozvím, že je nějaký problém.

**Comment by tomasmcz** [comment]
Rozdělení těch skriptů by víc zatěžovalo Travis a navíc by usnadňovalo debuggování na Travisu, což opět víc zatěžuje Travis. Zatěžovat Travis není slušné chování, není dobré pro Travis a ve výsledku ani pro nás.
