### ISSUE TITLE
unstated dependencies

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#36]
`neuralmonkey/estimate_scheduled_sampling.py` is depending on scipy. Scipy is quite a big dependency, I'd hate to install it just for the one function. Can we do something about this?

**Comment by tomasmcz** [comment]
Also `image_utils.py`. Maybe we should make scipy a dependency, but I'd rather avoid that, if it is at all possible.

**Comment by tomasmcz** [comment]
And `precompute_image_features.py`. Maybe some of these scripts should be outside the package?

**Comment by tomasmcz** [comment]
Related case: `javabridge` in `decompound_truecased.py`.

**Comment by tomasmcz** [comment]
And Flask in logbook.

**Comment by tomasmcz** [comment]
And caffe int the caffe script. This one I think should go into some helper directory or somewhere else outside the package itself.

**Comment by tomasmcz** [comment]
And `h5py` in `reformat_downloaded_image_features.py`.

**Comment by jindrahelcl** [comment]
All of these should go to some scripts directory (and out of neuralmonkey package). I have partially begun to work on this.

**Comment by martinpopel** [comment]
In Python, I've always seen `bin` directory to be recommended (not `script` as in Perl, not `scripts`).
See e.g. [this](http://learnpythonthehardway.org/book/ex46.html), [this](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html), or [that](http://as.ynchrono.us/2007/12/filesystem-structure-of-python-project_21.html).

**Comment by jindrahelcl** [comment]
Ok. I will separate the files that are not  directly dependent on the package and then, we provide additional docs for these with separately listed dependencies which will not be installed with the package.

**Comment by jindrahelcl** [comment]
As for logbook, I would leave it and add flask to package requirements. @jlibovicky ?

**Comment by jlibovicky** [comment]
Sure, keep logbook where it is.  `reformat_downloaded_image_features.py` can be deleted. I think we can get rid of the German decompounding stuff together with the javabridge package.

The image stuff is tricky. If we would want neuralmonkey to replicate the multimodal experiments, we definitely need them, although scipy is a huge dependency and installing caffe is an odyssey.

**Comment by jindrahelcl** [comment]
Put all the things to the `bin` dir, maybe try to update them with the new package api and leave them for the time we want to replicate the experiments.

**Comment by tomasmcz** [comment]
I think this is all done now.
