### ISSUE TITLE
report_gpu_memory_consumption=True is broken

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#364]
This parameter makes training impossible since it only loads model into GPU and then it waits indefinitely.

**Comment by kspar** [comment]
Works for me

**Comment by jindrahelcl** [comment]
@tomkocmi would you provide more details (e.g. log, config file and commit id?)

**Comment by tomkocmi** [comment]
we have examined it with @jlibovicky ... I have run machine training task config on new monkey (commit from two weeks ago). And it didnt' train and was only in a look. It can be a problem with our architecture, but I am not an expert in it. With Jindra we traced it into a call to the outside of NM.

**Comment by tomkocmi** [comment]
I have found another clue for this. The problem appears only when the model is too big and cannot get into the GPU. In that case it just freeze instead of falling down.

**Comment by jlibovicky** [comment]
I would just remove the `report_gpu_memory_consumption` feature. The memory consumption does not change during training anyway and it makes problem under unknown circumstances.

**Comment by jindrahelcl** [comment]
seconded..

**Comment by tomkocmi** [comment]
@obo go for it :D
