### ISSUE TITLE
logbook

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#37]
Why is this `logbook` thing in master? Is it done or is it work-in-progress? If it's done, flask should be a dependency. It is not used anywhere, is it a stand-alone tool? Then it should be documented somewhere.

**Comment by jlibovicky** [comment]
Although more feature are welcome (#29, #30), it is ready to use now.

This is what should be done ASAP:

- [ ] change the title (now that we know it's a monkey)
- [ ] reformat the options in the TensorBoard style
- [ ] add flask to requirements
- [ ] create a README file

**Comment by tomasmcz** [comment]
Then this logbook thing should have its own executable. Also, don't do `python neuralmonkey/file.py`, it will not work well with imports.

- [ ] create an executable
- [ ] update readme
