### ISSUE TITLE
Parent classes for Encoders and Decoders

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#370]
I know this was discussed several times, but what about doing at least placeholder for that class first before we know what is needed to be put there? I think already there is several things every Enc/Dec should contain.

**Comment by jlibovicky** [comment]
Ideas on how the class hierarchy should look like are gathered in a [Google doc](https://docs.google.com/document/d/1l4FIsXcYYyqt9yky9dxc9qcR5UWOfCd2-5nPga3yH0Y/edit?usp=sharing).

**Comment by tomkocmi** [comment]
Is being solved by current code refactor.
