### ISSUE TITLE
Package executable

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#38]
The package should somehow provide an executable. Right now the training may be executed with `python -u -m neuralmonkey.train whatever.ini`, maybe we should document this somewhere until we find a better way to do this. One of us will have to learn how to manage a proper Python package.

**Comment by martinpopel** [comment]
We had a similar issue in the [Udapi](http://udapi.github.io/) project and created a bin directory with [an executable](https://github.com/udapi/udapi-python/blob/master/bin/udapy), which can be added to PATH. @zabokrtsky [observed](https://github.com/udapi/udapi-python/commit/1eeb89de7) that naming the executable as the main package + ".py" (so `neuralmonkey.py` in this case) leads to  hard-to-debug problems. Let us know if you find another solution than choosing a different name for the executable.

**Comment by jindrahelcl** [comment]
New executables are in `bin`.

- `neuralmonkey-train` does what train.py used to do
- `neuralmonkey-run` does what run.py used to do

According to http://stackoverflow.com/questions/9027584/how-to-change-the-file-mode-on-github, prior the installation, it is a good thing to include symlink to the package to the bin folder so the scripts could see the package. These links should not be included in the installation, of course, but it is the simplest way to have the executable in bin and to be able to use it during development.

The next thing to do is to create `setup.py`, but for now I think it can wait for other important issues to be solved first.

**Comment by tomasmcz** [comment]
I think this is far from done (and therefore prematurely closed).

- why two executables? I think it would be much nicer to just have one and call it with a command, eg. `neuralmonkey train` or `neuralmonkey run`...
- the convention is (as expressed eg. [here](http://as.ynchrono.us/2007/12/filesystem-structure-of-python-project_21.html)) that the executable should not contain any code, only a call to some method in the package
- the bin folder should only contain the package executable(s), all the helper scripts that are not part of the package should be somewhere else (a `scripts` folder?)

**Comment by jindrahelcl** [comment]
Starting to work on 1 and 2. For 3, find a source describing how it is done properly and we can change that.

**Comment by jindrahelcl** [comment]
Forget it, if you have an idea how to do it best (the 1 and 2), just do it.. I don't have too much time for this now.

**Comment by jlibovicky** [comment]
I would prefer having two separate executables, these subcommands are useful in cases when there complicated hierarchies of commands like git to prevent  having plenty of executables. We will have only two (if we add a server run, than three) executables, that is a reasonable number. But if you think it is so much nicer to have only one executable, do it as you wish.

**Comment by jindrahelcl** [comment]
referencing  #94
