### ISSUE TITLE
Avoid wasting vocabulary size on unseen BPE parts

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#381]
NM with BPE wastes vocabulary entries on "intermediate" BPE merges that never occur alone and only serve to compose larger bpe tokens (or complete words).

Workaround option 1: preprocess all corpora manually, disable bpe pre/postprocessing in NM altogether
Workaround option 1b: keep bpe post-processing on, but remember: the training target side should be provided after bpe splitting while validation target side should be normal tokens (so option 1b is quite messy).

Workaround option 2: keep using bpe processors but beforehand process corpora manually and manually pickle the vocabulary or all seen bpe tokens, load this dictionary instead of dictionary from merges

**Comment by sebastien-j** [comment]
I believe that creating the vocabulary from the BPE codes directly might also cause some training tokens to become unknown.
