### ISSUE TITLE
tests culture

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#39]
Test scripts should be moved away from the root directory. Also, why there is two files, `tests_run.sh` and `run_tests.sh` and what is their purpose? This should be all done in the tests directory. Also with `unit-tests_run.sh`, `mypy_run.sh`, `lint_run.sh` and others.

Also, one of the run tests scripts (tests_run i think) should use the `-P` (or `--directory-prefix`) option of wget instead of `cd`-ing there and back again. The `test-output` directory should  be generated somewhere else than in the root of the repository, preferable in a temporary location either in `/tmp` or in a `tmp` dir in subdirectory of `tests`.

**Comment by jindrahelcl** [comment]
It is also needed to add documentation for these tests.

**Comment by jindrahelcl** [comment]
Some (http://as.ynchrono.us/2007/12/filesystem-structure-of-python-project_21.html) even say that directory for unit tests should be inside the package.

**Comment by tomasmcz** [comment]
I was planning on moving these files, will do that after #3. Unit tests already are inside the package. What should be in the documentation?

**Comment by jindrahelcl** [comment]
The question is what shouldn't... 
These things definitely should: How the tests are run, which is which and what do they test.

**Comment by tomasmcz** [comment]
OK, I will write a readme file after I move the files.

**Comment by tomasmcz** [comment]
All done.
