### ISSUE TITLE
CPU memory exhaustion

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#390]
Na tuhle chybu jsem uz narazil mnohokrat, nemohu najit sve posledni issue k teto chybe (vim, ze jsem vytvarel uz minimalne dve a mozna byly vyreseny nejake chyby mezi, ale nikdy ne tato hlavni).

Jde o to, ze s kazdou validaci si opice neco ulozi do CPU pameti a necha to tam. Uz jsem prochazel kod validace a nevim, co je zdrojem, kazdopadne po dostatecne velkem mnozstvi validaci dojde k zaplneni pameti. 

Bohuzel tohle jde spatne ladit a i kdyz jsem narazil na tu chybu uz nekolikrat, nejde mi poradne replikovat.

**Comment by jlibovicky** [comment]
Jednou jsem s tím strávil asi tři hodiny a pak jsem související issues zavřel. Nepovedlo se mi zreplikovat ani že by spotřeba po validacích rostla, ani na GPU ani CPU, natož že by se paměť vyčerpala. Důkladně jsem pročetl všechen kód, co by mohl způsobovat (bylo to krátce po zavedení TF manageru) a jsem si téměř jistý, že tam nic není. Navíc sám opici používám a nikdy jsem na to nenarazil, takže si myslím, že problém bude spíš někde vně opice.

**Comment by jindrahelcl** [comment]
#97 duplicate
