### ISSUE TITLE
Run as a web service

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#42]
Once we have the run.py script it should be extremely easy using flask (which is already a dependency). It will receive a dictionary of dataset series (the same way we have right now) as JSON and send back a JSON with outputs and some statistics.

**Comment by tomasmcz** [comment]
Do you really think we should do this before MTM? What will this be good for? I think that there are much more important think to do right now.

**Comment by jindrahelcl** [comment]
za mě rozhodně jo.

**Comment by jlibovicky** [comment]
Is's super easy and it will look very cool. Moreover, we need it for the subtitles chatbot ;-)

**Comment by tomasmcz** [comment]
OK. Then one of you should assign himself to this and have it done before MTM.
