### ISSUE TITLE
BPE preprocessor broken

### ISSUE THREAD

**Issue by bastings** [ufal/neuralmonkey#421]
In this commit https://github.com/ufal/neuralmonkey/commit/9940b5e24d2d2a2835f5bc304ba4b4d35a88cc65#diff-ecdb020f1284a8d818ccc1ad46e8304eL30 a hack was changed, and the change now prevents any word from being BPE encoded. (!!)

It basically skips over every word, because of this line:
```
if word:
    output.append(word)
    continue
```

I'm not sure why this hack is there, but right now nothing is being BPE'd.

Something like this would fix it, but again, it depends on why this hack was there.
```
if len(word) == 0:
    continue
```

**Comment by jindrahelcl** [comment]
Thanks for pointing this out! We have noticed some odd behavior with BPE but never figured out what's wrong. I've fixed it in master.

Btw. note that the graphs have changed significantly in 9fe23728e38b8d1377a0f7c100138eade3e3f562 so check it before updating. Older models won't behave as they should with the new version.
