### ISSUE TITLE
Why storing summary of regularizations

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#440]
Why do we store them? I tried to find an answer if the knowledge of L1/L2 regularization curve during training is actually useful, but didn't find anything.
And second, if the L1 or L2 is not used the summary shouldn't be created. Because it looks like the regularization is indeed used.
I can correct the second issue, but if there is no reason why to store L1 or L2, then I would just drop the summarization.

**Comment by jindrahelcl** [comment]
Tohle je odpověď hlavně na druhou část dotazu:

Protože se ti občas může stát, že uděláš někde něco špatně, a právě hodnota L2 a L1 ti ukážou, že to je špatně i doopravdy.

L1 a L2 neni regularizace, jsou to metriky, který jdou změřit na libovolnym modelu - s regularizací i bez. Pokud tam L1 ani L2 regularizaci nedáš a vidíš v tensorboardu, že ti to roste nade všechny rozumný meze, tak z toho můžeš usoudit, že bys je mohl použít.

Co se týče první části dotazu, nejsem si jistej, na co se ptáš. Ukládaj se proto, aby se z toho mohl udělat graf v čase.
