### ISSUE TITLE
exp-nm-mt/out-example-translation/variables.data does not exist

### ISSUE THREAD

**Issue by loveJasmine** [ufal/neuralmonkey#442]
per my understanding, 'variables.data'  shouldn't exist in a fresh running session,
so this is a bug ?

here are my workaround:

--- a/neuralmonkey/run.py
+++ b/neuralmonkey/run.py

@@ -69,12 +69,14 @@ def initialize_for_running(output_dir, tf_manager, variable_files) -> None:
         variable_files = [default_varfile]
 
     for vfile in variable_files:
          if not os.path.exists("{}.index".format(vfile)):
             log("Index file for var prefix {} does not exist".format(vfile),
                 color="red")
-            exit(1)
+            #exit(1)
 
-    tf_manager.restore(variable_files)
+    #tf_manager.restore(variable_files)
 
     log_print("")

**Comment by jindrahelcl** [comment]
The `neuralmonkey-run` script runs an __existing__ model on a given dataset. So it has to have the variable files. If you want to train a new model, use `neuralmonkey-train`.
