### ISSUE TITLE
how to disable the bpe in translation task?

### ISSUE THREAD

**Issue by loveJasmine** [ufal/neuralmonkey#443]
I just use it as chatbot

**Comment by jlibovicky** [comment]
You just remove the BPE preprocessors and postprocessor from the configuration file and use `from_dataset` function for creating a vocabulary.

However, I would consider using BPE even for a chat bot, budecause using BPE, you are able to copy OOV tokens, typcially named entities, from input to the output character by character. But it indeed depends on your data.

**Comment by jindrahelcl** [comment]
Look for example at `examples/language_model.ini` configuration, where the datasets are without BPE.

**Comment by loveJasmine** [comment]
it been a while since I have to move to something else
now, I am back:

here are my config file that don't use BPE for training a chatbot:

@jlibovicky @jindrahelcl 
is this look  right?  Thanks@@@

[train_data]
;class=dataset.load_dataset_from_files
class=vocabulary.from_dataset
s_source="../ve_tf1.0_py3/deepone/train_data/_train.q"
s_target="../ve_tf1.0_py3/deepone/train_data/_train.a"
;preprocessors=[]
;preprocessors=[("source", "source_bpe", <bpe_preprocess>), ("target", "target_bpe", <bpe_preprocess>)]

[val_data]
;class=dataset.load_dataset_from_files
class=vocabulary.from_dataset
s_source="../ve_tf1.0_py3/deepone/train_data/_val.q"
s_target="../ve_tf1.0_py3/deepone/train_data/_val.a"
;preprocessors=[]
;preprocessors=[("source", "source_bpe", <bpe_preprocess>), ("target", "target_bpe", <bpe_preprocess>)]


;[bpe_preprocess]
;class=processors.bpe.BPEPreprocessor
;merge_file="exp-nm-mt/data/bpe_merges"

;[bpe_postprocess]
;class=processors.bpe.BPEPostprocessor

[shared_vocabulary]
class=vocabulary.from_dataset
;datasets="exp-nm-mt/data/from_dataset.vob"

[source_vocabulary]
class=vocabulary.from_dataset
datasets=[<train_data>]
series_ids=["source"]
max_size=50000

[target_vocabulary]
class=vocabulary.from_dataset
datasets=[<train_data>]
series_ids=["target"]
max_size=50000

[encoder]
class=encoders.sentence_encoder.SentenceEncoder
name="sentence_encoder"
rnn_size=300
max_input_len=50
embedding_size=300
dropout_keep_prob=0.8
attention_type=decoding_function.Attention
data_id="source"
vocabulary=<source_vocabulary>

[decoder]
class=decoders.decoder.Decoder
name="decoder"
encoders=[<encoder>]
rnn_size=256
embedding_size=300
dropout_keep_prob=0.8
use_attention=True
data_id="target"
vocabulary=<target_vocabulary>
max_output_len=50

[trainer]
class=trainers.cross_entropy_trainer.CrossEntropyTrainer
decoders=[<decoder>]
l2_weight=1.0e-8

[runner]
class=runners.runner.GreedyRunner
decoder=<decoder>
output_series="series_named_greedy"
;postprocess=<bpe_postprocess>

[bleu]
class=evaluators.bleu.BLEUEvaluator
name="BLEU-4"

[tf_manager]
class=tf_manager.TensorFlowManager
num_threads=4
num_sessions=1
minimize_metric=False
save_n_best=3

[main]
name="machine translation"
output="exp-nm-mt/out-example-translation"
runners=[<runner>]
tf_manager=<tf_manager>
trainer=<trainer>
train_dataset=<train_data>
val_dataset=<val_data>
evaluation=[("series_named_greedy", "target", <bleu>), ("series_named_greedy", "target", evaluators.ter.TER)]
batch_size=80
runners_batch_size=256
epochs=10
validation_period=5000
logging_period=80

**Comment by loveJasmine** [comment]
it should be 

[train_data]
class=dataset.load_dataset_from_files
.....
[val_data]
class=dataset.load_dataset_from_files

**Comment by jindrahelcl** [comment]
the [shared_vocabulary] section is not complete and I think it could be thrown away

**Comment by loveJasmine** [comment]
@jindrahelcl 

by the way, what's about [shared_vocabulary]? any paper or tutorial on that!

**Comment by jindrahelcl** [comment]
If you refer to the name of the section, the names of the configuration sections are just arbitrary strings, used to reference the configuration objects.

If you refer to the possibility of sharing the vocabulary across encoders and decoders, one can use the shared vocabulary, if the language in a bunch of encoders or decoders is the same. E.g. in post-editing, when you have the same language on the input and on the output.

Your `[shared_vocabulary]` was never referenced in the configuration which means it is left out from building the model.

**Comment by loveJasmine** [comment]
got it! thanks! @jindrahelcl
