### ISSUE TITLE
Experiment identification

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#445]
Parametr 'name' v mainu se nikde nepouziva krom vypsani jednoho radku do logu (neustale jej tedy kopirujeme ze stejnych konfigu do jinych). Co kdyby se jako identifikace experimentu pouzivala jen output directory?

Kdyz delam experimenty, tak je to pro me outputdir docela dulezita informace. A jelikoz se doted nikde nepsala, tak jsem ji aspon pridal sem: commit c917177d. Ale myslim si, ze by mohla nahradit name, pokud s tim jmenem neplanujete neco vic. Co myslite?

**Comment by jindrahelcl** [comment]
Nevim čim myslíš identifikaci experimentu. Name experimentu nikdy k žádný identifikaci nesloužilo a ani asi nemělo. Jestli chceš, představ si, že se to místo `name` jmenuje `short_description`, ale měnit to nebudeme, páč by všechny konfiguráky přestaly fungovat.

K tomu commitu do mastera - nekomituj do mastera!!! Divim se, že to prošlo tim pylintem protože dáváš `else` za větev, která končí `exit(1)`. Tam by jednak žádnej `else` bejt neměl a jednak to patří jinam - nejlíp do `logging.py` na řádku 75. Takže to jdu revertnout a opravit.

**Comment by jindrahelcl** [comment]
pokračujme diskusi v #447
