### ISSUE TITLE
At least linear projection automatically reuses variables

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#458]
Following code will create only two set of variables, one for scope "first", second for scope "second". And none of the asserts will throw exception.

assert not tf.get_variable_scope().reuse
b = linear(a, 600, scope="first")
c = linear(b, 600, scope="second")
d = linear(c, 600, scope="second")
assert not tf.get_variable_scope().reuse

In case that 'c' and 'd' had a different size, it will break on an error similar to this:
Error while loading 'runners': Trying to share variable encoder/input_projection/LinearProjection/LinearProjection/weights, but specified shape (2048, 600) and found shape (2048, 2048).

The variable sharing will hapen no matter of the scope.reuse, which is quite a huge problem. It is either problem with contrib.fully_connected or some weird behavior of TF.

**Comment by jlibovicky** [comment]
Co s touhle issue? Já bych to rovnou zavřel, protože s tím nemůžeme nic dělat kromě toho, že se na to dáme pozor.

**Comment by tomkocmi** [comment]
Pockej tohle je zasadni problem ... tohle muze rozbijet celou opici, nikde nevis kde vsude tahle chyba nastava dokud se nezjisti, co za ni stoji, to nemusi byt pouze v linear.

**Comment by jindrahelcl** [comment]
jediná rozumná věc, co se s tim dá dělat, je udělat parametr `scope` funkce `linear` povinnej. Potom když to dáš dvakrát za sebe se stejnou scope, tak musíš zjistit, jestli to funguje tak, jak má.

**Comment by tomkocmi** [comment]
No me nejde uplne o tu funkci linear, ale bojim se toho jestli to neni nejake divne chovani TF a tim padem by to mohlo byt i u jinych casti (napriklad konvolucky)

**Comment by jindrahelcl** [comment]
closing as no longer relevant (linear -> tf layers dense)
