### ISSUE TITLE
Tensorboard all validations

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#460]
When using multiple validation dataset, plot scores of all of them to tensorboard.

**Comment by jindrahelcl** [comment]
Aha, původně jsem si myslel, že se jen netensorboardujou ty jiný než ta hlavní validace, podle který se ukládá. Ale je v tom bug. Takže to prosím @tomkocmi zkus opravit. Do tensorboardu se háže skóre ze všech validačních datasetů do jednoho grafu. Zejtra se kouknem na to, jak by to mělo bejt správně.

**Comment by tomkocmi** [comment]
me to na masteru opice kdyz jsem tuhle featuru pridaval funguje (nebo mozna nevim presne co myslis).

**Comment by tomkocmi** [comment]
pockat ty myslis jakoze kdyz mas ruzne validace na stejne uloze? typu prekladani novinovych clanku, titulku a treti validacni set jsou treba zakony, tak ze se to kresli do stejneho grafu?

**Comment by jindrahelcl** [comment]
přesně tak

**Comment by tomkocmi** [comment]
Tenhle mam nekde na seznamu todo listu, ale neprijde mi podstatny, soucasne vypisovani do jednoho grafu se da vyresit jinyma metrikama. Podle me by to chtelo prekopat celou learning utils nez tam pridavat dalsi podminky (ale nekoukal jsem jak by sel tenhle issue osetrit) ... Mimochodem da se nejak nastavit, aby se mi ukazoval tenhle issue v notifikaci abych na nej nezapomenul?

**Comment by jindrahelcl** [comment]
Nevim. Ale účinný je navyknout si jednou za čas zkontrolovat seznam issues na který jsi assignutej.

Proč bych měl dělat různý metriky když chci měřit pořád jednu? Mam troje validační data a jeden evaluátor, kterej funguje na všechny. Takže to má fungovat tak, že místo grafu pro každou data series a každou na ní spoštěnou metriku se mi to ještě rozduplikuje přes validační datasety. Neřikám, že tam nebude potřeba promyslet a předělat pár věcí, ale takhle to zkrátka nedělá, co má.
