### ISSUE TITLE
Using BaseAttention crashes somewhere else than it should

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#461]
When using BaseAttention by mistake (e.g. using imagenet encoder without specified attention type and the recurrent decoder with attention), the program crashes on `unexpected keyword argument 'input_weights'`.

It should either crash on the `NotImplementedError` or in the decoder that would check if there is attention defined on that object.

This issue is probably a wontfix, because of the upcoming refactor, but I'd keep it until the refactor is done or this issue is resolved.

**Comment by jlibovicky** [comment]
Will get solved by implementing #454.

**Comment by jlibovicky** [comment]
Will get resolved after merging #502.
