### ISSUE TITLE
In config combine parameter name and config name of something

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#464]
Neslo by v konfigu propojit name a jmeno objektu v []? Priklad

[embedded_input]
class=model.sequence.EmbeddedSequence
name="encoder_input_sequence"

by bylo:

[encoder_input_sequence]
class=model.sequence.EmbeddedSequence

+) kdyz objekt ma jmeno tak musi byt jedinecne, stejne tak informace v []
+) pro novacky to bude jednodussi na pochopeni na co se vlastne odkazuje
+) usetri to plno radku v configu
+) nebudou vznikat kolize v nazvech v konfigu (viz priklad nahode), kdy je mozne pojmenovat objekt jinak nez je jeho jmeno
-) nepujde pouzivat mezery (a asi i dalsi znaky) v nazvu
+-) vsechny objekty najednou budou pojmenovane (v tuto chvili vetsina objektu jmeno ma a tak to beru spise jako vyhodu kdy v budoucnu napriklad bude potreba pojmenovat nejaky objekt a on jiz bude mit sve jmeno, ted jsem u toho narazil u vocabularies, kde by se mi to hodilo)

Mozna nevidim nejaky zasadni problem, proc to tak neudelat, ale prislo by mi to lepsi a zvlast kdyz ted delame velky refaktor tak bych to do nej zahrnul (a klidne poctive to predelam i se vsema testama, examplama a tutorialama, protoze tohle by se mi tam hodne libilo)

**Comment by jindrahelcl** [comment]
O tom tady už taky probíhala diskuse, ale možná by to stálo za to přehodnotit. Obecné bude problém poznat, jestli dáná funkce parametr "name" přijímá nebo ne. Někdy to taky může být na škodu. Možná by tohle chování šlo omezit jen na instance třídy ModelPart, ale pak by byl problém s helper funkcema

**Comment by tomkocmi** [comment]
A kde by to mohlo vadit? Podle me kdyz by se vsem objektum pridal parameter name i kdyz by se nevyuzival tak to skodit nebude. Je vsak mozne ze nejakou velkou komplikaci prehlizim.

**Comment by jlibovicky** [comment]
Technicky by to problém nebyl. V Pythonu se jde celkem jednoduše podívat jaké má funkce argumenty a když mezi nimi bude `name`, tak se tam může plácnout název té sekce.

Spíš mi to přijde maličko proti duchu té konfigurace a jako uživatele by mě spíš znepokojovalo, že ten konfigurák, přestože se tváří hodně transparentně, tak mi dělá nějaké věci za zády. Ten jazyk je takový Python pro chudé. Každá sekce vlastně znamená:

```
<section_name> = <class>(arg1=..., arg2=...)
```

Takhle transparentně bez jakýchkoli zákeřností.

Určitě bych to nedělal úplně obecně. V principu je možné z toho konfiguráku volat jakoukoli funkci, Když bude mít náhodou argument `name` tak se může stát, že se v tom Pythonu probublá někam až bůhví kam a spadne to na nějaké kryptické chybové hlášce.

Takže pokud bychom něco takového dělali, tak bych to omezil jenom na potomky `ModelPart`. Na druhou stranu nevím, jestli benefit z toho, že by se někde ušetřilo pár řádek a občas ušetřila nějaká práce při debugování konfiguráku, překonal zmatení uživatele, který by si musel hlídat, že ne všechno, co vidí v dokumentaci, píše v konfiguráku a něco se mu děje samo pod rukama, protože konfigurák je chytřejší než uživatel.

**Comment by jindrahelcl** [comment]
Můžeš volat i funkce mimo neuralmonkey package. Těm přidat name nemůžeš.

Dne 15. 6. 2017 16:02 napsal uživatel "tomkocmi" <notifications@github.com>:

**Comment by tomkocmi** [comment]
Nemyslim, ze by to matlo uzivatele. Ale tak konfigurak muze byt jeste chytrejsi a prvne zkontrolovat jestli tam name nahodou neni definovany, pokud by byl, tak by se pouzil a pokud ne tak by se vyplnil podle jmena v []. Tim by se vyresilo i to, ze objekty ktere nechteji name by ho nemeli.

Na druhou stranu me by prislo celkem v pohode, aby vsechny objekty ktere mohou byt inicializovane v configu meli moznost mit parametr name. Treba ted by se mi hodil u vocabularies, abych je nemusel ukladat podle indexu v pridruzene embeddedsequence (viz #465)

**Comment by jindrahelcl** [comment]
Podle mě není vůbec na škodu, že se tam name píše explicitně. Pohodlí
uživatelů je sice důležitý, ale zdaleka ne tak, abychom si mohli dovolit
zabývat se tím teď, když jsou potřeba dělat jiný věci.

Dne 15. 6. 2017 16:35 napsal uživatel "tomkocmi" <notifications@github.com>:

**Comment by tomkocmi** [comment]
Proto jsem se nabidnul, ze to udelam. Kazdopadne me by prislo opravdu dobre, aby kazdy objekt mel name. Viz ty vocabularies a nikdy nevime co dalsiho bude potrebovat name (a kdyz pridame name parametr tak zrusime zpetnou kompatibilitu konfiguraku, takhle by to meli vsechny i kdyz by to nepotrebovali)

**Comment by jindrahelcl** [comment]
Je kravina, aby každá věc měla name. Zapomínáš, že sekce konfigurace neodpovídají nutně objektům. Sekce konfigurace odpovídají volání funkce, tak jak to píše Jindra. Chtít, aby každá funkce volatelná z konfiguráku měla name je prostě špatně. Pokud chceš přidat jméno ke slovníku, tak přidej jméno ke slovníku jako nepovinnej parametr.

Pokud jde o slučování názvu sekce s parametrem `name`, je potřeba rozmyslet, jestli neexistuje případ, kdy chceme, aby dva objekty vytvořené z konfigurace měli stejné jméno. Třeba kvůli sdílení variable scopu. To bychom si tímhle krokem znemožnili.

Následuje nekonstruktivní poznámka:
Tím "jsou potřeba dělat jiný věci" jsem nemyslel, že já teď dělám něco jinýho, ale že všichni, včetně tebe, bychom měli radši dělat něco jinýho. Třeba některou z issues, který jsi otevřel, jako #458. Taky bys mohl řešit bugy, který jsi zavedl svýma změnama, například #460. Anebo se jen kouknout na seznam všech bugů a vyřešit nějaký z nich.
