### ISSUE TITLE
Sequence labeler as another decoder

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#47]

**Comment by jindrahelcl** [comment]
enhancement je podmnožina feature podle mě. :-) to by to pak mohlo bejt u všeho

**Comment by jlibovicky** [comment]
Is this in the `mtm16` branch?

**Comment by jindrahelcl** [comment]
Yes

**Comment by jlibovicky** [comment]
So, shall we close this?

**Comment by jindrahelcl** [comment]
My policy so far on closing issues was to close them after the branches are merged to master. I am not enforcing this, though.. :)

**Comment by jlibovicky** [comment]
Solved with #100.
