### ISSUE TITLE
[help]I need a setting suggestion for my task  

### ISSUE THREAD

**Issue by loveJasmine** [ufal/neuralmonkey#474]
Suppose I have a about 10 millions QA pairs as training dataset, and about 50K pairs as validation dataset

what an efficient and reasonable way to set:
batch_size=
runners_batch_size=
epochs=
validation_period=
logging_period=
***************************************
Now I am working on:

batch_size=100
runners_batch_size=128
epochs=20
validation_period=2000
logging_period=80

On this setting, it consumes about 2M GPU memory.
It seems too slowly even on a M40 GPU,
after 12 hours:
^[[33m2017-06-20 09:37:34^[[0m: Epoch 1/20  Instances 3277791  series_named_greedy/BLEU-4: 2.105    series_named_greedy/runtime_xent: 0.06941    series_named_greedy/train_xent: 0.03682^[[1m    series_named_greedy/TER: 1.041^[[0m

Now my another setting is:
batch_size=512
runners_batch_size=2048
epochs=10
validation_period=50000
logging_period=800

it takes 8M GPU memory, look the M40 are more efficient used without memory overload

**Comment by tomkocmi** [comment]
We usually set batch size and runners batch size the same. The value should be the biggest you can fit to the GPU. About logging period you can set the time how offen you want to validate for example:

logging_period="5m"
validation_period="60m"
