### ISSUE TITLE
training failed on self-critical training

### ISSUE THREAD

**Issue by loveJasmine** [ufal/neuralmonkey#479]
decoder/attention_decoder/LinearProjection/LinearProjection/biases:0            [250]                      250
decoder/attention_decoder/OrthoGRUCell/gates/weights:0                          [506, 512]              259072
decoder/attention_decoder/OrthoGRUCell/gates/biases:0                           [512]                      512
decoder/attention_decoder/OrthoGRUCell/candidate/weights:0                      [506, 256]              129536
decoder/attention_decoder/OrthoGRUCell/candidate/biases:0                       [256]                      256
decoder/attention_decoder/attention_sentence_encoder/Attention/weights:0        [256, 600]              153600
decoder/attention_decoder/attention_sentence_encoder/Attention/biases:0         [600]                      600
decoder/attention_decoder/AttnOutputProjection/AttnOutputProjection/weights:0   [856, 256]              219136
decoder/attention_decoder/AttnOutputProjection/AttnOutputProjection/biases:0    [256]                      256

^[[33m2017-06-23 13:33:45^[[0m: Total number of all parameters: 7417203
^[[33m2017-06-23 13:33:52^[[0m: Initializing TensorBoard summary writer.
^[[33m2017-06-23 13:34:01^[[0m: TensorBoard writer initialized.
^[[33m2017-06-23 13:34:01^[[0m: Starting training

^[[31m2017-06-23 13:34:01^[[0m: Epoch 1 starts
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: trainer/gr_decoder/state_to_word_b_0
         [[Node: trainer/gr_decoder/state_to_word_b_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](trainer/gr_decoder/state_to_word_b_0/tag, trainer/clip_by_norm_13/_945)]]

Caused by op 'trainer/gr_decoder/state_to_word_b_0', defined at:
  File "bin/neuralmonkey-train", line 6, in <module>
    main()
  File "/home/yike.yk/neuralmonkey/bin/neuralmonkey/train.py", line 172, in main
    cfg.build_model(warn_unused=True)
  File "/home/yike.yk/neuralmonkey/bin/neuralmonkey/config/configuration.py", line 86, in build_model
    model = build_config(self.config_dict, self.ignored, warn_unused)
  File "/home/yike.yk/neuralmonkey/bin/neuralmonkey/config/builder.py", line 198, in build_config
    value, config_dicts, existing_objects, 0)
  File "/home/yike.yk/neuralmonkey/bin/neuralmonkey/config/builder.py", line 109, in build_object
    obj = instantiate_class(value[7:], all_dicts, existing_objects, depth)
  File "/home/yike.yk/neuralmonkey/bin/neuralmonkey/config/builder.py", line 165, in instantiate_class
    obj = clazz(*bounded_params.args, **bounded_params.kwargs)
  File "/home/yike.yk/neuralmonkey/bin/neuralmonkey/trainers/generic_trainer.py", line 98, in __init__
    grad, collections=["summary_gradients"])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/summary/summary.py", line 203, in histogram
    tag=scope.rstrip('/'), values=values, name=scope)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 139, in _histogram_summary
    name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: trainer/gr_decoder/state_to_word_b_0
         [[Node: trainer/gr_decoder/state_to_word_b_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](trainer/gr_decoder/state_to_word_b_0/tag, trainer/clip_by_norm_13/_945)]]

                                                                                                                                                                                        294,0-1       Bot

^[[1m^[[33m                                 Variable name                                         Shape           Size
^[[0m
sentence_encoder/input_projection/word_embeddings:0                             [6004, 300]            1801200
sentence_encoder/bidirectional_rnn/fw/OrthoGRUCell/gates/weights:0              [600, 600]              360000
sentence_encoder/bidirectional_rnn/fw/OrthoGRUCell/gates/biases:0               [600]                      600
sentence_encoder/bidirectional_rnn/fw/OrthoGRUCell/candidate/weights:0          [600, 300]              180000
sentence_encoder/bidirectional_rnn/fw/OrthoGRUCell/candidate/biases:0           [300]                      300
sentence_encoder/bidirectional_rnn/bw/OrthoGRUCell/gates/weights:0              [600, 600]              360000
sentence_encoder/bidirectional_rnn/bw/OrthoGRUCell/gates/biases:0               [600]                      600
sentence_encoder/bidirectional_rnn/bw/OrthoGRUCell/candidate/weights:0          [600, 300]              180000
sentence_encoder/bidirectional_rnn/bw/OrthoGRUCell/candidate/biases:0           [300]                      300
decoder/initial_state/encoders_projection/weights:0                             [600, 256]              153600
decoder/initial_state/encoders_projection/biases:0                              [256]                      256
decoder/word_embeddings:0                                                       [6004, 250]            1501000
decoder/state_to_word_W:0                                                       [256, 6004]            1537024
decoder/state_to_word_b:0                                                       [6004]                    6004
decoder/attention_sentence_encoder/AttnW:0                                      [1, 1, 600, 600]        360000
decoder/attention_sentence_encoder/AttnV:0                                      [600]                      600
decoder/attention_sentence_encoder/AttnV_b:0                                    []                           1
decoder/attention_decoder/LinearProjection/LinearProjection/weights:0           [850, 250]              212500
decoder/attention_decoder/LinearProjection/LinearProjection/biases:0            [250]                      250
decoder/attention_decoder/OrthoGRUCell/gates/weights:0                          [506, 512]              259072
decoder/attention_decoder/OrthoGRUCell/gates/biases:0                           [512]                      512
decoder/attention_decoder/OrthoGRUCell/candidate/weights:0                      [506, 256]              129536
decoder/attention_decoder/OrthoGRUCell/candidate/biases:0                       [256]                      256
decoder/attention_decoder/attention_sentence_encoder/Attention/weights:0        [256, 600]              153600
decoder/attention_decoder/attention_sentence_encoder/Attention/biases:0         [600]                      600
decoder/attention_decoder/AttnOutputProjection/AttnOutputProjection/weights:0   [856, 256]              219136
decoder/attention_decoder/AttnOutputProjection/AttnOutputProjection/biases:0    [256]                      256

^[[33m2017-06-23 13:33:45^[[0m: Total number of all parameters: 7417203
^[[33m2017-06-23 13:33:52^[[0m: Initializing TensorBoard summary writer.
^[[33m2017-06-23 13:34:01^[[0m: TensorBoard writer initialized.
^[[33m2017-06-23 13:34:01^[[0m: Starting training

**Comment by jindrahelcl** [comment]
Can you provide the contents of `git_commit` and `git_diff`files from the experiment directory? (or the latest git hash as printed by `git log`)

**Comment by loveJasmine** [comment]
$git log
commit 52c13bd4cc9c9df4114b64b459c8550872770d6c
Merge: 8326820 0bf00be
Author: Jindra Helcl <jindra.helcl@gmail.com>
Date:   Tue Jun 13 13:40:02 2017 +0200

    Merge pull request #456 from ufal/encoders_refactor

    Encoders refactor

commit 0bf00be9eccf534560184175918e19b29bfc111c
Author: Jindra Helcl <helcl@ufal.mff.cuni.cz>
Date:   Tue Jun 6 13:23:32 2017 +0200

    update model part unit test to work with lazily initialized encoder

commit 9a7e6c95bc3433b91064f9fe700c575f2e7a51cb
Author: Jindra Helcl <helcl@ufal.mff.cuni.cz>
Date:   Tue Jun 6 11:31:44 2017 +0200

    fixing unit tests

**Comment by jindrahelcl** [comment]
I'm not sure why you encountered that error. Try to checkout a previous version, 824b9c9 should work fine.
If that won't work, please post your INI file so we could take a look at it..

**Comment by loveJasmine** [comment]
even under https://github.com/ufal/neuralmonkey/commit/824b9c9a92b5f54941cbc3b433f798e5ddb91b78
it got the same error

my ini as:

[train_data]
class=dataset.load_dataset_from_files
s_source="../andy_data/tr.q"
s_target="../andy_data/tr.a"

lazy=True

[val_data]
class=dataset.load_dataset_from_files
s_source="../andy_data/va.q"
s_target="../andy_data/va.a"

[shared_vocabulary]
class=vocabulary.from_dataset
max_size=6000

[source_vocabulary]
class=vocabulary.from_dataset
datasets=[<train_data>]
series_ids=["source"]
max_size=7000

[target_vocabulary]
class=vocabulary.from_dataset
datasets=[<train_data>]
series_ids=["target"]
max_size=8000

[encoder]
class=encoders.sentence_encoder.SentenceEncoder
name="sentence_encoder"
rnn_size=300
max_input_len=50
embedding_size=300
dropout_keep_prob=0.8
attention_type=decoding_function.Attention
data_id="source"
vocabulary=<source_vocabulary>

[decoder]
class=decoders.decoder.Decoder
name="decoder"
encoders=[<encoder>]
rnn_size=256
embedding_size=300
dropout_keep_prob=0.8
use_attention=True
data_id="target"
vocabulary=<target_vocabulary>
max_output_len=50
[self_critical]
class=trainers.self_critical_objective.self_critical_objective
decoder=<decoder>
reward_function=trainers.self_critical_objective.sentence_bleu
weight=0.5

[cross_entropy]
class=trainers.cross_entropy_trainer.xent_objective
decoder=<decoder>
weight=0.5

[trainer]
class=trainers.generic_trainer.GenericTrainer
objectives=[<cross_entropy>,<self_critical>]
l2_weight=1.0e-8
clip_norm=1.0

[runner]
class=runners.runner.GreedyRunner
decoder=<decoder>
output_series="series_named_greedy"

[bleu]
class=evaluators.bleu.BLEUEvaluator
name="BLEU-4"

[tf_manager]
class=tf_manager.TensorFlowManager
num_threads=4
num_sessions=1
minimize_metric=False
save_n_best=3

[main]
name="deepone with self-critical training"
output="deepone_out-self-critical"
runners=[<runner>]
tf_manager=<tf_manager>
trainer=<trainer>
train_dataset=<train_data>
val_dataset=<val_data>
evaluation=[("series_named_greedy", "target", <bleu>), ("series_named_greedy", "target", evaluators.ter.TER)]
batch_size=108
runners_batch_size=128
epochs=12

validation_period=3215
random_seed=1234
logging_period=77

**Comment by loveJasmine** [comment]
it passed if I change the ini as the following, but I am not sure which one caused the error.


[train_data]
class=dataset.load_dataset_from_files
s_source="../andy_data970201/tr.q"
s_target="../andy_data970201/tr.a"

[val_data]
class=dataset.load_dataset_from_files
s_source="../andy_data970201/va.q"
s_target="../andy_data970201/va.a"

[shared_vocabulary]
class=vocabulary.from_dataset
max_size=8000

[source_vocabulary]
class=vocabulary.from_dataset
datasets=[<train_data>]
series_ids=["source"]
max_size=8000

[target_vocabulary]
class=vocabulary.from_dataset
datasets=[<train_data>]
series_ids=["target"]
max_size=8000

[encoder]
class=encoders.sentence_encoder.SentenceEncoder
name="sentence_encoder"
rnn_size=300
max_input_len=50
embedding_size=300
dropout_keep_prob=0.8
attention_type=decoding_function.Attention
data_id="source"
vocabulary=<source_vocabulary>

[decoder]
class=decoders.decoder.Decoder
name="decoder"
encoders=[<encoder>]
rnn_size=256
embedding_size=300
dropout_keep_prob=0.8
use_attention=True
data_id="target"
vocabulary=<target_vocabulary>
max_output_len=50
[self_critical]
class=trainers.self_critical_objective.self_critical_objective
decoder=<decoder>
reward_function=trainers.self_critical_objective.sentence_bleu
weight=0.5

[cross_entropy]
class=trainers.cross_entropy_trainer.xent_objective
decoder=<decoder>
weight=0.5

[trainer]
class=trainers.generic_trainer.GenericTrainer
objectives=[<cross_entropy>,<self_critical>]
l2_weight=1.0e-8
clip_norm=1.0

[runner]
class=runners.runner.GreedyRunner
decoder=<decoder>
output_series="series_named_greedy"

[bleu]
class=evaluators.bleu.BLEUEvaluator
name="BLEU-4"

[tf_manager]
class=tf_manager.TensorFlowManager
num_threads=4
num_sessions=1
minimize_metric=False
save_n_best=3

[main]
name="deepone with self-critical training"
output="deepone_out-self-critical"
runners=[<runner>]
tf_manager=<tf_manager>
trainer=<trainer>
train_dataset=<train_data>
val_dataset=<val_data>
evaluation=[("series_named_greedy", "target", <bleu>), ("series_named_greedy", "target", evaluators.ter.TER)]
batch_size=108
runners_batch_size=128
epochs=12

validation_period=3215
random_seed=1234
logging_period=77

**Comment by loveJasmine** [comment]
maybe this item
lazy=True
is the root cause

**Comment by jindrahelcl** [comment]
was the `lazy=True` the only change?

**Comment by loveJasmine** [comment]
that's not the only changes, 
the other is that I set different max_size in source_vocabulary & target_vocabulary

**Comment by loveJasmine** [comment]
I am sure the root cause is the 
'lazy=True'

**Comment by jindrahelcl** [comment]
ok, thanks. I will open an issue for that.
