### ISSUE TITLE
how to set  variables=XXX on the evaluation ini setting for translation-like/chatbot task?

### ISSUE THREAD

**Issue by loveJasmine** [ufal/neuralmonkey#480]
I guess the doc are missed this item
variables=XXXX

suppose I had training done WITH a train ini like:
[main]
name="done"
output="done_out-andy_data970201"

 then I build an ini file to evaluation like:
[main]
test_datasets=[<eval_data>]
variables=XXXXXX----- how to set???

[eval_data]
class=dataset.load_dataset_from_files
s_source="../andy_data970201/te.q"
s_series_named_greedy_out="done_out-andy_data970201/te.a.out"

the content of done_out-andy_data970201 
total 426676
 users        57 Jun 20 22:21 args                                            
 users       183 Jun 22 21:55 checkpoint                                      
 users  62343360 Jun 23 10:04 events.out.tfevents.1497968759.e27k01378.su18   
 users      1740 Jun 20 22:21 experiment.ini                                  
 users    218139 Jun 23 10:01 experiment.log                                  
 users        41 Jun 20 22:21 git_commit                                      
 users     17582 Jun 20 22:21 git_diff                                        
 users      1739 Jun 20 22:21 original.ini                                    
 users 114328248 Jun 21 05:13 variables.data.0.data-00000-of-00001            
 users      3430 Jun 21 05:13 variables.data.0.index                          
 users  10431017 Jun 21 05:13 variables.data.0.meta                           
 users 114328248 Jun 21 17:05 variables.data.1.data-00000-of-00001            
 users      3430 Jun 21 17:05 variables.data.1.index                          
 users  10431017 Jun 21 17:05 variables.data.1.meta                           
 users 114328248 Jun 22 21:55 variables.data.2.data-00000-of-00001            
 users      3430 Jun 22 21:55 variables.data.2.index                          
 users  10431017 Jun 22 21:55 variables.data.2.meta                           
 users        22 Jun 21 05:13 variables.data.best -> variables.data.0.index   

variables=["variables.data"]

**Comment by jindrahelcl** [comment]
the variables should be the common prefix of the three files describing a single variable set.

In this example, you have three saved variable sets (the ones with suffixes 0, 1, and 2). Each of them has three files (`*.index`, `*.meta`, and `*.data-00000-of-00001`). The file `variables.data.best` points to the index file of best set (this will be changed when #478 is merged). In your case, the link points to the variable file set with index 0. So your variables should be this:

```
variables = ["variables.data.0"]
```

There is a limited ensemble support (and I don't know whether it can be used right now), which you can use by providing all the three variable sets:


```
variables = ["variables.data.0", "variables.data.1", "variables.data.2"]
```

**Comment by loveJasmine** [comment]
It make some progress, like

2017-06-23 20:36:40: Model built.

2017-06-23 20:36:40: Loading variables from variables.data.0
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for variables.data.0
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for variables.data.0
W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for variables.data.0


I did some changes on source code(add/del some 'print') after training

**Comment by loveJasmine** [comment]
I got it.

it must specify the path like:
variables=["done_out-andy_data970201/variables.data.0"]
