### ISSUE TITLE
about coding style & format

### ISSUE THREAD

**Issue by loveJasmine** [ufal/neuralmonkey#483]
why we use the type explanation code style like:

    def __init__(self,
                 mlp_input: tf.Tensor,
                 layer_configuration: List[int],
                 dropout_keep_prob: float,
                 output_size: int,
                 train_mode: tf.Tensor,

I looks a lot of 'red wave underline' in pycharm

**Comment by jindrahelcl** [comment]
Set your Python interpreter to 3.5 and the red line goes away

Dne 27. 6. 2017 8:46 napsal uživatel "yk_data" <notifications@github.com>:
