### ISSUE TITLE
Lazy dataset should have a config method

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#49]
Lazy dataset should have a similar building function as the standard (in-memory) dataset in the `config` module. Moreover, its `__init__` method should be refactored the same way.

**Comment by jindrahelcl** [comment]
#85

**Comment by jlibovicky** [comment]
Is this solved?

**Comment by jindrahelcl** [comment]
`neuralmonkey.dataset.load_dataset_from_files` got the `lazy` boolean parameter. So yes. The config helper method is still the same - `config.utils.dataset_from_files`
