### ISSUE TITLE
Tensorboard shows an empty graph section

### ISSUE THREAD

**Issue by StoyanVenDimitrov** [ufal/neuralmonkey#495]
Hi,
I want to see the graph with my new mrt_trainer. I see the graph using the Xent trainer, but when I switch to mine trainer, the section remains empty, although no "No graph definition files were found." message shows up. The graph exists though, meaning I know it computes loss, gradients etc. The difference to the Xent is, that even though I have num_of_sessions=1, I have two iterations for session_results in the execute(). Could that require some adjustments in order to visualize the graph?

Best,
Stoyan

**Comment by jindrahelcl** [comment]
Hi,

I suspect this might be a bug, but I don't see how. @jlibovicky could you take a look at that?

Jindra

**Comment by jlibovicky** [comment]
Hi, I don't think these things are related. The graph needs to be built before anything is executed, it has nothing in common in the way the particular nodes of the graph are later executed. When you look into the experiment directory, is the graph definition there?

**Comment by StoyanVenDimitrov** [comment]
Hi,
no, I don't see it. But I also don't see it for the xent model. This is what I have in the directory, the same is for both models:
![capture](https://user-images.githubusercontent.com/19803516/28415736-4705f6c4-6d51-11e7-9bdd-fffc39418bc6.JPG)

**Comment by jlibovicky** [comment]
It should be in the events file. It's a binary file, but you can view the strings inside e.g. using the [`strings`](http://www.linfo.org/strings.html) command and have a look if you see names of the graph nodes. Another clue could the size of the file, if its significantly smaller than the other one, it may mean the graph definition inside is missing.

**Comment by StoyanVenDimitrov** [comment]
Hi, 
the mrt-model file is actually 3 times bigger then for the xent-model...
I was not sure what the lines mean, but I think what I see among other things are names in the defined name scopes and such lines are presented in both files. I'll upload a screenshot again.
![mrt](https://user-images.githubusercontent.com/19803516/28418015-80ff0aec-6d5a-11e7-9a2d-c10813effd4a.JPG)

**Comment by jlibovicky** [comment]
Then the graph is definitely in the events file. In that case, I would suspect it is a TensorBoard issue due to the graph size.
