### ISSUE TITLE
Chrf neresi division by zero

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#496]
chr_p = chr_p_matched / chr_p_all

**Comment by jindrahelcl** [comment]
Tak tam dej podmínku, aby když je obojí nula, že je to celý nula. Nebo má smysl dělat něco jinýho?

**Comment by tomkocmi** [comment]
Co tam pridat malinkou konstantu?

**Comment by jindrahelcl** [comment]
klidně.

**Comment by jlibovicky** [comment]
Teoreticky by to mělo být 1, protože je to extrém precission/recall křivky, kdy je precision 1 a recall je 0.

**Comment by varisd** [comment]
Closed in commit d9707f712d4c31aaaa3092c5d32d0bccd69b138b
