### ISSUE TITLE
Beamsearch does not work if no ground truth is provided

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#5]
Implementation of beam search relies on placeholders which are fed fed nothing if the ground thruth sequence is not provided.

**Comment by tomasmcz** [comment]
@jlibovicky: Does beamsearch ever work? I will deal with this, but I'd like to fix my test script first. Is it possible to read a configuration and set a random seed before the computation is graph is build?

**Comment by jlibovicky** [comment]
@tomasmcz It does and it give 2 additional BLEU points in the MMMT task. The configuration is loaded in two phases. First it just creates a dictionary of the values and in the second phase all the functions are called (which includes building the graph).

**Comment by jlibovicky** [comment]
No relevant since PR #151.
