### ISSUE TITLE
decoder.py: Provide shape invariants in sampling mode

### ISSUE THREAD

**Issue by StoyanVenDimitrov** [ufal/neuralmonkey#513]
Hi,
I tried out the new decoder in sampling mode, but got this: `Failed to build model: Error while loading 'runners': The shape for decoder/while/Merge_1:0 is not an invariant for the loop. It enters the loop with shape (?,), but has shape (?, 1) after one iteration. Provide shape invariants using either the 'shape_invariants' argument of tf.while_loop or set_shape() on the loop variables.
`  Any idea on how to handle it right? Thanks!

Best,
Stoyan

**Comment by jlibovicky** [comment]
Try reshaping the sample to `[-1]` here: https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/decoders/decoder.py#L466
