### ISSUE TITLE
Backward compatibility of the decoder

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#518]
As I wrote in #516, decoder should still allow a way of using only linear projection. Please consider this an urgent issue - must be done prior merging #517.

@tomkocmi if you don't want to do this, please assign @varisd as this is essential for us to be able to test ensembling beam search with old models and new codebase.

**Comment by tomkocmi** [comment]
I cannot do it right now if it is that urgent. So I am assigning Dusan as you said.

**Comment by jlibovicky** [comment]
Done in #532.
