### ISSUE TITLE
Default variable file resolution does not work when sharing experiment directory.

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#542]
See #541

**Comment by jindrahelcl** [comment]
@tomasmcz odassignni se jestli to nechces delat...

**Comment by tomasmcz** [comment]
chci, nestíhám, snad brzy budu mít míň hořících povinností a dostanu se k tomu

**Comment by jindrahelcl** [comment]
@cifkao je tohle hotový tim tvým pull requestem? (#613)

**Comment by cifkao** [comment]
Vypadá to, že to je ono.

**Comment by cifkao** [comment]
Fixed by #613.
