### ISSUE TITLE
Why don't we use pydocstyle?

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#543]
There is the `tests/pydocstyle_run.sh` - why don't we use it? (Apart from the fact that it outputs around 1800 lines of errors in the docstrings, obviously.. :-) )

Should someone start with fixing those? (i.e. making documentation)

**Comment by jindrahelcl** [comment]
@tomasmcz you could at least docstring the parts of the code that are yours..

**Comment by varisd** [comment]
Another possibly related question is, why don't we use tests/pycodestyle.sh?
I guess it is because of redundancy, because pylint does similar stuff as pycodestyle, am I right?

**Comment by varisd** [comment]
This should be part of tests. The actual number of errors is ~900. I am currently working out, which error messages can be turned off (that put too much restriction on the documentation style).

It is quite a lot of work for one person to fix all of these, so everyone should go through their contributions a resolve them personally after I update the ignore list.

**Comment by jindrahelcl** [comment]
Closed by #552
