### ISSUE TITLE
Should we freeze dependencies?

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#55]
If we do not have concrete versions of dependencies in requirements, things like error in #54 might be happening from time to time. On the other hand, if we freeze the dependencies, we should check for updates from time to time, which means more work. I'm leaning towards automatic updates and  letting the build fail from time to time. We test things fairly regularly now, so we should be able to catch and repair breaking changes. What do you think?

**Comment by jindrahelcl** [comment]
I am for updated dependencies. But that does not mean some of them shouldn't be freezed - like we did in the case of the newest nltk 3.2.1 which crashed when computing BLEU, when we replaced it with 3.2.0.. We should design performance tests for this (train on a very small data and evaluate and keep the scores from these tests). Maybe it's also meaningful to measure running time of the test.

**Comment by jlibovicky** [comment]
Keep dependencies updated. And never use NLTK again :-)

**Comment by tomasmcz** [comment]
OK.

To keep meaningful test scores, we would need to fix random seeds (I don't think it works at the moment). I don't think there is a reasonable way to reliably measure meaningful running time.

**Comment by jindrahelcl** [comment]
It does not have to be reliable - if the timing is suspicious, you can re-run the test and if the timing is still bad, you can investigate.
