### ISSUE TITLE
Replace reduce_mean with reduce_sum?

### ISSUE THREAD

**Issue by tomkocmi** [ufal/neuralmonkey#551]
V RNN decoderu na radku 321 je reduce_mean, bavili jsme se o tom v Dansku, ze by tam mohl byt reduce_sum a tak jsem to otestoval a chovalo se to temer stejne (vysledny rozdil byl v setinach BLEU). Navrhoval bych tedy zamenit tuto funkci, co myslite?

**Comment by tomasmcz** [comment]
Neznamená to, že jinak velké batche (například poslední batch) budou mít jinou váhu?

**Comment by jindrahelcl** [comment]
Znamená. Pro konstantně velký batche N je to ekvivalentní volbě learning rate N-krát větší(/menší). Jelikož to na trénování nemá vliv, neměnil bych to.
