### ISSUE TITLE
Problems with Pyter when running unit tests

### ISSUE THREAD

**Issue by gwenniger** [ufal/neuralmonkey#553]
I am new to neural monkey, but when I installed it today I ran into 
several issues with the unit tests related to pyter.

After installation, running
./tests/unit-tests_run.sh

Causes syntax errors in the files  pyter/__init__.py 
and  pyter/util.py. 
These errors are caused by the syntax of python, that has changed in newer versions, 
and I was able to fix them by adapting the code, replacing

"iter.zip"  (=> zip)
(in pyter/__init__.py )
https://stackoverflow.com/questions/32261698/my-idle-does-not-recognize-itertools-izip-as-a-function

and the regular expression
"ru"     (=>"r")
(gebruikt in pyter/util.py )
https://stackoverflow.com/questions/26063899/python-version-3-4-does-not-support-a-ur-prefix

I think it would be good if these errors could be fixed, since they directly appear in the unit tests with 
my python version (Python 3.5.2)
but I think the tricky part is that the correct 
command depends on the python version, so ideally that should be checked in the fixed code,
so that there are different cases depending on the python version.

**Comment by jlibovicky** [comment]
Pyter's version for Python 3 is not yet in pypi, so unfortunately you need to install exactly the version that is in [`requirements.txt`](https://github.com/ufal/neuralmonkey/blob/master/requirements.txt#L7):

```bash
pip install git+https://github.com/aflc/pyter@857a1552443f139a3
```
