### ISSUE TITLE
Vocabulary includes words with unicode whitespace but does not load them

### ISSUE THREAD

**Issue by bastings** [ufal/neuralmonkey#555]
Currently (tested on 0.2.2), if unicode whitespace "\xa0" is in a document, it is included in the vocabulary. If you save this to disk as a wordlist, and then load it again for test time (with `neuralmonkey-run`, these words are not part of the loaded vocabulary, and it will result in an error, since the loaded vocabulary size does not match the size of the word embedding matrix.

A fix could be to change the `from_wordlist` function to strip only the end-of-line symbol from the line, and nothing else:
Line 77 in `vocabulary.py` would become:

```python
line = line.strip('\n')
```

This fixes the issue. Alternatively (or additionally), we might not want to include such items in the vocabulary in the first place.

**Comment by varisd** [comment]
Sounds reasonable. User himself should take care of the trailing whitespaces during data preparation.

Please create a pull request with a suggested fix so that we can close this issue.

**Comment by jindrahelcl** [comment]
For small edits like this, you can go to the file directly on github and edit it there. After the edits are done, it lets you choose between a commit to master or opening a pull request.

https://github.com/ufal/neuralmonkey/blob/f1dc50b3397a957918e7e3845d9dc6a37f196e29/neuralmonkey/vocabulary.py#L83

**Comment by varisd** [comment]
resolved by PR #569
