### ISSUE TITLE
Sequence and TemporalStateful should be the same interface

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#556]
Right now, there are two abstract classes `Sequence` for something with is an input sequence and `TemporalStateful` which generates as a result of a computation. This in fact should be the same inerface, such that we can easily stack model parts.

**Comment by cifkao** [comment]
Is the following too audacious?

- Keep `Sequence` and get rid of `TemporalStateful`.
- A recurrent encoder will have a property called `state_sequence` (or `output_sequence` or whatever) of type `Sequence`, which will replace the properties `temporal_states` and `temporal_length`.
- Make it possible to reference objects' attributes in the config file. Then we can write, for instance:
```ini
[encoder1]
input_sequence=<embeddings>

[encoder2]
input_sequence=<encoder1.state_sequence>

[decoder]
input_sequence=<encoder2.state_sequence>
```

**Comment by jindrahelcl** [comment]
I'd do it the other way - throw away the sequence class and keep *statefuls. First, there is the `SpatialStateful` interface for 2D state matrices. Second, `Sequence` is a model part, which is not a very intuitive thing. Third, `Sequence` is now only used in the embedding-encoder relationship, whereas `TemporalStateful` is newer and used on more places. 

So, for example for embeddings which are done in the `EmbeddedSequence` class, I would create a class `Embedding` which would be a `TemporalStateful` instance of `ModelPart`, and consume a data series and embedding size.

However, we should find a commonly accepted solution and I am open to have my mind changed..

As for the object attribute references in the config, I'm very much in favor for doing it.

**Comment by varisd** [comment]
Please also check somewhat related issue #575 (when deciding where to apply dropout).

**Comment by jindrahelcl** [comment]
I created issue for the referencing (#576)

**Comment by jlibovicky** [comment]
This is done, but I can find the PR.
