### ISSUE TITLE
Report corrupted line number during vocabulary loading

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#567]
When loading vocabulary from wordlist fails on malformed line, it should say that clearly and provide the line number (and filename).

@tomkocmi or @varisd, please do this ASAP as it's a very small edit, otherwise this issue will stuck here until the end of time.

Code reference:
https://github.com/StoyanVenDimitrov/neuralmonkey/blob/mrt_annealing/neuralmonkey/vocabulary.py#L82

**Comment by varisd** [comment]
Fixed in 332268a0fec849b55958edc3b778010bb9cd5e54
