### ISSUE TITLE
Logbook shows no expirements on tests

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#57]
When I run `bin/neuralmonkey-logbook --port 5050 --logdir tests/tmp-test-output`, I get a screen with "click experiment on the left", but there is no experiment on the left. Why is that?

**Comment by jindrahelcl** [comment]
The `logdir` should be the parent `tests` directory since it is designed to work with multiple experiments,  each of them having their own dir.

**Comment by jindrahelcl** [comment]
`bin/neuralmonkey-logbook --port 5050 --logdir tests`

**Comment by jindrahelcl** [comment]
The real issue here is #58

**Comment by tomasmcz** [comment]
I see. How can we formulate this in `neuralmonkey/logbook/README.md` so that it is clear what `<experiments>` should be?

**Comment by jindrahelcl** [comment]
I would do it in the tensorboard fashion:

> where logdir points to the directory where the SummaryWriter serialized its data. If this logdir directory contains subdirectories which contain serialized data from separate runs, then TensorBoard will visualize the data from all of those runs. Once TensorBoard is running, navigate your web browser to localhost:6006 to view the TensorBoard.

That would mean that this issue is also a request for a logbook feature. In the case `logdir` points to dir with an experiment, it should show the logbook only with the one experiment.

**Comment by tomasmcz** [comment]
I agree. It might also say something like "no experiments to display" instead of "click experiment on the left" when there are no experiments in the logdir.

**Comment by jindrahelcl** [comment]
Added an ugly message of no experiment found (should not do any harm given the logbook design :-) ) in 37f579403812bc4369f5c003dd9fdae0acd1117e and

**Comment by jindrahelcl** [comment]
Now, if `logdir` contains the `experiment.ini` file, it is added as well.

This can be closed. However, a new issue could be raised if we want to list also the experiment.ini-cont.N files as separate experimetns in logbook.. But this can wait, maybe the non-overwriting is done differently in the future.
