### ISSUE TITLE
Referencing attributes of objects in configuration

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#576]
As @cifkao suggests in #556, it would be nice to extend the referencing mechanism in the config file
to be able to point at an objest's attribute:

```ini
[some_obj]
attr=val

[other_obj]
other_attr=<some_obj.attr>
```

Along with this, I suggest to support a global object (with a reserved constant name, like GLOBALS but perhaps less php-ish) which would not need to be used as a whole (unlike other objects) and whose parameters would be perhaps referencable without the GLOBALS-or-whatever prefix:

```ini
[global]
; note: no "class" attribute here
embedding_size=256

[input_sequence]
class=...
embedding_size=<embedding_size>
```

The second part is optional.

**Comment by jindrahelcl** [comment]
Also note that the GLOBALS-part should behave as a syntactic sugar for:

```ini
[embedding_size]
class=int
x=256
```

(including unused warnings)

**Comment by cifkao** [comment]
Also, it might be useful to be able to use `configparser`'s [interpolation](https://docs.python.org/3/library/configparser.html#interpolation-of-values) feature (or something inspired by that):
```ini
[test_data]
...
s_target_out="${main.output}/target.txt"
```

**Comment by jlibovicky** [comment]
I would prefer the `${...}` notation because it makes it obvious that is only a string substitution (which I believe is what we want, correct me if not). The previously mentioned notation `<an_object.its_attribute>` suggests that it is an attribute of a Python object that has been already initialized.
