### ISSUE TITLE
Adam not found in checkpoint

### ISSUE THREAD

**Issue by StoyanVenDimitrov** [ufal/neuralmonkey#595]
Hi, 

some nodes are not in the checkpoints e.g. `Not found: Key decoder/attention_decoder/Attn
OutputProjection/biases/Adam_1 not found in checkpoint`   and I cannot run a MRT model on a pretrained cross entropy model. How can I include them to the saver?

Best,
Stoyan

**Comment by StoyanVenDimitrov** [comment]
... and not only Adam. When switched to SGD some others are also missing.

`2017-11-23 20:51:10.335741: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key sentence_encoder/input_projection/word_embeddings not found in checkpoint
2017-11-23 20:51:10.339673: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key decoder/attention_decoder/AttnOutputProjection/biases not found in checkpoint
2017-11-23 20:51:10.343059: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key decoder/attention_decoder/AttnOutputProjection/weights not found in checkpoint
`

**Comment by jindrahelcl** [comment]
Is the neuralmonkey version still the same? It's possible that the names of some variable scopes have changed

**Comment by jindrahelcl** [comment]
We did not test the checkpoint functonality much (for saving and loading variables from a single model part) so it is likely a bug. But it should work when the version that saved the checkpoint is compatible with the version that loads it.

**Comment by StoyanVenDimitrov** [comment]
Yes, I forked the repository and didn’t update it since. Used the master to train a cross entropy model and my branch for the MRT. No changes should have happened.

**Comment by jindrahelcl** [comment]
Could you send the version hash so we can test it?

**Comment by StoyanVenDimitrov** [comment]
It’s the 0.2.1 version. (I hope this is what you are asking for)

**Comment by jindrahelcl** [comment]
Ok, that's it.. Could you also paste the configuration files so we can see what's going on.. Are  you using the `save_checkpoint` and `load_checkpoint` functionality, or are you using the `initial_variables` config for loading the variables?

As for Adam, it's Ok that Adam nodes are not in the checkpoint since we are saving only trainable variables.

**Comment by StoyanVenDimitrov** [comment]
The .ini for training the MRT is [1](https://github.com/StoyanVenDimitrov/neuralmonkey/blob/562d8da98e40ec5ae1c8e5637f29875f1134f7cb/examples/bpe_translation.ini)  and for the cross entropy model [2](https://github.com/StoyanVenDimitrov/neuralmonkey/blob/562d8da98e40ec5ae1c8e5637f29875f1134f7cb/experiment.ini)

I use the `initial_variables`. I pass it in the .ini

**Comment by StoyanVenDimitrov** [comment]
can close this, my bad. Somehow I mixed the encoders, as you can see in the .ini. For the X entropy used the `recurrent.py` and for MRT `sentence_encoder.py`. 
Sorry for the confusion, I'll stick to the `recurrent.py`, I guess it doesn´t impact the results after all.

**Comment by jindrahelcl** [comment]
ah, ok..
