### ISSUE TITLE
Dataset level preprocessing and postprocessing

### ISSUE THREAD

**Issue by jlibovicky** [ufal/neuralmonkey#60]
Apart from the pre- and post-processor that do something with a single data series, we will need something that will work with the whole dataset (and probably add a new series). These are the use cases I have in mind:
- the end-to-end post-editing task - we need take the source sentence and the generated edits in order to get the output;
- factored translation - decoder(s) will generate pairs of lemma+POS as two series and we will call some morphological post-processing that will generate the actual forms.

**Comment by jindrahelcl** [comment]
@jlibovicky  neni tohle už hotový?

**Comment by jlibovicky** [comment]
Teoreticky je tam na to připravený hook, ale nemá to jedinou existující implementaci, takže to není a nemůže být otestované.

**Comment by jlibovicky** [comment]
Done with #278.
