### ISSUE TITLE
pad_to_max_len doesn´t work

### ISSUE THREAD

**Issue by StoyanVenDimitrov** [ufal/neuralmonkey#603]
Hi,

I set `pad_to_max_len` in the `AutoregressiveDecoder`, but it doesn´t work. Any ideas?

Best, 
Stoyan

**Comment by jindrahelcl** [comment]
Hi, what do you mean?

Padding to maximum length is turned off in the decoder (https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/decoders/autoregressive.py#L308). You are saying that setting it to `True` does not work (e.g. you don't get the same shape of the input tensors)? In that case, there could be a bug in the vocabulary, but I doubt it..

**Comment by StoyanVenDimitrov** [comment]
Hi, 

yes, I set it to `True`, but the inputs are still cut to the length of the longest input in the batch. I just switched to the current NM Version, with the 0.2.1 `pad_to_max_len` worked well.

**Comment by jindrahelcl** [comment]
hmm.. are you setting the padding also in the encoder or do you only want to have unified lengths of targets across batches?

**Comment by StoyanVenDimitrov** [comment]
I want to have the targets up to a full sentence length. Because I treat them as sampled candidates, like the candidates that are sampled. They are sampled to full sentence length and I operate always on full length. So if a candidate is shorter than this I want to pad it.

**Comment by varisd** [comment]
Hi,

Can I ask you for the configuration file you are using so I can check the problem? Thanks

**Comment by StoyanVenDimitrov** [comment]
Hi, 

sure: https://github.com/StoyanVenDimitrov/neuralmonkey/blob/master/examples/bpe_translation.ini
