### ISSUE TITLE
Unit tests failing only on Travis

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#62]
Can you look into this:

https://travis-ci.org/ufal/neuralmonkey/jobs/143296737

pull the corresponding commit and run the tests yourself and check if you can replicate this. Otherwise, check the Travis settings, which are next to blame. It seems the Perl script is not run correctly. As far as I  know, there are no additional dependencies for Perl to be installed, but maybe Perl itself is missing from the Travis instance.

**Comment by jindrahelcl** [comment]
If something needs to be fixed in the code, do it in branch bleu_tests as a part of pull request  #63

**Comment by tomasmcz** [comment]
There is no Perl on Travis, unless you explicitly ask for it. I would also be happier if we could avoid this huge dependency. Is there any reasonable way to do this without Perl?

**Comment by jlibovicky** [comment]
Perl is a big dependency, on the other hand the pure Perl is by default on every Linux distribution. Later, it may also appear to be useful to have wrappers for some originally Moses tools like various tokenizers, true-casing, etc., which is all in Perl.

Regarding BLEU, there are some Python implementations with unclear or unfriendly licence:
- https://gist.github.com/odashi/8092484
- https://github.com/vikasnar/Bleu
- https://github.com/tylin/coco-caption/blob/master/pycocoevalcap/bleu/bleu_scorer.py

You can still write yourself in Python and I am sure it will more reliable than the NLTK implementation.

**Comment by jlibovicky** [comment]
Wraper na wraper je něco jako rovnák na vohejbák. Napište radši svoje BLEU. :-)

**Comment by martinpopel** [comment]
Ten mteval-v13a.pl je dost hrůza (byť to z CPANu potřebuje jen XML::Twig, jinak tomu stačí jakýkoli perl). Jedinou výhodu to má, že to je **the** reference implementation. Když člověk nepotřebuje mít oficiální BLEU (mírné rozdíly kvůli tokenizaci a vyhlazování nevadí) a má jen jednu referenci a nepotřebuje NIST (stačí BLEU), tak to jde napsat o dost jednodušeji, elegantněji a určitě to i poběží rychleji. I tak doporučuji dělat tokenizaci v rámci výpočtu BLEU (tedy předpokládat vstup detokenizovaný).

Mimochodem mteval-v13a.pl vyžaduje příšerný xml formát na vstupu, navíc to je paranoidní a chce to i věty ve zdrojovém jazyce, které k výpočtu BLEU nejsou vůbec potřeba. Proto jsem si na to napsal ten wrapper. Docela mi k tomu sedí ten název "rovnák na vohejbák".:-)

**Comment by tomasmcz** [comment]
@jlibovicky Not every system is a linux distribution.

I am not against calling Perl tools outside of the package, but I would like to avoid Perl inside. Are we using the reference implementation for anything other than tests? Do we really need to test this regularly?

**Comment by jindrahelcl** [comment]
@tomasmcz Everyone who installed Tensorflow has Perl and there in no point assuming otherwise. Unless maybe you want to support users with Macs. Which I don't.

**Comment by jindrahelcl** [comment]
Now, the reference BLEU score is used to compute BLEU on every logging occasion and on every validation. It did not bring any significant slow-down.

**Comment by jindrahelcl** [comment]
@martinpopel @jlibovicky V tom přápadě už máme zase vohejbák na rovnák na ten původní vohejbák.. Ale funguje to slušně a napsal jsem k tomu i nějaký unit testy, podle kterých se taky zdá, že to běží.

**Comment by jindrahelcl** [comment]
Můžem napsat vlastní BLEU. Nicméně je asi dobrý mít i tohleto na získávání čísel porovnatelných s článkama. Vlastní BLEU už je napsaný, ale je tam ještě pár bugů, a tak to nevychází stejně jako to referenční

**Comment by tomasmcz** [comment]
Examples of systems where Perl isn't installed by default: Windows (where I would also like to be able to develop this), various VMs (e.g. Travis).

If you insist on using Perl, I can fix the Travis config and we should update README to reflect that Perl is a dependency.

**Comment by jindrahelcl** [comment]
Tensorflow is not for Windows. You have to use Docker, with which I assume you either have Perl for free completely, or installed with a very very low effort.

**Comment by jindrahelcl** [comment]
To summarize:

1. put Perl on Travis so the wrapper for the reference implementation can be tested.
2. don't put Perl on project requirements
3. create and maintain list of recommended (or module-specific, if you want) requirements, that will contain all requirements not needed to run the slut, but needed to some parts (e.g. reference BLEU, nltk BLEU, scipy in some bin/ scripts, etc.)

This way, everybody wins.

**Comment by jlibovicky** [comment]
Sure. I think it's perfectly O.K. to say: if you want to use wrappers for some standard MT scripts, you will need Perl (which probably everyone doing MT already have) and if want to have some image processing in the model, then you will need scipy.

**Comment by tomasmcz** [comment]
Native Windows support for TF is planned for near future.

I'm OK with wrappers for wrappers for MT tool wrappers requiring Perl, but I think that default test suit should be able to run with just what is listed in the README. So either it should not depend on Perl, or Perl should be listed there (maybe with a note that it is only needed for specific modules and the test suite).

**Comment by jindrahelcl** [comment]
What if the test suite checked if perl is there and enabled/disabled some tests accordingly? (As in many ohter unix-like package-oriented worlds)

**Comment by tomasmcz** [comment]
OK. Will you do that for your Perl-tests? After we see that it works everywhere, I will learn how to enable Perl on Travis.

**Comment by tomasmcz** [comment]
I was wrong – there is Perl on Travis by default. `This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi`. But for some reason, the wrapper seems to always return 0. This does not happen on my local computer. Happy debugging (this is exactly why I would avoid Perl).

**Comment by jindrahelcl** [comment]
Bleu ref wrapper has been deprecated, closing this. No need for Perl now.
