### ISSUE TITLE
bleu_ref breaks Python 3.4 compatibility

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#64]
Question is: should we fix this and try to maintain Python 3.4 as well as 3.5 or should we just say we only support 3.5 (which is something we might want to do in the future anyway, to enable 3.5 type annotations)?

**Comment by tomasmcz** [comment]
See `big_tests` branch Travis results for errors.

**Comment by jindrahelcl** [comment]
As in numerous discussions on this topic, the simplest and cleanest way is to recommend 3.5 but don't require it. Since this is an optional module, it does not harm anything.

Also, I have already done a checking in the unit test which skips the testing if the Python version is older. (not pushed yet).

**Comment by tomasmcz** [comment]
If this is an optional module, why is it in the main test (`tests/small.ini`)?

**Comment by tomasmcz** [comment]
Also, "optional modules" should be clearly marked and their dependencies documented. How would  the user be supposed to know that this particular module works only with Python 3.5, while rest of the package works works with any Python 3?

**Comment by jindrahelcl** [comment]
I would ditch all but the newest version of python 3.. I am not going to spend time on support of an outdated version of Python (unlike 2.7, which is not compatible with 3.*). If you want to use this on Metacentrum, write to Mr. Zdeněk and he will add the module. Everyone else should be able to manage to get Python 3.5 (if there are reasons why they don't, they probably apply also to users with Python 2.7 which we abandoned).

**Comment by tomasmcz** [comment]
I wouldn't call Python 3.4 _outdated_. TF only added support for 3.5 21 days ago, most (if not all) computers at MFF still have 3.4, Python 3.5 is only default in the latest Ubuntu and so on.

For the time being, I think that it would be better to fix the one offending file to work with both versions than introduce different test behavior for different versions.

What does @jlibovicky think?

**Comment by jindrahelcl** [comment]
> For the time being, I think that it would be better to fix the one offending file to work with both versions than introduce different test behavior for different versions

You're welcome to do it.

**Comment by jlibovicky** [comment]
I would say, that probably everyone who is able to train an MT system, is probably able to make Python 3.5 run on her or his machine. I wouldn't expect anybody having decided not use our software because of Python 3.5. (Though there are tons of other reasons for not no using NM. :-P) So, let's go from >=3.5.

**Comment by tomasmcz** [comment]
@jlibovicky Two weeks ago I wouldn't have been able to run Python 3.5 on UFAL computers without considerable overhead in preparation (although my ability to train an MT system is also questionable, so I may not be a good counter-example). 

Anyway, if we only support Python 3.5, we should state that in README and `prepare_env.sh` should either reflect this change or disappear.

**Comment by jindrahelcl** [comment]
It's really no big deal. You can even do it without Mr. Zdeněk's help. I've just installed neuralmonkey _and_ Python 3.5 from scratch without superuser permissions it myself and I am already running an experiment. (cca 40 min of low-energy work).

**Comment by jindrahelcl** [comment]
Btw. that 40 minutes included one installation of python 3.6 and then removing it because tensorflow does not support it.

**Comment by jindrahelcl** [comment]
Closing this discussion, bleu_ref is deprecated since 8d5112
