### ISSUE TITLE
bleu_ref.py returns 0 when wrapper fails

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#65]
Why does the call to `BLEUReferenceImplWrapper` return 0.0 when receiving incorrect output from the wrapper? Shouldn't it throw an error?

Also, why does it print and not log?

**Comment by jindrahelcl** [comment]
I made this decision because the evaluation used to crash on suspicious data. But we don't want to crash when the mteval script crashes, because it happens rarely and the rest of the evaluations still yield reasonable numbers. The evaluation itself should never interrupt the training process - the numbers that come out of it do not affect the training so it should not matter if they are sometimes broken.

You're welcome to fix the prints.

**Comment by tomasmcz** [comment]
I think I would like to crash when the evaluation crashes. Or at least read in the log that something strange happened.

**Comment by tomasmcz** [comment]
Btw. if there was code review or at least a pull request, this would have been revealed and discussed before we found that in certain conditions (e.g. on Travis), bleu_ref doesn't work at all, so this error-hiding behavior really isn't ideal.

**Comment by jindrahelcl** [comment]
who said that bleu_ref does not work?

**Comment by tomasmcz** [comment]
Your tests says so #62.

**Comment by jindrahelcl** [comment]
But that is the reason why there are the tests, in the first place.. They check for this error and expose it.

**Comment by jindrahelcl** [comment]
It is __not__ good when you run the experiment for weekend, and when you get back, you learn that it crashed after two hours on an error that had no chance to influence the training itself.

**Comment by jindrahelcl** [comment]
During training, every error that can be handled, should be handled. Crashes during training should be avoided at all costs.

**Comment by jindrahelcl** [comment]
Lastly, there __is__ a pull request where you can adress this problem ( #63 ).

**Comment by tomasmcz** [comment]
Test cannot catch certain errors, for example when the error is that you are masking errors, like here. Tests also don't catch unreadable code and other things that would be easier solved before adding that code to the codebase, not half a year later when they cause real problems.

I disagree. When you sustain the training at all costs, you might end up with weekend of useless, incorrect data and don't even know about it. Whenever there is an error, the program should fail. If you fear that your over-the-weekend experiment will fail, test your configuration on smaller data beforehand.

There was no pull request for `bleu_ref.py`, it was commited and pushed directly to master (af9e96f29f06b1bf352075bb0ea499a6fbfee5ba). The pull request you are referencing has nothing to do with this issue, except for my tangential note about `bleu_ref.py` not working on Travis, which as far as I can tell, is something in the Perl code, in no direct connection to the problems I have with `bleu_ref.py`.

**Comment by tomasmcz** [comment]
As if models running with bugs without failing already wasn't one of the biggest challenges in machine learning...

**Comment by jindrahelcl** [comment]
Yeah, except the bleu computation is not a part of the model.

**Comment by tomasmcz** [comment]
Well, it might be one day (we talked about training to BLEU) and I will not remember it forever that this module might behave strange without failing. And even when it isn't, I don't want to be wondering whether an evaluation module encountered an error without failing or my model is really that bad when all the scores are zero.

**Comment by jindrahelcl** [comment]
As I wrote earlier, the wrapper _used to_ crash on suspicious circumstances. Now, it works. The suspicious circumstances are subject to the unit test. The exception handling serves but as a remnant of those cruel times. Do what you want, but do it already.

**Comment by tomasmcz** [comment]
Now it "works" (#62) so there is no need to mask its errors so we should just re-raise them instead of returning 0. I don't have time for that now, so either fix it (it's your code after all) or leave this issue open until I get to it.

**Comment by jindrahelcl** [comment]
wont fix, bleu_ref is deprecated by 8d5112
