### ISSUE TITLE
Abstract predecessor class for neuralmonkey.evaluators

### ISSUE THREAD

**Issue by varisd** [ufal/neuralmonkey#667]
In the spirit of OOP, all neuralmonkey.evaluators should be unified through a single predecessor class AbastractEvaluator (or BaseEvaluator) with abstract __call__() method (with signature [[List[List[Any]], List[List[Any]]], float]).

**Comment by jlibovicky** [comment]
I think it should be `List[Any], List[Any] -> float`. Output of a runner is not necessarily a list.

**Comment by varisd** [comment]
I based the signature on a quick look at evaluators/bleu.py
If it differs between the evaluators than we have more motivation for this refactor. However in the end, it might not be beginner friendly.
