### ISSUE TITLE
Run script loads training dataset

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#67]
Runner should not load the training dataset again.

**Comment by jlibovicky** [comment]
Where is this happening?

**Comment by jindrahelcl** [comment]
I am trying to run this now, maybe I've got it wrong. I've run the training from commit cc1ec7d. I use the same ini script that I used for training (see attachment `qtleap-alpha.ini`), and I use the `val_dataset.ini` as the dataset config.

It seems the dataset arguments are not ignored.

I am also getting errors probably caused by the dataset init helper:

```
Error while loading 'val_data': '_sre.SRE_Match' object is not subscriptable
(...)
File "/home/jihe01/mmmt/bin/neuralmonkey/config/utils.py", line 46, in <dictcomp>
    if SERIES_OUTPUT.match(key)}
```

[val_datasets.ini.txt](https://github.com/ufal/neuralmonkey/files/361253/val_datasets.ini.txt)
[qtleap-alpha.ini.txt](https://github.com/ufal/neuralmonkey/files/361252/qtleap-alpha.ini.txt)

**Comment by jindrahelcl** [comment]
It seems I've figured out the error. There was a leftover Python 2 matching of the regex.

**Comment by jlibovicky** [comment]
Is this solved?

**Comment by jindrahelcl** [comment]
It shoudl be solved in the experiment object branch. (#73) (berliner refactor)

**Comment by jlibovicky** [comment]
I don't think it happens any more, though I don't when it got fixed.

**Comment by jindrahelcl** [comment]
AFAIK it's not fixed.. I use two separate configuration files for this.

2016-11-30 13:19 GMT+00:00 Jindřich Libovický <notifications@github.com>:

**Comment by jlibovicky** [comment]
According to the tests cases logs it does happy any more.

**Comment by jindrahelcl** [comment]
:D :D cože? :-)

**Comment by jlibovicky** [comment]
:-D už je to dobře

**Comment by jindrahelcl** [comment]
škoda.. :-)

**Comment by tomkocmi** [comment]
Isn't it somehow connected with #210 ?

**Comment by jlibovicky** [comment]
Not at all. This was about handling configuration in `run.py` script.
