### ISSUE TITLE
Replicate NMT scores of Bahdanau et al. (2015)

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#68]
Use neuralmonkey to replicate the scores of [Bahdanau et al. (2015)](https://arxiv.org/pdf/1409.0473v7.pdf) on English-to-French, [WMT-14 translation task](http://www.statmt.org/wmt14/translation-task.html)

This would mean to do the following things:
- [x] Include the domain adaptation of [Axelrod et al. (2011)](https://aclweb.org/anthology/D/D11/D11-1033.pdf)
- [x] Include the tokenization script from Moses (somehow related to #32)
- [x] Adapt the code to the equations in the paper
- [ ] Make sure we are able to run beam search with the trained model

Anything else?

**Comment by jindrahelcl** [comment]
For replicaton, the domain adaptation is not required - the filtered WMT data are available on http://www-lium.univ-lemans.fr/~schwenk/cslm_joint_paper/

**Comment by jlibovicky** [comment]
I would expect the pseudo-in-domain-selection to have some scripts (probably in Perl) in the Moses code base. @ales-t was using it, he probably knows more. 

It would be also good to claim in the paper, we can replicate a state-of-the-art result and provide a script that will prove it.

**Comment by jindrahelcl** [comment]
> It would be also good to claim in the paper, we can replicate a state-of-the-art result and provide a script that will prove it.

Yes, that was my motivation for opening this issue.

**Comment by jindrahelcl** [comment]
It can prove challenging, though. I fear the model they used will not fit into any of our GPU's memory (I have a 6GB titan, same size as the cards on UFAL)

**Comment by ales-t** [comment]
About the in-domain selection: you need two language models compatible with
SRILM, one trained on "guaranteed" in-domain data, the other trained on
general/out-of-domain data. They should both have identical n-gram length
and similar training data sizes. People also typically filter out
singletons (replacing them with <UNK>) when doing this.

Once you have the LMs, you can run this simple tool to score your sentences:

https://redmine.ms.mff.cuni.cz/projects/ufal-smt-playground/repository/revisions/master/show/playground/tools/lmppl

**Comment by jindrahelcl** [comment]
Thanks. Do you think it is applicable when the only real in-domain data I have is a very small dev set (~2k sentences)? (The in-domain part of the training dataset I have is very noisy and probably wouldn't do good) 

Also, given the size of the in-domain corpus, is it then better to train the general language model on a random 2k-sentence-subset of the whole data than on a different subset?

**Comment by ales-t** [comment]
Hm, you can try it but I don't think this is enough data. Your OOV rate
will be very high and generalization might be poor. It's hard to guess in
advance though.

Ales

**Comment by jindrahelcl** [comment]
Attention decoder implementation now follows equations in the paper (PR #77).

**Comment by jindrahelcl** [comment]
As for the domain adaptation and tokenizer, I would just put a note (or possibly a script) in the experiment directory with instructions of how to obtain the en-fr wmt task filtered data (these are available) and how to tokenize the data.

The product of this issue will be a directory inside `examples/` with `ini` file and scripts/instructions how to prepare the data.

**Comment by jindrahelcl** [comment]
Issues s beam searchem je tu hromada, tohle je jinak už hotový.
