### ISSUE TITLE
NMT with Recurrent Attention Modeling

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#69]
Incorporate this: https://arxiv.org/pdf/1607.05108v1.pdf

**Comment by jlibovicky** [comment]
Got merged wtih #436.

**Comment by loveJasmine** [comment]
how to enable/disable this feature in ini file?

**Comment by jindrahelcl** [comment]
That should be sufficient. Depending on the version of Neural Monkey, it may be required to also supply `attention_state_size` to the encoder as well.
