### ISSUE TITLE
Cannot import 'Levenshtein'

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#7]
Cannot import 'Levenshtein' when trying to run pylint on `evaluation.py`. This means that a package is missing in requirements.txt.

**Comment by jindrahelcl** [comment]
added python-Levenshtein to requirements

**Comment by tomasmcz** [comment]
Now it says `No name 'ratio' in module 'Levenshtein'`. Is `python-Levenshtein` the correct package? Do we need a specific version?

Also, @jindrahelcl, you should not close an issue (particularly if it is not you who opened it or you who wrote the code in question) unless you verify that it is resolved.

**Comment by jindrahelcl** [comment]
the package is correct (https://rawgit.com/ztane/python-Levenshtein/master/docs/Levenshtein.html#Levenshtein-ratio) and dir(Levenshtein) lists ratio as one of its members.

**Comment by tomasmcz** [comment]
This is strange, pylint keeps complaining on both computers I tried this on. I decided to locally disable the warning until this is solved.

@jindrahelcl, you also said that you added the requirement, but you did not actually push any commit...

**Comment by jindrahelcl** [comment]
Yeah, I've pushed it to the old remote..

**Comment by jindrahelcl** [comment]
Anyway, pylint is complaining about it on my computer, too..

**Comment by jlibovicky** [comment]
You could have checked the packages in prepare_env.sh script which I keep maintained. Now (1948856) it uses the requirements.txt.  I made a new clone, installed the requirements and it seems to be all right.
