### ISSUE TITLE
Add initial_variables option to the second ini file when running

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#72]
Now, initial variables of the model are taken from the file "variables.data.best" in the experiment's output directory. I suggest to put this configuration in the second ini file that the runner takes, along with the data it uses.

**Comment by jlibovicky** [comment]
Originally, the scenario I had in mind was that you train several models and then you want run all the models (with their own config files) on the same datasets and share the dataset configuration file. In this use case, I would rather copy the original experiment config file and edit it. (I am not sure whether it is possible now, but it certainly used to be at some point, it was called `initial_variables`.) I wouldn't also mess up the definition of the model (this what the experiment.ini contains, including instructions how to train it) and the data, unless we are sure that this little hack will save a lot of time for our users.

**Comment by jindrahelcl** [comment]
> copy original experiment config and edit it

Yes, now it is possible and it is the way I am using it.

> it was called `initial_variables`

It is, but it is amongst the ignored arguments when running - the run script in master uses "variables.data.best" (zadrátovaně). ([here] (https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/run.py#L30) and [here] (https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/run.py#L51-L59)) 

I would prefer to have one configuration of the architecture of the model (plus training) and a set of configruations with datasets and initial variables (for running). But it seems more of a matter of taste. 

Another approach would be to supply the variable file for the run command as a command line parameter, but it's not my favorite.

**Comment by jindrahelcl** [comment]
@jlibovicky Btw, the dataset config files are containing the output file, which pretty much prevents their re-use..

**Comment by jindrahelcl** [comment]
This is done now
