### ISSUE TITLE
Convert named tuples to classes

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#721]
See e.g. this code:
https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/gan/python/namedtuples.py

The named tuples are created as classes that are derived from named tuples.

This will make a beautiful code because 1) we get rid of a lot of  #pylint: disable lines, 2) namedtuples will become easily documentable, 3) inheritance will become simple

**Comment by jindrahelcl** [comment]
And, they will become classes which means they could also have user-defined methods.

**Comment by varisd** [comment]
I just want to mention that we should be careful to not break the compatibility with the nest.map_structure method, we use together with the named tuples.

Other than that, it seems like a good idea to me.

**Comment by jindrahelcl** [comment]
The new structures will still be tuples so nest.map_structure will work with them as well.
