### ISSUE TITLE
Float of type 1e-3 is not parsed correctly in ini

### ISSUE THREAD

**Issue by Simon-Will** [ufal/neuralmonkey#725]
Floats of the type `1e-3` are not accepted by the parser because the FLOAT regex in the file [`parsing.py`](https://github.com/ufal/neuralmonkey/blob/5b3adca5906321dfecdd8f7be78af392650a360f/neuralmonkey/config/parsing.py) does not match. It only matches if there is a dot (like in `1.0e-3`).  `1e-3` is a correct python float, though, and floats like this are also generated by templating systems like jinja2.

Therefore the FLOAT regex should be adjusted. I would be happy to do this and will send a pull request if that’s okay.

**Comment by jindrahelcl** [comment]
Hi, thanks, we are aware of this issue. If you send a pull request it'll be great.

**Comment by Simon-Will** [comment]
I have sent it.
