### ISSUE TITLE
experiment.py crashes when git is not available

### ISSUE THREAD

**Issue by Simon-Will** [ufal/neuralmonkey#726]
In [`experiment.py`](https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/experiment.py) there is a dependency on the command `git` being installed on the system. While saving the git commit and diff is certainly useful, git is not always available, especially on GPU computing servers.

I propose failing gracefully and just logging a warning that git is not available and git diff and git commit are not stored. I would be happy to do this and will send a pull request for this as well.

**Comment by jindrahelcl** [comment]
Good idea. Thanks.

**Comment by varisd** [comment]
Wasn't this resolved by #730 ?

**Comment by jindrahelcl** [comment]
Yes
