### ISSUE TITLE
DelayedUpdateTrainer.objective_buffers called twice without variable reuse

### ISSUE THREAD

**Issue by varisd** [ufal/neuralmonkey#788]
Atrribute Method DelayedUpdateTrainer.objective_buffers is being called twice,

once in:
https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/trainers/delayed_update_trainer.py#L156

and second time in:
https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/trainers/delayed_update_trainer.py#L173

There is no explicit specification of the variable reuse so I assume that each class method works with a different list of graph variables. Next time, I recommend using tf.get_variable + proper naming instead of using carelessly using tf.Variable

**Comment by jindrahelcl** [comment]
`self.objective_buffers` je `@tensor`, takže se volá jen jednou.
