### ISSUE TITLE
Decoder emits <unk> tokens even on a closed vocabulary task

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#80]
Should we introduce an option to exclude the `<unk>` token from a vocabulary?
This feature would be used in combination with Byte-pair encoding. One would expect the decoder to quickly learn not to emit `<unk>` tokens, but it seems it's not that certain.

**Comment by jindrahelcl** [comment]
My answer to this question is yes. Vocabulary should be either open or closed. Since closed vocabulary does not use the `<unk>` token, I would create the vocabulary without it.

As in #87, closed vocabulary won't perform the `<unk>` sampling.

The proposed solution is to make the default vocabulary closed, and make a subclass for open vocabularies (since they bring additional functionality). In addition, the open vocabulary subclass will have an attribute which will specify whether to sample `<unk>` tokens or not.

Config helper functions would return the correct type of vocabulary:
- `vocabulary_from_dataset` return an open vocabulary with the ability of sample `unk` tokens, specified by an argument (which will default on `True`)
- `vocabulary_from_file` return whichever vocabulary was saved in the file
- `vocabulary_from_bpe` return closed vocabulary generated from BPE merge file.

**Comment by jlibovicky** [comment]
That sounds fair enough. Before we do that, we need to check for places where the special tokens are hard-coded (I would bet there are some in the decoder, at least for `<s>` and `</s>`). What we can do about it is having special properties on the vocabulary class returning the indices of special tokens and throwing an exception if the special token (e.g. `<unk>`) is unavailable.

Nevertheless, it is suspicious, that the `<unk>`s appear in the output while using BPE, because there aren't any in the training data. The network should very quickly learn not to use them. If they survive on the output, it may signalize something elsewhere is wrong.

**Comment by jindrahelcl** [comment]
I think the `<unk>` was appearing in the outputs of the BPE training because it was sampled. (#87)

**Comment by jlibovicky** [comment]
OK, that makes sense.

**Comment by jindrahelcl** [comment]
There are other things to be considered. When using the closed vocabulary, one must ensure that no OOV words get to the input. In the case of BPE, out-of-alphabet characters must be recognized and processed. A word that contains an OOA character is still correctly segmented (e.g. šžětion becomes š + ž + ě + tion), but then š, ž and ě are unks and if we use them on run-time, the system must not crash...

**Comment by jlibovicky** [comment]
Good point, but its only the input vocabulary, isn't it? The output vocabulary can be still closed. Or you can do some dirty tricks to keep the input vocabulary closed as well - like remove accents for the OOV characters first and if it does not helps, remove the character entirely (having weird non-latin characters is probably not so often).

**Comment by jindrahelcl** [comment]
Probably the simplest way is to keep the `unk` token in the vocabulary and rely on the network to learn not to use it by not sampling it..

Can you take a look here: https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/vocabulary.py#L117
and explain why end tokens are appended only on some sentences while others have valid words on [n+1]-th position (despite the max_len)?

**Comment by jlibovicky** [comment]
I think this is correct. Index `i` from the outer loop iterates over the sentence length (which has a fixed upper bound `max_len + 1`). Index `j` iterates over the batch, variable `sent` is then the j-th sentence in the batch. We only can write number for tokens which are inside the sentence, i.e. tokens whose index `i` is smaller than the actual sentence length, this is the condition on line 117. When index `i` is equal to the sentence length, it points to the first position after the sentence (condition on line 121), therefore the `</s>` symbol is placed on this position. All the other positions in the tensor remain unchanged. Am I right?

**Comment by jindrahelcl** [comment]
Yes I think so. I was concerned about the fact that some of the resulting sentences (the ones that have been longer than `max_len + 1` words are not terminated with the `</s>` token. This could be right, in the way that we are not learning the network to cut long sentences, but it can be wrong because this behavior not obvious on the first look at the method.

**Comment by jlibovicky** [comment]
Oh, I see. It seemed kind of obvious to me that it would force the network to memorize the maximum sentence length and even if increased the `max_len` during run time, the network would not decode longer sentences. But it's just my intuition, I might be wrong, but I am pretty sure, this would happen. You may certainly try and find out what the result will be.

**Comment by jindrahelcl** [comment]
#82 introduces the `unk_sample_prob` parameter of the vocabulary which is set by default to 0 when loading vocabulary from BPE merge file, to 0.5 when loading the vocabulary from a dataset and to whatever the value was when loading from pickle.

**Comment by jlibovicky** [comment]
Does it mean it's solved since #82?

**Comment by jindrahelcl** [comment]
Ty jo, nevim.. Ale rozhodně můžeš teďkon tu unk_sample_prob nastavit z konfiguráku. Takže jo. Já bych to zavřel a udělal issue, aby na to vznikly unit_testy, který mi teď přijdou jako jedna z nejvyšších priorit.
