### ISSUE TITLE
Requirement of editing the post-edit.ini and translation.ini for APE and MT respectively

### ISSUE THREAD

**Issue by rupjyotiBaruah** [ufal/neuralmonkey#824]
Dear, Sir
Is there any editing required according to my own machine configuration for "model configuration" of both Post Editing Task(post-edit.ini) and Machine translation Task(translation.ini)
as it is given by  "https://neural-monkey.readthedocs.io/en/latest/tutorial.html"?
I mean the same task configure in my machine ??

**Comment by jindrahelcl** [comment]
Hi, as stated in #823, the tutorials are outdated, so some configuration tweaking is necessary. Refer to `tests/bahdanau.ini`, `tests/post-edit.ini`, `tests/bpe.ini`, tests/transformer.ini`, or `tests/small.ini` for working examples of the translation/post-editing configuration.
