### ISSUE TITLE
 Did you mean file './dataset.load_dataset_from_files'? 

### ISSUE THREAD

**Issue by rupjyotiBaruah** [ufal/neuralmonkey#831]
neuralmonkey.config.exceptions.ConfigBuildException: Error while loading 'train_dataset': Interpretation 'dataset.load_dataset_from_files' as type name, class 'load_dataset_from_files' does not exist. Did you mean file './dataset.load_dataset_from_files'? 
module 'neuralmonkey.dataset' has no attribute 'load_dataset_from_files'

**Comment by jindrahelcl** [comment]
`load_dataset_from_files` is obsolete. Use `dataset.load` instead. 
https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/dataset.py#L207
Look at tests/*.ini for examples on usage.
