### ISSUE TITLE
Option to disable <unk> sampling during training.

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#87]
For closed-vocabulary tasks (such as when using BPE), `<unk>` sampling should be disabled. Related to #80.

**Comment by jlibovicky** [comment]
What do you mean by sampling?

**Comment by jindrahelcl** [comment]
This: https://github.com/ufal/neuralmonkey/blob/master/neuralmonkey/vocabulary.py#L49

**Comment by jindrahelcl** [comment]
Github hid the `<unk>` in the description because it wasn't enclosed in backticks

**Comment by jlibovicky** [comment]
Then yes, we should have this one. :-)

**Comment by jindrahelcl** [comment]
Done in #82
