### ISSUE TITLE
Logging of config building

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#93]
The contents of the `experiment.log` file start after the config is built. It would be nice if the file contained also the output from config building. The thing is we need to parse the config first in order to know where to store the file.

I suggest to save all text output to a variable and dump it to the log file as soon as the logging file is initialized.

**Comment by jlibovicky** [comment]
What information are printed during the config building and what are they useful for? From my point of view, the logs during the config building serve mostly debugging the configuration. Once you have it running, all you need to know is in the debugged config file. Adding it would make the log even more cluttered than it is now. So, my question is: what would it be useful for?

Nevertheless, what you suggest is a good idea if we need it.

**Comment by jindrahelcl** [comment]
This morning, I was comparing the monster_decoder with decoder and I wanted to see if a training process that runs now outputted something during the config building or not. Then I realized I cannot see what it logged because that was before the logging was initialized.

And since it was not the first time I had this problem, it was enough for me to create the issue here.. :-)

Anyway, it is a very low priority issue. The real issue is the comparison between the two decoders - there seems to be no difference in semantics of the code, but in reality, the monster_decoder performs much better on translation tasks and I don't see why.

**Comment by jlibovicky** [comment]
But you can always have a look into the configuration file to see which decoder you have used, can't you?

If the monster does something else (or even better) than the standard decoder, it is the real issue that should have a priority.

**Comment by jindrahelcl** [comment]
That's what I wanted to say.. I've been looking into this but I can't spot any difference.
