### ISSUE TITLE
TensorFlow version in requirements.txt

### ISSUE THREAD

**Issue by jvdbogae** [ufal/neuralmonkey#96]
I am not sure whether adding the TensorFlow .whl is a good idea.
I ran the requirements script on a pascal machine (which requires cuda 8), resulting in the custom compiled tensorflow being overwritten.

**Comment by obo** [comment]
Tom will just add a warning to avoid --upgrade to the docs.

**Comment by obo** [comment]
If I understand Tom's comment above, this is resolved; closing.
