### ISSUE TITLE
support for gzipped input files

### ISSUE THREAD

**Issue by obo** [ufal/neuralmonkey#99]
Support for gzipped input files would _greatly_ help any larger experiments.

Support for gzipped input files should cover also bpe_merges, simply anything the user is potentially expected to provide and cannot be fed in through stdin (or <(zcat...) on commandline)

**Comment by jindrahelcl** [comment]
support for gzip input dataset files added in 47c57 in PR #77

**Comment by jindrahelcl** [comment]
what to do:.
- [ ] explicit setting of the readers for each data series (unavoidable)
- [ ] gzipped output series
- [ ] support for gzipped BPE merges

**Comment by tomkocmi** [comment]
I have corrected bug and documented it in #212

**Comment by jlibovicky** [comment]
Do we really need gzipped output and gzipped BPE merges? Gzipped output would require introducing a concept of writer or something like this.

**Comment by jindrahelcl** [comment]
no
